<?php

declare(strict_types=1);

/*
 * SplititWebApiV4Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SplititWebApiV4Lib\Authentication;

/**
 * Interface for defining the behavior of Authentication.
 */
interface ApiKeyCredentials
{
    /**
     * String value for xSplititApiKey.
     */
    public function getXSplititApiKey(): string;

    /**
     * Checks if provided credentials match with existing ones.
     *
     * @param string $xSplititApiKey Terminal API Key
     */
    public function equals(string $xSplititApiKey): bool;
}
