<?php

declare(strict_types=1);

/*
 * SplititWebApiV4Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SplititWebApiV4Lib\Authentication;

use Core\Utils\CoreHelper;

/**
 * Utility class for initializing ApiKey security credentials.
 */
class ApiKeyCredentialsBuilder
{
    /**
     * @var array
     */
    private $config;

    private function __construct(array $config)
    {
        $this->config = $config;
    }

    /**
     * Initializer for ApiKeyCredentialsBuilder
     *
     * @param string $xSplititApiKey
     */
    public static function init(string $xSplititApiKey): self
    {
        return new self(['xSplititApiKey' => $xSplititApiKey]);
    }

    /**
     * Setter for XSplititApiKey.
     *
     * @param string $xSplititApiKey
     *
     * @return $this
     */
    public function xSplititApiKey(string $xSplititApiKey): self
    {
        $this->config['xSplititApiKey'] = $xSplititApiKey;
        return $this;
    }

    public function getConfiguration(): array
    {
        return CoreHelper::clone($this->config);
    }
}
