<?php

declare(strict_types=1);

/*
 * SplititWebApiV4Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SplititWebApiV4Lib\Authentication;

use Core\Authentication\CoreAuth;
use SplititWebApiV4Lib\ConfigurationDefaults;
use Core\Request\Parameters\HeaderParam;

/**
 * Utility class for authorization and token management.
 */
class ApiKeyManager extends CoreAuth implements ApiKeyCredentials
{
    /**
     * @var array
     */
    private $config;

    public function __construct(array $config)
    {
        $this->config = $config;
        parent::__construct(HeaderParam::init('X-Splitit-Api-Key', $this->getXSplititApiKey())->requiredNonEmpty());
    }

    /**
     * String value for xSplititApiKey.
     */
    public function getXSplititApiKey(): string
    {
        return $this->config['xSplititApiKey'] ?? ConfigurationDefaults::X_SPLITIT_API_KEY;
    }

    /**
     * Checks if provided credentials match with existing ones.
     *
     * @param string $xSplititApiKey Terminal API Key
     */
    public function equals(string $xSplititApiKey): bool
    {
        return $xSplititApiKey == $this->getXSplititApiKey();
    }
}
