<?php

declare(strict_types=1);

/*
 * SplititWebApiV4Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SplititWebApiV4Lib\Models\Builders;

use Core\Utils\CoreHelper;
use SplititWebApiV4Lib\Models\AmountData;

/**
 * Builder for model AmountData
 *
 * @see AmountData
 */
class AmountDataBuilder
{
    /**
     * @var AmountData
     */
    private $instance;

    private function __construct(AmountData $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Amount Data Builder object.
     *
     * @param float $value
     */
    public static function init(float $value): self
    {
        return new self(new AmountData($value));
    }

    /**
     * Sets Symbol field.
     *
     * @param string|null $value
     */
    public function symbol(?string $value): self
    {
        $this->instance->setSymbol($value);
        return $this;
    }

    /**
     * Initializes a new Amount Data object.
     */
    public function build(): AmountData
    {
        return CoreHelper::clone($this->instance);
    }
}
