<?php

declare(strict_types=1);

/*
 * SplititWebApiV4Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SplititWebApiV4Lib\Models\Builders;

use Core\Utils\CoreHelper;
use SplititWebApiV4Lib\Models\ApiErrorModel;

/**
 * Builder for model ApiErrorModel
 *
 * @see ApiErrorModel
 */
class ApiErrorModelBuilder
{
    /**
     * @var ApiErrorModel
     */
    private $instance;

    private function __construct(ApiErrorModel $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Api Error Model Builder object.
     */
    public static function init(): self
    {
        return new self(new ApiErrorModel());
    }

    /**
     * Sets Code field.
     *
     * @param string|null $value
     */
    public function code(?string $value): self
    {
        $this->instance->setCode($value);
        return $this;
    }

    /**
     * Sets Message field.
     *
     * @param string|null $value
     */
    public function message(?string $value): self
    {
        $this->instance->setMessage($value);
        return $this;
    }

    /**
     * Sets Additional Info field.
     *
     * @param string|null $value
     */
    public function additionalInfo(?string $value): self
    {
        $this->instance->setAdditionalInfo($value);
        return $this;
    }

    /**
     * Sets Extra Data field.
     *
     * @param array<string,string>|null $value
     */
    public function extraData(?array $value): self
    {
        $this->instance->setExtraData($value);
        return $this;
    }

    /**
     * Initializes a new Api Error Model object.
     */
    public function build(): ApiErrorModel
    {
        return CoreHelper::clone($this->instance);
    }
}
