<?php

declare(strict_types=1);

/*
 * SplititWebApiV4Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SplititWebApiV4Lib\Models\Builders;

use Core\Utils\CoreHelper;
use SplititWebApiV4Lib\Models\AprData;

/**
 * Builder for model AprData
 *
 * @see AprData
 */
class AprDataBuilder
{
    /**
     * @var AprData
     */
    private $instance;

    private function __construct(AprData $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Apr Data Builder object.
     *
     * @param float $value
     */
    public static function init(float $value): self
    {
        return new self(new AprData($value));
    }

    /**
     * Sets Symbol field.
     *
     * @param string|null $value
     */
    public function symbol(?string $value): self
    {
        $this->instance->setSymbol($value);
        return $this;
    }

    /**
     * Initializes a new Apr Data object.
     */
    public function build(): AprData
    {
        return CoreHelper::clone($this->instance);
    }
}
