<?php

declare(strict_types=1);

/*
 * SplititWebApiV4Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SplititWebApiV4Lib\Models\Builders;

use Core\Utils\CoreHelper;
use SplititWebApiV4Lib\Models\AuthorizeAuthorizationData;
use SplititWebApiV4Lib\Models\ThreeDSRedirectData;

/**
 * Builder for model AuthorizeAuthorizationData
 *
 * @see AuthorizeAuthorizationData
 */
class AuthorizeAuthorizationDataBuilder
{
    /**
     * @var AuthorizeAuthorizationData
     */
    private $instance;

    private function __construct(AuthorizeAuthorizationData $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Authorize Authorization Data Builder object.
     *
     * @param string $status
     */
    public static function init(string $status): self
    {
        return new self(new AuthorizeAuthorizationData($status));
    }

    /**
     * Sets Splitit Error Result Code field.
     *
     * @param string|null $value
     */
    public function splititErrorResultCode(?string $value): self
    {
        $this->instance->setSplititErrorResultCode($value);
        return $this;
    }

    /**
     * Sets Gateway Transaction ID field.
     *
     * @param string|null $value
     */
    public function gatewayTransactionID(?string $value): self
    {
        $this->instance->setGatewayTransactionID($value);
        return $this;
    }

    /**
     * Sets Gateway Result Code field.
     *
     * @param string|null $value
     */
    public function gatewayResultCode(?string $value): self
    {
        $this->instance->setGatewayResultCode($value);
        return $this;
    }

    /**
     * Sets Gateway Result Message field.
     *
     * @param string|null $value
     */
    public function gatewayResultMessage(?string $value): self
    {
        $this->instance->setGatewayResultMessage($value);
        return $this;
    }

    /**
     * Sets Three DS Redirect field.
     *
     * @param ThreeDSRedirectData|null $value
     */
    public function threeDSRedirect(?ThreeDSRedirectData $value): self
    {
        $this->instance->setThreeDSRedirect($value);
        return $this;
    }

    /**
     * Sets CAVV field.
     *
     * @param string|null $value
     */
    public function cAVV(?string $value): self
    {
        $this->instance->setCAVV($value);
        return $this;
    }

    /**
     * Sets ECI field.
     *
     * @param string|null $value
     */
    public function eCI(?string $value): self
    {
        $this->instance->setECI($value);
        return $this;
    }

    /**
     * Sets Gateway Source Response field.
     *
     * @param string|null $value
     */
    public function gatewaySourceResponse(?string $value): self
    {
        $this->instance->setGatewaySourceResponse($value);
        return $this;
    }

    /**
     * Initializes a new Authorize Authorization Data object.
     */
    public function build(): AuthorizeAuthorizationData
    {
        return CoreHelper::clone($this->instance);
    }
}
