<?php

declare(strict_types=1);

/*
 * SplititWebApiV4Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SplititWebApiV4Lib\Models\Builders;

use Core\Utils\CoreHelper;
use SplititWebApiV4Lib\Models\AuthorizeRequest;
use SplititWebApiV4Lib\Models\ProcessingData;
use SplititWebApiV4Lib\Models\ThreeDSRequestData;

/**
 * Builder for model AuthorizeRequest
 *
 * @see AuthorizeRequest
 */
class AuthorizeRequestBuilder
{
    /**
     * @var AuthorizeRequest
     */
    private $instance;

    private function __construct(AuthorizeRequest $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Authorize Request Builder object.
     *
     * @param string $offerId
     * @param bool $autoCapture
     * @param bool $shopperAcceptedTerms
     */
    public static function init(string $offerId, bool $autoCapture, bool $shopperAcceptedTerms): self
    {
        return new self(new AuthorizeRequest($offerId, $autoCapture, $shopperAcceptedTerms));
    }

    /**
     * Sets Merchant Order Reference field.
     *
     * @param string|null $value
     */
    public function merchantOrderReference(?string $value): self
    {
        $this->instance->setMerchantOrderReference($value);
        return $this;
    }

    /**
     * Sets Three DS field.
     *
     * @param ThreeDSRequestData|null $value
     */
    public function threeDS(?ThreeDSRequestData $value): self
    {
        $this->instance->setThreeDS($value);
        return $this;
    }

    /**
     * Sets Processing Data field.
     *
     * @param ProcessingData|null $value
     */
    public function processingData(?ProcessingData $value): self
    {
        $this->instance->setProcessingData($value);
        return $this;
    }

    /**
     * Initializes a new Authorize Request object.
     */
    public function build(): AuthorizeRequest
    {
        return CoreHelper::clone($this->instance);
    }
}
