<?php

declare(strict_types=1);

/*
 * SplititWebApiV4Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SplititWebApiV4Lib\Models\Builders;

use Core\Utils\CoreHelper;
use SplititWebApiV4Lib\Models\AprData;
use SplititWebApiV4Lib\Models\AuthorizeAuthorizationData;
use SplititWebApiV4Lib\Models\AuthorizeResponse;
use SplititWebApiV4Lib\Models\InstallmentItem;
use SplititWebApiV4Lib\Models\MetadataItem;
use SplititWebApiV4Lib\Models\PaymentMethodData;

/**
 * Builder for model AuthorizeResponse
 *
 * @see AuthorizeResponse
 */
class AuthorizeResponseBuilder
{
    /**
     * @var AuthorizeResponse
     */
    private $instance;

    private function __construct(AuthorizeResponse $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Authorize Response Builder object.
     *
     * @param \DateTime $dateCreated
     * @param string $planStatus
     * @param string $purchaseMethod
     * @param float $purchaseAmount
     * @param float $totalFees
     * @param float $totalAmount
     */
    public static function init(
        \DateTime $dateCreated,
        string $planStatus,
        string $purchaseMethod,
        float $purchaseAmount,
        float $totalFees,
        float $totalAmount
    ): self {
        return new self(new AuthorizeResponse(
            $dateCreated,
            $planStatus,
            $purchaseMethod,
            $purchaseAmount,
            $totalFees,
            $totalAmount
        ));
    }

    /**
     * Sets Installment Plan Number field.
     *
     * @param string|null $value
     */
    public function installmentPlanNumber(?string $value): self
    {
        $this->instance->setInstallmentPlanNumber($value);
        return $this;
    }

    /**
     * Sets Merchant Order Reference field.
     *
     * @param string|null $value
     */
    public function merchantOrderReference(?string $value): self
    {
        $this->instance->setMerchantOrderReference($value);
        return $this;
    }

    /**
     * Sets Currency field.
     *
     * @param string|null $value
     */
    public function currency(?string $value): self
    {
        $this->instance->setCurrency($value);
        return $this;
    }

    /**
     * Sets Apr field.
     *
     * @param AprData|null $value
     */
    public function apr(?AprData $value): self
    {
        $this->instance->setApr($value);
        return $this;
    }

    /**
     * Sets Authorization field.
     *
     * @param AuthorizeAuthorizationData|null $value
     */
    public function authorization(?AuthorizeAuthorizationData $value): self
    {
        $this->instance->setAuthorization($value);
        return $this;
    }

    /**
     * Sets Payment Method field.
     *
     * @param PaymentMethodData|null $value
     */
    public function paymentMethod(?PaymentMethodData $value): self
    {
        $this->instance->setPaymentMethod($value);
        return $this;
    }

    /**
     * Sets Installments field.
     *
     * @param InstallmentItem[]|null $value
     */
    public function installments(?array $value): self
    {
        $this->instance->setInstallments($value);
        return $this;
    }

    /**
     * Sets Metadata field.
     *
     * @param MetadataItem[]|null $value
     */
    public function metadata(?array $value): self
    {
        $this->instance->setMetadata($value);
        return $this;
    }

    /**
     * Initializes a new Authorize Response object.
     */
    public function build(): AuthorizeResponse
    {
        return CoreHelper::clone($this->instance);
    }
}
