<?php

declare(strict_types=1);

/*
 * SplititWebApiV4Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SplititWebApiV4Lib\Models\Builders;

use Core\Utils\CoreHelper;
use SplititWebApiV4Lib\Models\BillingAddressData;

/**
 * Builder for model BillingAddressData
 *
 * @see BillingAddressData
 */
class BillingAddressDataBuilder
{
    /**
     * @var BillingAddressData
     */
    private $instance;

    private function __construct(BillingAddressData $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Billing Address Data Builder object.
     */
    public static function init(): self
    {
        return new self(new BillingAddressData());
    }

    /**
     * Sets Line 1 field.
     *
     * @param string|null $value
     */
    public function line1(?string $value): self
    {
        $this->instance->setLine1($value);
        return $this;
    }

    /**
     * Sets Line 2 field.
     *
     * @param string|null $value
     */
    public function line2(?string $value): self
    {
        $this->instance->setLine2($value);
        return $this;
    }

    /**
     * Sets City field.
     *
     * @param string|null $value
     */
    public function city(?string $value): self
    {
        $this->instance->setCity($value);
        return $this;
    }

    /**
     * Sets State field.
     *
     * @param string|null $value
     */
    public function state(?string $value): self
    {
        $this->instance->setState($value);
        return $this;
    }

    /**
     * Sets Postal Code field.
     *
     * @param string|null $value
     */
    public function postalCode(?string $value): self
    {
        $this->instance->setPostalCode($value);
        return $this;
    }

    /**
     * Sets Country field.
     *
     * @param string|null $value
     */
    public function country(?string $value): self
    {
        $this->instance->setCountry($value);
        return $this;
    }

    /**
     * Initializes a new Billing Address Data object.
     */
    public function build(): BillingAddressData
    {
        return CoreHelper::clone($this->instance);
    }
}
