<?php

declare(strict_types=1);

/*
 * SplititWebApiV4Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SplititWebApiV4Lib\Models\Builders;

use Core\Utils\CoreHelper;
use SplititWebApiV4Lib\Models\CardValidityRequest;
use SplititWebApiV4Lib\Models\PaymentMethod;

/**
 * Builder for model CardValidityRequest
 *
 * @see CardValidityRequest
 */
class CardValidityRequestBuilder
{
    /**
     * @var CardValidityRequest
     */
    private $instance;

    private function __construct(CardValidityRequest $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Card Validity Request Builder object.
     */
    public static function init(): self
    {
        return new self(new CardValidityRequest());
    }

    /**
     * Sets Payment Method field.
     *
     * @param PaymentMethod|null $value
     */
    public function paymentMethod(?PaymentMethod $value): self
    {
        $this->instance->setPaymentMethod($value);
        return $this;
    }

    /**
     * Initializes a new Card Validity Request object.
     */
    public function build(): CardValidityRequest
    {
        return CoreHelper::clone($this->instance);
    }
}
