<?php

declare(strict_types=1);

/*
 * SplititWebApiV4Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SplititWebApiV4Lib\Models\Builders;

use Core\Utils\CoreHelper;
use SplititWebApiV4Lib\Models\CardDetails;

/**
 * Builder for model CardDetails
 *
 * @see CardDetails
 */
class CardDetailsBuilder
{
    /**
     * @var CardDetails
     */
    private $instance;

    private function __construct(CardDetails $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Card Details Builder object.
     *
     * @param string $cardNumber
     * @param string $expYear
     * @param string $expMonth
     */
    public static function init(string $cardNumber, string $expYear, string $expMonth): self
    {
        return new self(new CardDetails($cardNumber, $expYear, $expMonth));
    }

    /**
     * Sets First Name field.
     *
     * @param string|null $value
     */
    public function firstName(?string $value): self
    {
        $this->instance->setFirstName($value);
        return $this;
    }

    /**
     * Sets Last Name field.
     *
     * @param string|null $value
     */
    public function lastName(?string $value): self
    {
        $this->instance->setLastName($value);
        return $this;
    }

    /**
     * Sets Cvv field.
     *
     * @param string|null $value
     */
    public function cvv(?string $value): self
    {
        $this->instance->setCvv($value);
        return $this;
    }

    /**
     * Initializes a new Card Details object.
     */
    public function build(): CardDetails
    {
        return CoreHelper::clone($this->instance);
    }
}
