<?php

declare(strict_types=1);

/*
 * SplititWebApiV4Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SplititWebApiV4Lib\Models\Builders;

use Core\Utils\CoreHelper;
use SplititWebApiV4Lib\Models\CardValidityResponse;
use SplititWebApiV4Lib\Models\ValidationError;

/**
 * Builder for model CardValidityResponse
 *
 * @see CardValidityResponse
 */
class CardValidityResponseBuilder
{
    /**
     * @var CardValidityResponse
     */
    private $instance;

    private function __construct(CardValidityResponse $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Card Validity Response Builder object.
     *
     * @param bool $result
     */
    public static function init(bool $result): self
    {
        return new self(new CardValidityResponse($result));
    }

    /**
     * Sets Validation Errors field.
     *
     * @param ValidationError[]|null $value
     */
    public function validationErrors(?array $value): self
    {
        $this->instance->setValidationErrors($value);
        return $this;
    }

    /**
     * Initializes a new Card Validity Response object.
     */
    public function build(): CardValidityResponse
    {
        return CoreHelper::clone($this->instance);
    }
}
