<?php

declare(strict_types=1);

/*
 * SplititWebApiV4Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SplititWebApiV4Lib\Models\Builders;

use Core\Utils\CoreHelper;
use SplititWebApiV4Lib\Models\CheckoutUrlData;

/**
 * Builder for model CheckoutUrlData
 *
 * @see CheckoutUrlData
 */
class CheckoutUrlDataBuilder
{
    /**
     * @var CheckoutUrlData
     */
    private $instance;

    private function __construct(CheckoutUrlData $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Checkout Url Data Builder object.
     */
    public static function init(): self
    {
        return new self(new CheckoutUrlData());
    }

    /**
     * Sets Url field.
     *
     * @param string|null $value
     */
    public function url(?string $value): self
    {
        $this->instance->setUrl($value);
        return $this;
    }

    /**
     * Sets Valid Until field.
     *
     * @param \DateTime|null $value
     */
    public function validUntil(?\DateTime $value): self
    {
        $this->instance->setValidUntil($value);
        return $this;
    }

    /**
     * Initializes a new Checkout Url Data object.
     */
    public function build(): CheckoutUrlData
    {
        return CoreHelper::clone($this->instance);
    }
}
