<?php

declare(strict_types=1);

/*
 * SplititWebApiV4Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SplititWebApiV4Lib\Models\Builders;

use Core\Utils\CoreHelper;
use SplititWebApiV4Lib\Models\ContentSegment;

/**
 * Builder for model ContentSegment
 *
 * @see ContentSegment
 */
class ContentSegmentBuilder
{
    /**
     * @var ContentSegment
     */
    private $instance;

    private function __construct(ContentSegment $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Content Segment Builder object.
     */
    public static function init(): self
    {
        return new self(new ContentSegment());
    }

    /**
     * Sets Type field.
     *
     * @param string|null $value
     */
    public function type(?string $value): self
    {
        $this->instance->setType($value);
        return $this;
    }

    /**
     * Sets Value field.
     *
     * @param string|null $value
     */
    public function value(?string $value): self
    {
        $this->instance->setValue($value);
        return $this;
    }

    /**
     * Sets Label field.
     *
     * @param string|null $value
     */
    public function label(?string $value): self
    {
        $this->instance->setLabel($value);
        return $this;
    }

    /**
     * Sets Url field.
     *
     * @param string|null $value
     */
    public function url(?string $value): self
    {
        $this->instance->setUrl($value);
        return $this;
    }

    /**
     * Initializes a new Content Segment object.
     */
    public function build(): ContentSegment
    {
        return CoreHelper::clone($this->instance);
    }
}
