<?php

declare(strict_types=1);

/*
 * SplititWebApiV4Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SplititWebApiV4Lib\Models\Builders;

use Core\Utils\CoreHelper;
use SplititWebApiV4Lib\Models\ContentSegment;
use SplititWebApiV4Lib\Models\InlineContent;

/**
 * Builder for model InlineContent
 *
 * @see InlineContent
 */
class InlineContentBuilder
{
    /**
     * @var InlineContent
     */
    private $instance;

    private function __construct(InlineContent $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Inline Content Builder object.
     */
    public static function init(): self
    {
        return new self(new InlineContent());
    }

    /**
     * Sets Segments field.
     *
     * @param ContentSegment[]|null $value
     */
    public function segments(?array $value): self
    {
        $this->instance->setSegments($value);
        return $this;
    }

    /**
     * Initializes a new Inline Content object.
     */
    public function build(): InlineContent
    {
        return CoreHelper::clone($this->instance);
    }
}
