<?php

declare(strict_types=1);

/*
 * SplititWebApiV4Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SplititWebApiV4Lib\Models\Builders;

use Core\Utils\CoreHelper;
use SplititWebApiV4Lib\Models\InstallmentPlanSearchRequest;

/**
 * Builder for model InstallmentPlanSearchRequest
 *
 * @see InstallmentPlanSearchRequest
 */
class InstallmentPlanSearchRequestBuilder
{
    /**
     * @var InstallmentPlanSearchRequest
     */
    private $instance;

    private function __construct(InstallmentPlanSearchRequest $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Installment Plan Search Request Builder object.
     */
    public static function init(): self
    {
        return new self(new InstallmentPlanSearchRequest());
    }

    /**
     * Sets Installment Plan Numbers field.
     *
     * @param string[]|null $value
     */
    public function installmentPlanNumbers(?array $value): self
    {
        $this->instance->setInstallmentPlanNumbers($value);
        return $this;
    }

    /**
     * Sets Merchant Order Reference Ids field.
     *
     * @param string[]|null $value
     */
    public function merchantOrderReferenceIds(?array $value): self
    {
        $this->instance->setMerchantOrderReferenceIds($value);
        return $this;
    }

    /**
     * Initializes a new Installment Plan Search Request object.
     */
    public function build(): InstallmentPlanSearchRequest
    {
        return CoreHelper::clone($this->instance);
    }
}
