<?php

declare(strict_types=1);

/*
 * SplititWebApiV4Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SplititWebApiV4Lib\Models\Builders;

use Core\Utils\CoreHelper;
use SplititWebApiV4Lib\Models\AmountData;
use SplititWebApiV4Lib\Models\InstallmentItem;

/**
 * Builder for model InstallmentItem
 *
 * @see InstallmentItem
 */
class InstallmentItemBuilder
{
    /**
     * @var InstallmentItem
     */
    private $instance;

    private function __construct(InstallmentItem $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Installment Item Builder object.
     *
     * @param int $installmentNumber
     * @param string $status
     */
    public static function init(int $installmentNumber, string $status): self
    {
        return new self(new InstallmentItem($installmentNumber, $status));
    }

    /**
     * Sets Amount field.
     *
     * @param AmountData|null $value
     */
    public function amount(?AmountData $value): self
    {
        $this->instance->setAmount($value);
        return $this;
    }

    /**
     * Sets Process Date Time field.
     *
     * @param \DateTime|null $value
     */
    public function processDateTime(?\DateTime $value): self
    {
        $this->instance->setProcessDateTime($value);
        return $this;
    }

    /**
     * Initializes a new Installment Item object.
     */
    public function build(): InstallmentItem
    {
        return CoreHelper::clone($this->instance);
    }
}
