<?php

declare(strict_types=1);

/*
 * SplititWebApiV4Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SplititWebApiV4Lib\Models\Builders;

use Core\Utils\CoreHelper;
use SplititWebApiV4Lib\Models\InstallmentPlanDetailsResponse;
use SplititWebApiV4Lib\Models\InstallmentPlanSearchDetailsResponse;

/**
 * Builder for model InstallmentPlanSearchDetailsResponse
 *
 * @see InstallmentPlanSearchDetailsResponse
 */
class InstallmentPlanSearchDetailsResponseBuilder
{
    /**
     * @var InstallmentPlanSearchDetailsResponse
     */
    private $instance;

    private function __construct(InstallmentPlanSearchDetailsResponse $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Installment Plan Search Details Response Builder object.
     */
    public static function init(): self
    {
        return new self(new InstallmentPlanSearchDetailsResponse());
    }

    /**
     * Sets Plan List field.
     *
     * @param InstallmentPlanDetailsResponse[]|null $value
     */
    public function planList(?array $value): self
    {
        $this->instance->setPlanList($value);
        return $this;
    }

    /**
     * Initializes a new Installment Plan Search Details Response object.
     */
    public function build(): InstallmentPlanSearchDetailsResponse
    {
        return CoreHelper::clone($this->instance);
    }
}
