<?php

declare(strict_types=1);

/*
 * SplititWebApiV4Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SplititWebApiV4Lib\Models\Builders;

use Core\Utils\CoreHelper;
use SplititWebApiV4Lib\Models\AprData;
use SplititWebApiV4Lib\Models\InstallmentItem;
use SplititWebApiV4Lib\Models\InstallmentPlanDetailsResponse;
use SplititWebApiV4Lib\Models\MetadataItem;
use SplititWebApiV4Lib\Models\PaymentMethodData;
use SplititWebApiV4Lib\Models\PlanAuthorizationData;
use SplititWebApiV4Lib\Models\PlanLinksData;
use SplititWebApiV4Lib\Models\RefundItem;
use SplititWebApiV4Lib\Models\ShopperDetailsData;

/**
 * Builder for model InstallmentPlanDetailsResponse
 *
 * @see InstallmentPlanDetailsResponse
 */
class InstallmentPlanDetailsResponseBuilder
{
    /**
     * @var InstallmentPlanDetailsResponse
     */
    private $instance;

    private function __construct(InstallmentPlanDetailsResponse $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Installment Plan Details Response Builder object.
     *
     * @param \DateTime $dateCreated
     * @param string $status
     * @param string $installmentProvider
     * @param string $purchaseMethod
     * @param float $purchaseAmount
     * @param float $totalAmount
     * @param float $totalFees
     */
    public static function init(
        \DateTime $dateCreated,
        string $status,
        string $installmentProvider,
        string $purchaseMethod,
        float $purchaseAmount,
        float $totalAmount,
        float $totalFees
    ): self {
        return new self(new InstallmentPlanDetailsResponse(
            $dateCreated,
            $status,
            $installmentProvider,
            $purchaseMethod,
            $purchaseAmount,
            $totalAmount,
            $totalFees
        ));
    }

    /**
     * Sets Installment Plan Number field.
     *
     * @param string|null $value
     */
    public function installmentPlanNumber(?string $value): self
    {
        $this->instance->setInstallmentPlanNumber($value);
        return $this;
    }

    /**
     * Sets Merchant Order Reference field.
     *
     * @param string|null $value
     */
    public function merchantOrderReference(?string $value): self
    {
        $this->instance->setMerchantOrderReference($value);
        return $this;
    }

    /**
     * Sets Currency field.
     *
     * @param string|null $value
     */
    public function currency(?string $value): self
    {
        $this->instance->setCurrency($value);
        return $this;
    }

    /**
     * Sets Apr field.
     *
     * @param AprData|null $value
     */
    public function apr(?AprData $value): self
    {
        $this->instance->setApr($value);
        return $this;
    }

    /**
     * Sets Authorization field.
     *
     * @param PlanAuthorizationData|null $value
     */
    public function authorization(?PlanAuthorizationData $value): self
    {
        $this->instance->setAuthorization($value);
        return $this;
    }

    /**
     * Sets Shopper Details field.
     *
     * @param ShopperDetailsData|null $value
     */
    public function shopperDetails(?ShopperDetailsData $value): self
    {
        $this->instance->setShopperDetails($value);
        return $this;
    }

    /**
     * Sets Payment Method field.
     *
     * @param PaymentMethodData|null $value
     */
    public function paymentMethod(?PaymentMethodData $value): self
    {
        $this->instance->setPaymentMethod($value);
        return $this;
    }

    /**
     * Sets Installments field.
     *
     * @param InstallmentItem[]|null $value
     */
    public function installments(?array $value): self
    {
        $this->instance->setInstallments($value);
        return $this;
    }

    /**
     * Sets Refunds field.
     *
     * @param RefundItem[]|null $value
     */
    public function refunds(?array $value): self
    {
        $this->instance->setRefunds($value);
        return $this;
    }

    /**
     * Sets Links field.
     *
     * @param PlanLinksData[]|null $value
     */
    public function links(?array $value): self
    {
        $this->instance->setLinks($value);
        return $this;
    }

    /**
     * Sets Metadata field.
     *
     * @param MetadataItem[]|null $value
     */
    public function metadata(?array $value): self
    {
        $this->instance->setMetadata($value);
        return $this;
    }

    /**
     * Initializes a new Installment Plan Details Response object.
     */
    public function build(): InstallmentPlanDetailsResponse
    {
        return CoreHelper::clone($this->instance);
    }
}
