<?php

declare(strict_types=1);

/*
 * SplititWebApiV4Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SplititWebApiV4Lib\Models\Builders;

use Core\Utils\CoreHelper;
use SplititWebApiV4Lib\Models\MaskedCardDetails;

/**
 * Builder for model MaskedCardDetails
 *
 * @see MaskedCardDetails
 */
class MaskedCardDetailsBuilder
{
    /**
     * @var MaskedCardDetails
     */
    private $instance;

    private function __construct(MaskedCardDetails $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Masked Card Details Builder object.
     */
    public static function init(): self
    {
        return new self(new MaskedCardDetails());
    }

    /**
     * Sets Last 4 Digits field.
     *
     * @param string|null $value
     */
    public function last4Digits(?string $value): self
    {
        $this->instance->setLast4Digits($value);
        return $this;
    }

    /**
     * Sets BIN field.
     *
     * @param string|null $value
     */
    public function bIN(?string $value): self
    {
        $this->instance->setBIN($value);
        return $this;
    }

    /**
     * Sets Issuer Name field.
     *
     * @param string|null $value
     */
    public function issuerName(?string $value): self
    {
        $this->instance->setIssuerName($value);
        return $this;
    }

    /**
     * Initializes a new Masked Card Details object.
     */
    public function build(): MaskedCardDetails
    {
        return CoreHelper::clone($this->instance);
    }
}
