<?php

declare(strict_types=1);

/*
 * SplititWebApiV4Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SplititWebApiV4Lib\Models\Builders;

use Core\Utils\CoreHelper;
use SplititWebApiV4Lib\Models\MetadataItem;

/**
 * Builder for model MetadataItem
 *
 * @see MetadataItem
 */
class MetadataItemBuilder
{
    /**
     * @var MetadataItem
     */
    private $instance;

    private function __construct(MetadataItem $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Metadata Item Builder object.
     */
    public static function init(): self
    {
        return new self(new MetadataItem());
    }

    /**
     * Sets Key field.
     *
     * @param string|null $value
     */
    public function key(?string $value): self
    {
        $this->instance->setKey($value);
        return $this;
    }

    /**
     * Sets Value field.
     *
     * @param string|null $value
     */
    public function value(?string $value): self
    {
        $this->instance->setValue($value);
        return $this;
    }

    /**
     * Initializes a new Metadata Item object.
     */
    public function build(): MetadataItem
    {
        return CoreHelper::clone($this->instance);
    }
}
