<?php

declare(strict_types=1);

/*
 * SplititWebApiV4Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SplititWebApiV4Lib\Models\Builders;

use Core\Utils\CoreHelper;
use SplititWebApiV4Lib\Models\OfferItem;
use SplititWebApiV4Lib\Models\OffersPaymentMethodResponse;
use SplititWebApiV4Lib\Models\OffersResponse;

/**
 * Builder for model OffersResponse
 *
 * @see OffersResponse
 */
class OffersResponseBuilder
{
    /**
     * @var OffersResponse
     */
    private $instance;

    private function __construct(OffersResponse $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Offers Response Builder object.
     *
     * @param string $purchaseMethod
     * @param float $purchaseAmount
     */
    public static function init(string $purchaseMethod, float $purchaseAmount): self
    {
        return new self(new OffersResponse($purchaseMethod, $purchaseAmount));
    }

    /**
     * Sets Installment Plan Number field.
     *
     * @param string|null $value
     */
    public function installmentPlanNumber(?string $value): self
    {
        $this->instance->setInstallmentPlanNumber($value);
        return $this;
    }

    /**
     * Sets Merchant Order Reference field.
     *
     * @param string|null $value
     */
    public function merchantOrderReference(?string $value): self
    {
        $this->instance->setMerchantOrderReference($value);
        return $this;
    }

    /**
     * Sets Currency field.
     *
     * @param string|null $value
     */
    public function currency(?string $value): self
    {
        $this->instance->setCurrency($value);
        return $this;
    }

    /**
     * Sets Payment Method field.
     *
     * @param OffersPaymentMethodResponse|null $value
     */
    public function paymentMethod(?OffersPaymentMethodResponse $value): self
    {
        $this->instance->setPaymentMethod($value);
        return $this;
    }

    /**
     * Sets Offers field.
     *
     * @param OfferItem[]|null $value
     */
    public function offers(?array $value): self
    {
        $this->instance->setOffers($value);
        return $this;
    }

    /**
     * Sets Valid Until field.
     *
     * @param \DateTime|null $value
     */
    public function validUntil(?\DateTime $value): self
    {
        $this->instance->setValidUntil($value);
        return $this;
    }

    /**
     * Initializes a new Offers Response object.
     */
    public function build(): OffersResponse
    {
        return CoreHelper::clone($this->instance);
    }
}
