<?php

declare(strict_types=1);

/*
 * SplititWebApiV4Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SplititWebApiV4Lib\Models\Builders;

use Core\Utils\CoreHelper;
use SplititWebApiV4Lib\Models\MetadataItem;
use SplititWebApiV4Lib\Models\OffersMerchantDetails;
use SplititWebApiV4Lib\Models\OffersPaymentMethod;
use SplititWebApiV4Lib\Models\OffersRequest;
use SplititWebApiV4Lib\Models\OffersShopperDetails;

/**
 * Builder for model OffersRequest
 *
 * @see OffersRequest
 */
class OffersRequestBuilder
{
    /**
     * @var OffersRequest
     */
    private $instance;

    private function __construct(OffersRequest $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Offers Request Builder object.
     *
     * @param string $purchaseMethod
     * @param string $purchaseAmount
     * @param string $currency
     * @param OffersShopperDetails $shopperDetails
     * @param OffersPaymentMethod $paymentMethod
     */
    public static function init(
        string $purchaseMethod,
        string $purchaseAmount,
        string $currency,
        OffersShopperDetails $shopperDetails,
        OffersPaymentMethod $paymentMethod
    ): self {
        return new self(
            new OffersRequest($purchaseMethod, $purchaseAmount, $currency, $shopperDetails, $paymentMethod)
        );
    }

    /**
     * Sets Merchant Order Reference field.
     *
     * @param string|null $value
     */
    public function merchantOrderReference(?string $value): self
    {
        $this->instance->setMerchantOrderReference($value);
        return $this;
    }

    /**
     * Sets Merchant Details field.
     *
     * @param OffersMerchantDetails|null $value
     */
    public function merchantDetails(?OffersMerchantDetails $value): self
    {
        $this->instance->setMerchantDetails($value);
        return $this;
    }

    /**
     * Sets Metadata field.
     *
     * @param MetadataItem[]|null $value
     */
    public function metadata(?array $value): self
    {
        $this->instance->setMetadata($value);
        return $this;
    }

    /**
     * Initializes a new Offers Request object.
     */
    public function build(): OffersRequest
    {
        return CoreHelper::clone($this->instance);
    }
}
