<?php

declare(strict_types=1);

/*
 * SplititWebApiV4Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SplititWebApiV4Lib\Models\Builders;

use Core\Utils\CoreHelper;
use SplititWebApiV4Lib\Models\OffersStoreLocation;

/**
 * Builder for model OffersStoreLocation
 *
 * @see OffersStoreLocation
 */
class OffersStoreLocationBuilder
{
    /**
     * @var OffersStoreLocation
     */
    private $instance;

    private function __construct(OffersStoreLocation $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Offers Store Location Builder object.
     *
     * @param string $line1
     * @param string $postalCode
     * @param string $country
     */
    public static function init(string $line1, string $postalCode, string $country): self
    {
        return new self(new OffersStoreLocation($line1, $postalCode, $country));
    }

    /**
     * Sets Line 2 field.
     *
     * @param string|null $value
     */
    public function line2(?string $value): self
    {
        $this->instance->setLine2($value);
        return $this;
    }

    /**
     * Sets City field.
     *
     * @param string|null $value
     */
    public function city(?string $value): self
    {
        $this->instance->setCity($value);
        return $this;
    }

    /**
     * Sets State field.
     *
     * @param string|null $value
     */
    public function state(?string $value): self
    {
        $this->instance->setState($value);
        return $this;
    }

    /**
     * Initializes a new Offers Store Location object.
     */
    public function build(): OffersStoreLocation
    {
        return CoreHelper::clone($this->instance);
    }
}
