<?php

declare(strict_types=1);

/*
 * SplititWebApiV4Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SplititWebApiV4Lib\Models\Builders;

use Core\Utils\CoreHelper;
use SplititWebApiV4Lib\Models\OffersMerchantDetails;
use SplititWebApiV4Lib\Models\OffersStoreLocation;

/**
 * Builder for model OffersMerchantDetails
 *
 * @see OffersMerchantDetails
 */
class OffersMerchantDetailsBuilder
{
    /**
     * @var OffersMerchantDetails
     */
    private $instance;

    private function __construct(OffersMerchantDetails $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Offers Merchant Details Builder object.
     *
     * @param OffersStoreLocation $storeLocation
     */
    public static function init(OffersStoreLocation $storeLocation): self
    {
        return new self(new OffersMerchantDetails($storeLocation));
    }

    /**
     * Sets Store Name field.
     *
     * @param string|null $value
     */
    public function storeName(?string $value): self
    {
        $this->instance->setStoreName($value);
        return $this;
    }

    /**
     * Sets Store Id field.
     *
     * @param string|null $value
     */
    public function storeId(?string $value): self
    {
        $this->instance->setStoreId($value);
        return $this;
    }

    /**
     * Initializes a new Offers Merchant Details object.
     */
    public function build(): OffersMerchantDetails
    {
        return CoreHelper::clone($this->instance);
    }
}
