<?php

declare(strict_types=1);

/*
 * SplititWebApiV4Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SplititWebApiV4Lib\Models\Builders;

use Core\Utils\CoreHelper;
use SplititWebApiV4Lib\Models\OffersBillingAddress;
use SplititWebApiV4Lib\Models\OffersShopperDetails;

/**
 * Builder for model OffersShopperDetails
 *
 * @see OffersShopperDetails
 */
class OffersShopperDetailsBuilder
{
    /**
     * @var OffersShopperDetails
     */
    private $instance;

    private function __construct(OffersShopperDetails $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Offers Shopper Details Builder object.
     *
     * @param string $lastName
     * @param string $email
     */
    public static function init(string $lastName, string $email): self
    {
        return new self(new OffersShopperDetails($lastName, $email));
    }

    /**
     * Sets First Name field.
     *
     * @param string|null $value
     */
    public function firstName(?string $value): self
    {
        $this->instance->setFirstName($value);
        return $this;
    }

    /**
     * Sets Phone Number field.
     *
     * @param string|null $value
     */
    public function phoneNumber(?string $value): self
    {
        $this->instance->setPhoneNumber($value);
        return $this;
    }

    /**
     * Sets Shopper Locale field.
     *
     * @param string|null $value
     */
    public function shopperLocale(?string $value): self
    {
        $this->instance->setShopperLocale($value);
        return $this;
    }

    /**
     * Sets Billing Address field.
     *
     * @param OffersBillingAddress|null $value
     */
    public function billingAddress(?OffersBillingAddress $value): self
    {
        $this->instance->setBillingAddress($value);
        return $this;
    }

    /**
     * Initializes a new Offers Shopper Details object.
     */
    public function build(): OffersShopperDetails
    {
        return CoreHelper::clone($this->instance);
    }
}
