<?php

declare(strict_types=1);

/*
 * SplititWebApiV4Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SplititWebApiV4Lib\Models\Builders;

use Core\Utils\CoreHelper;
use SplititWebApiV4Lib\Models\OffersCardDetails;

/**
 * Builder for model OffersCardDetails
 *
 * @see OffersCardDetails
 */
class OffersCardDetailsBuilder
{
    /**
     * @var OffersCardDetails
     */
    private $instance;

    private function __construct(OffersCardDetails $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Offers Card Details Builder object.
     *
     * @param string $cardNumber
     * @param int $expMonth
     * @param int $expYear
     */
    public static function init(string $cardNumber, int $expMonth, int $expYear): self
    {
        return new self(new OffersCardDetails($cardNumber, $expMonth, $expYear));
    }

    /**
     * Sets First Name field.
     *
     * @param string|null $value
     */
    public function firstName(?string $value): self
    {
        $this->instance->setFirstName($value);
        return $this;
    }

    /**
     * Sets Last Name field.
     *
     * @param string|null $value
     */
    public function lastName(?string $value): self
    {
        $this->instance->setLastName($value);
        return $this;
    }

    /**
     * Sets Cvv field.
     *
     * @param string|null $value
     */
    public function cvv(?string $value): self
    {
        $this->instance->setCvv($value);
        return $this;
    }

    /**
     * Initializes a new Offers Card Details object.
     */
    public function build(): OffersCardDetails
    {
        return CoreHelper::clone($this->instance);
    }
}
