<?php

declare(strict_types=1);

/*
 * SplititWebApiV4Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SplititWebApiV4Lib\Models\Builders;

use Core\Utils\CoreHelper;
use SplititWebApiV4Lib\Models\AmountData;
use SplititWebApiV4Lib\Models\AprData;
use SplititWebApiV4Lib\Models\InlineContent;
use SplititWebApiV4Lib\Models\OfferItem;

/**
 * Builder for model OfferItem
 *
 * @see OfferItem
 */
class OfferItemBuilder
{
    /**
     * @var OfferItem
     */
    private $instance;

    private function __construct(OfferItem $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Offer Item Builder object.
     *
     * @param float $totalAmount
     * @param float $totalFees
     * @param int $numberOfInstallments
     * @param float $installmentAmount
     * @param float $firstInstallmentAmount
     */
    public static function init(
        float $totalAmount,
        float $totalFees,
        int $numberOfInstallments,
        float $installmentAmount,
        float $firstInstallmentAmount
    ): self {
        return new self(
            new OfferItem(
                $totalAmount,
                $totalFees,
                $numberOfInstallments,
                $installmentAmount,
                $firstInstallmentAmount
            )
        );
    }

    /**
     * Sets Offer Id field.
     *
     * @param string|null $value
     */
    public function offerId(?string $value): self
    {
        $this->instance->setOfferId($value);
        return $this;
    }

    /**
     * Sets Apr field.
     *
     * @param AprData|null $value
     */
    public function apr(?AprData $value): self
    {
        $this->instance->setApr($value);
        return $this;
    }

    /**
     * Sets Currency field.
     *
     * @param string|null $value
     */
    public function currency(?string $value): self
    {
        $this->instance->setCurrency($value);
        return $this;
    }

    /**
     * Sets Frequency field.
     *
     * @param string|null $value
     */
    public function frequency(?string $value): self
    {
        $this->instance->setFrequency($value);
        return $this;
    }

    /**
     * Sets Last Installment Amount field.
     *
     * @param AmountData|null $value
     */
    public function lastInstallmentAmount(?AmountData $value): self
    {
        $this->instance->setLastInstallmentAmount($value);
        return $this;
    }

    /**
     * Sets Inline Content field.
     *
     * @param InlineContent|null $value
     */
    public function inlineContent(?InlineContent $value): self
    {
        $this->instance->setInlineContent($value);
        return $this;
    }

    /**
     * Initializes a new Offer Item object.
     */
    public function build(): OfferItem
    {
        return CoreHelper::clone($this->instance);
    }
}
