<?php

declare(strict_types=1);

/*
 * SplititWebApiV4Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SplititWebApiV4Lib\Models\Builders;

use Core\Utils\CoreHelper;
use SplititWebApiV4Lib\Models\OffersCardDetails;
use SplititWebApiV4Lib\Models\OffersPaymentMethod;

/**
 * Builder for model OffersPaymentMethod
 *
 * @see OffersPaymentMethod
 */
class OffersPaymentMethodBuilder
{
    /**
     * @var OffersPaymentMethod
     */
    private $instance;

    private function __construct(OffersPaymentMethod $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Offers Payment Method Builder object.
     *
     * @param OffersCardDetails $cardDetails
     */
    public static function init(OffersCardDetails $cardDetails): self
    {
        return new self(new OffersPaymentMethod($cardDetails));
    }

    /**
     * Initializes a new Offers Payment Method object.
     */
    public function build(): OffersPaymentMethod
    {
        return CoreHelper::clone($this->instance);
    }
}
