<?php

declare(strict_types=1);

/*
 * SplititWebApiV4Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SplititWebApiV4Lib\Models\Builders;

use Core\Utils\CoreHelper;
use SplititWebApiV4Lib\Models\CheckoutUrlData;
use SplititWebApiV4Lib\Models\PaymentLinkResponse;

/**
 * Builder for model PaymentLinkResponse
 *
 * @see PaymentLinkResponse
 */
class PaymentLinkResponseBuilder
{
    /**
     * @var PaymentLinkResponse
     */
    private $instance;

    private function __construct(PaymentLinkResponse $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Payment Link Response Builder object.
     *
     * @param float $purchaseAmount
     */
    public static function init(float $purchaseAmount): self
    {
        return new self(new PaymentLinkResponse($purchaseAmount));
    }

    /**
     * Sets Checkout Url field.
     *
     * @param CheckoutUrlData|null $value
     */
    public function checkoutUrl(?CheckoutUrlData $value): self
    {
        $this->instance->setCheckoutUrl($value);
        return $this;
    }

    /**
     * Sets Installment Plan Number field.
     *
     * @param string|null $value
     */
    public function installmentPlanNumber(?string $value): self
    {
        $this->instance->setInstallmentPlanNumber($value);
        return $this;
    }

    /**
     * Sets Merchant Order Reference field.
     *
     * @param string|null $value
     */
    public function merchantOrderReference(?string $value): self
    {
        $this->instance->setMerchantOrderReference($value);
        return $this;
    }

    /**
     * Sets Currency field.
     *
     * @param string|null $value
     */
    public function currency(?string $value): self
    {
        $this->instance->setCurrency($value);
        return $this;
    }

    /**
     * Initializes a new Payment Link Response object.
     */
    public function build(): PaymentLinkResponse
    {
        return CoreHelper::clone($this->instance);
    }
}
