<?php

declare(strict_types=1);

/*
 * SplititWebApiV4Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SplititWebApiV4Lib\Models\Builders;

use Core\Utils\CoreHelper;
use SplititWebApiV4Lib\Models\MaskedCardDetails;
use SplititWebApiV4Lib\Models\PaymentMethodData;

/**
 * Builder for model PaymentMethodData
 *
 * @see PaymentMethodData
 */
class PaymentMethodDataBuilder
{
    /**
     * @var PaymentMethodData
     */
    private $instance;

    private function __construct(PaymentMethodData $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Payment Method Data Builder object.
     */
    public static function init(): self
    {
        return new self(new PaymentMethodData());
    }

    /**
     * Sets Card Details field.
     *
     * @param MaskedCardDetails|null $value
     */
    public function cardDetails(?MaskedCardDetails $value): self
    {
        $this->instance->setCardDetails($value);
        return $this;
    }

    /**
     * Sets Par field.
     *
     * @param string|null $value
     */
    public function par(?string $value): self
    {
        $this->instance->setPar($value);
        return $this;
    }

    /**
     * Initializes a new Payment Method Data object.
     */
    public function build(): PaymentMethodData
    {
        return CoreHelper::clone($this->instance);
    }
}
