<?php

declare(strict_types=1);

/*
 * SplititWebApiV4Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SplititWebApiV4Lib\Models\Builders;

use Core\Utils\CoreHelper;
use SplititWebApiV4Lib\Models\PaymentMethod;

/**
 * Builder for model PaymentMethod
 *
 * @see PaymentMethod
 */
class PaymentMethodBuilder
{
    /**
     * @var PaymentMethod
     */
    private $instance;

    private function __construct(PaymentMethod $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Payment Method Builder object.
     *
     * @param string $value
     */
    public static function init(string $value): self
    {
        return new self(new PaymentMethod($value));
    }

    /**
     * Initializes a new Payment Method object.
     */
    public function build(): PaymentMethod
    {
        return CoreHelper::clone($this->instance);
    }
}
