<?php

declare(strict_types=1);

/*
 * SplititWebApiV4Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SplititWebApiV4Lib\Models\Builders;

use Core\Utils\CoreHelper;
use SplititWebApiV4Lib\Models\MetadataItem;
use SplititWebApiV4Lib\Models\OffersMerchantDetails;
use SplititWebApiV4Lib\Models\OffersShopperDetails;
use SplititWebApiV4Lib\Models\PaymentLinkRequest;
use SplititWebApiV4Lib\Models\ProcessingData;
use SplititWebApiV4Lib\Models\RedirectUrls;
use SplititWebApiV4Lib\Models\ThreeDSExecute;

/**
 * Builder for model PaymentLinkRequest
 *
 * @see PaymentLinkRequest
 */
class PaymentLinkRequestBuilder
{
    /**
     * @var PaymentLinkRequest
     */
    private $instance;

    private function __construct(PaymentLinkRequest $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Payment Link Request Builder object.
     *
     * @param string $amount
     * @param string $currency
     * @param string $purchaseMethod
     * @param OffersShopperDetails $shopperDetails
     */
    public static function init(
        string $amount,
        string $currency,
        string $purchaseMethod,
        OffersShopperDetails $shopperDetails
    ): self {
        return new self(new PaymentLinkRequest($amount, $currency, $purchaseMethod, $shopperDetails));
    }

    /**
     * Sets Auto Capture field.
     *
     * @param bool|null $value
     */
    public function autoCapture(?bool $value): self
    {
        $this->instance->setAutoCapture($value);
        return $this;
    }

    /**
     * Sets Merchant Order Reference field.
     *
     * @param string|null $value
     */
    public function merchantOrderReference(?string $value): self
    {
        $this->instance->setMerchantOrderReference($value);
        return $this;
    }

    /**
     * Sets Merchant Details field.
     *
     * @param OffersMerchantDetails|null $value
     */
    public function merchantDetails(?OffersMerchantDetails $value): self
    {
        $this->instance->setMerchantDetails($value);
        return $this;
    }

    /**
     * Sets Checkout Url Validity field.
     *
     * @param \DateTime|null $value
     */
    public function checkoutUrlValidity(?\DateTime $value): self
    {
        $this->instance->setCheckoutUrlValidity($value);
        return $this;
    }

    /**
     * Sets Metadata field.
     *
     * @param MetadataItem[]|null $value
     */
    public function metadata(?array $value): self
    {
        $this->instance->setMetadata($value);
        return $this;
    }

    /**
     * Sets Redirect Urls field.
     *
     * @param RedirectUrls|null $value
     */
    public function redirectUrls(?RedirectUrls $value): self
    {
        $this->instance->setRedirectUrls($value);
        return $this;
    }

    /**
     * Sets Processing Data field.
     *
     * @param ProcessingData|null $value
     */
    public function processingData(?ProcessingData $value): self
    {
        $this->instance->setProcessingData($value);
        return $this;
    }

    /**
     * Sets Three DS field.
     *
     * @param ThreeDSExecute|null $value
     */
    public function threeDS(?ThreeDSExecute $value): self
    {
        $this->instance->setThreeDS($value);
        return $this;
    }

    /**
     * Initializes a new Payment Link Request object.
     */
    public function build(): PaymentLinkRequest
    {
        return CoreHelper::clone($this->instance);
    }
}
