<?php

declare(strict_types=1);

/*
 * SplititWebApiV4Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SplititWebApiV4Lib\Models\Builders;

use Core\Utils\CoreHelper;
use SplititWebApiV4Lib\Models\PlanLinksData;

/**
 * Builder for model PlanLinksData
 *
 * @see PlanLinksData
 */
class PlanLinksDataBuilder
{
    /**
     * @var PlanLinksData
     */
    private $instance;

    private function __construct(PlanLinksData $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Plan Links Data Builder object.
     */
    public static function init(): self
    {
        return new self(new PlanLinksData());
    }

    /**
     * Sets Key field.
     *
     * @param string|null $value
     */
    public function key(?string $value): self
    {
        $this->instance->setKey($value);
        return $this;
    }

    /**
     * Sets Label field.
     *
     * @param string|null $value
     */
    public function label(?string $value): self
    {
        $this->instance->setLabel($value);
        return $this;
    }

    /**
     * Sets Value field.
     *
     * @param string|null $value
     */
    public function value(?string $value): self
    {
        $this->instance->setValue($value);
        return $this;
    }

    /**
     * Sets Description field.
     *
     * @param string|null $value
     */
    public function description(?string $value): self
    {
        $this->instance->setDescription($value);
        return $this;
    }

    /**
     * Initializes a new Plan Links Data object.
     */
    public function build(): PlanLinksData
    {
        return CoreHelper::clone($this->instance);
    }
}
