<?php

declare(strict_types=1);

/*
 * SplititWebApiV4Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SplititWebApiV4Lib\Models\Builders;

use Core\Utils\CoreHelper;
use SplititWebApiV4Lib\Models\ProcessingData;

/**
 * Builder for model ProcessingData
 *
 * @see ProcessingData
 */
class ProcessingDataBuilder
{
    /**
     * @var ProcessingData
     */
    private $instance;

    private function __construct(ProcessingData $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Processing Data Builder object.
     */
    public static function init(): self
    {
        return new self(new ProcessingData());
    }

    /**
     * Sets Soft Descriptor field.
     *
     * @param string|null $value
     */
    public function softDescriptor(?string $value): self
    {
        $this->instance->setSoftDescriptor($value);
        return $this;
    }

    /**
     * Initializes a new Processing Data object.
     */
    public function build(): ProcessingData
    {
        return CoreHelper::clone($this->instance);
    }
}
