<?php

declare(strict_types=1);

/*
 * SplititWebApiV4Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SplititWebApiV4Lib\Models\Builders;

use Core\Utils\CoreHelper;
use SplititWebApiV4Lib\Models\RedirectUrls;

/**
 * Builder for model RedirectUrls
 *
 * @see RedirectUrls
 */
class RedirectUrlsBuilder
{
    /**
     * @var RedirectUrls
     */
    private $instance;

    private function __construct(RedirectUrls $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Redirect Urls Builder object.
     *
     * @param string $successUrl
     */
    public static function init(string $successUrl): self
    {
        return new self(new RedirectUrls($successUrl));
    }

    /**
     * Sets Failure Url field.
     *
     * @param string|null $value
     */
    public function failureUrl(?string $value): self
    {
        $this->instance->setFailureUrl($value);
        return $this;
    }

    /**
     * Sets Cancel Url field.
     *
     * @param string|null $value
     */
    public function cancelUrl(?string $value): self
    {
        $this->instance->setCancelUrl($value);
        return $this;
    }

    /**
     * Initializes a new Redirect Urls object.
     */
    public function build(): RedirectUrls
    {
        return CoreHelper::clone($this->instance);
    }
}
