<?php

declare(strict_types=1);

/*
 * SplititWebApiV4Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SplititWebApiV4Lib\Models\Builders;

use Core\Utils\CoreHelper;
use SplititWebApiV4Lib\Models\RefundRequest;

/**
 * Builder for model RefundRequest
 *
 * @see RefundRequest
 */
class RefundRequestBuilder
{
    /**
     * @var RefundRequest
     */
    private $instance;

    private function __construct(RefundRequest $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Refund Request Builder object.
     *
     * @param string $amount
     */
    public static function init(string $amount): self
    {
        return new self(new RefundRequest($amount));
    }

    /**
     * Sets Reference Id field.
     *
     * @param string|null $value
     */
    public function referenceId(?string $value): self
    {
        $this->instance->setReferenceId($value);
        return $this;
    }

    /**
     * Initializes a new Refund Request object.
     */
    public function build(): RefundRequest
    {
        return CoreHelper::clone($this->instance);
    }
}
