<?php

declare(strict_types=1);

/*
 * SplititWebApiV4Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SplititWebApiV4Lib\Models\Builders;

use Core\Utils\CoreHelper;
use SplititWebApiV4Lib\Models\RefundItem;

/**
 * Builder for model RefundItem
 *
 * @see RefundItem
 */
class RefundItemBuilder
{
    /**
     * @var RefundItem
     */
    private $instance;

    private function __construct(RefundItem $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Refund Item Builder object.
     *
     * @param float $requestedAmount
     */
    public static function init(float $requestedAmount): self
    {
        return new self(new RefundItem($requestedAmount));
    }

    /**
     * Sets Submit Date field.
     *
     * @param \DateTime|null $value
     */
    public function submitDate(?\DateTime $value): self
    {
        $this->instance->setSubmitDate($value);
        return $this;
    }

    /**
     * Sets Status field.
     *
     * @param string|null $value
     */
    public function status(?string $value): self
    {
        $this->instance->setStatus($value);
        return $this;
    }

    /**
     * Sets Non Credit Refund Amount field.
     *
     * @param float|null $value
     */
    public function nonCreditRefundAmount(?float $value): self
    {
        $this->instance->setNonCreditRefundAmount($value);
        return $this;
    }

    /**
     * Sets Credit Refund Amount field.
     *
     * @param float|null $value
     */
    public function creditRefundAmount(?float $value): self
    {
        $this->instance->setCreditRefundAmount($value);
        return $this;
    }

    /**
     * Sets Refund Id field.
     *
     * @param string|null $value
     */
    public function refundId(?string $value): self
    {
        $this->instance->setRefundId($value);
        return $this;
    }

    /**
     * Sets Reference Id field.
     *
     * @param string|null $value
     */
    public function referenceId(?string $value): self
    {
        $this->instance->setReferenceId($value);
        return $this;
    }

    /**
     * Initializes a new Refund Item object.
     */
    public function build(): RefundItem
    {
        return CoreHelper::clone($this->instance);
    }
}
