<?php

declare(strict_types=1);

/*
 * SplititWebApiV4Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SplititWebApiV4Lib\Models\Builders;

use Core\Utils\CoreHelper;
use SplititWebApiV4Lib\Models\RefundResponse;

/**
 * Builder for model RefundResponse
 *
 * @see RefundResponse
 */
class RefundResponseBuilder
{
    /**
     * @var RefundResponse
     */
    private $instance;

    private function __construct(RefundResponse $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Refund Response Builder object.
     *
     * @param float $requestedAmount
     */
    public static function init(float $requestedAmount): self
    {
        return new self(new RefundResponse($requestedAmount));
    }

    /**
     * Sets Refund Id field.
     *
     * @param string|null $value
     */
    public function refundId(?string $value): self
    {
        $this->instance->setRefundId($value);
        return $this;
    }

    /**
     * Sets Installment Plan Number field.
     *
     * @param string|null $value
     */
    public function installmentPlanNumber(?string $value): self
    {
        $this->instance->setInstallmentPlanNumber($value);
        return $this;
    }

    /**
     * Sets Currency field.
     *
     * @param string|null $value
     */
    public function currency(?string $value): self
    {
        $this->instance->setCurrency($value);
        return $this;
    }

    /**
     * Sets Reference Id field.
     *
     * @param string|null $value
     */
    public function referenceId(?string $value): self
    {
        $this->instance->setReferenceId($value);
        return $this;
    }

    /**
     * Initializes a new Refund Response object.
     */
    public function build(): RefundResponse
    {
        return CoreHelper::clone($this->instance);
    }
}
