<?php

declare(strict_types=1);

/*
 * SplititWebApiV4Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SplititWebApiV4Lib\Models\Builders;

use Core\Utils\CoreHelper;
use SplititWebApiV4Lib\Models\BillingAddressData;
use SplititWebApiV4Lib\Models\ShopperDetailsData;

/**
 * Builder for model ShopperDetailsData
 *
 * @see ShopperDetailsData
 */
class ShopperDetailsDataBuilder
{
    /**
     * @var ShopperDetailsData
     */
    private $instance;

    private function __construct(ShopperDetailsData $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Shopper Details Data Builder object.
     */
    public static function init(): self
    {
        return new self(new ShopperDetailsData());
    }

    /**
     * Sets First Name field.
     *
     * @param string|null $value
     */
    public function firstName(?string $value): self
    {
        $this->instance->setFirstName($value);
        return $this;
    }

    /**
     * Sets Last Name field.
     *
     * @param string|null $value
     */
    public function lastName(?string $value): self
    {
        $this->instance->setLastName($value);
        return $this;
    }

    /**
     * Sets Email field.
     *
     * @param string|null $value
     */
    public function email(?string $value): self
    {
        $this->instance->setEmail($value);
        return $this;
    }

    /**
     * Sets Phone Number field.
     *
     * @param string|null $value
     */
    public function phoneNumber(?string $value): self
    {
        $this->instance->setPhoneNumber($value);
        return $this;
    }

    /**
     * Sets Culture field.
     *
     * @param string|null $value
     */
    public function culture(?string $value): self
    {
        $this->instance->setCulture($value);
        return $this;
    }

    /**
     * Sets Billing Address field.
     *
     * @param BillingAddressData|null $value
     */
    public function billingAddress(?BillingAddressData $value): self
    {
        $this->instance->setBillingAddress($value);
        return $this;
    }

    /**
     * Initializes a new Shopper Details Data object.
     */
    public function build(): ShopperDetailsData
    {
        return CoreHelper::clone($this->instance);
    }
}
