<?php

declare(strict_types=1);

/*
 * SplititWebApiV4Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SplititWebApiV4Lib\Models\Builders;

use Core\Utils\CoreHelper;
use SplititWebApiV4Lib\Models\ThreeDSAuthenticationData;

/**
 * Builder for model ThreeDSAuthenticationData
 *
 * @see ThreeDSAuthenticationData
 */
class ThreeDSAuthenticationDataBuilder
{
    /**
     * @var ThreeDSAuthenticationData
     */
    private $instance;

    private function __construct(ThreeDSAuthenticationData $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Three DS Authentication Data Builder object.
     *
     * @param string $eCI
     * @param string $cAVV
     * @param string $directoryServerTransactionId
     * @param string $version
     */
    public static function init(string $eCI, string $cAVV, string $directoryServerTransactionId, string $version): self
    {
        return new self(new ThreeDSAuthenticationData($eCI, $cAVV, $directoryServerTransactionId, $version));
    }

    /**
     * Initializes a new Three DS Authentication Data object.
     */
    public function build(): ThreeDSAuthenticationData
    {
        return CoreHelper::clone($this->instance);
    }
}
