<?php

declare(strict_types=1);

/*
 * SplititWebApiV4Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SplititWebApiV4Lib\Models\Builders;

use Core\Utils\CoreHelper;
use SplititWebApiV4Lib\Models\ThreeDSExecute;

/**
 * Builder for model ThreeDSExecute
 *
 * @see ThreeDSExecute
 */
class ThreeDSExecuteBuilder
{
    /**
     * @var ThreeDSExecute
     */
    private $instance;

    private function __construct(ThreeDSExecute $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Three DS Execute Builder object.
     */
    public static function init(): self
    {
        return new self(new ThreeDSExecute());
    }

    /**
     * Sets Execute field.
     *
     * @param bool|null $value
     */
    public function execute(?bool $value): self
    {
        $this->instance->setExecute($value);
        return $this;
    }

    /**
     * Initializes a new Three DS Execute object.
     */
    public function build(): ThreeDSExecute
    {
        return CoreHelper::clone($this->instance);
    }
}
