<?php

declare(strict_types=1);

/*
 * SplititWebApiV4Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SplititWebApiV4Lib\Models\Builders;

use Core\Utils\CoreHelper;
use SplititWebApiV4Lib\Models\ThreeDSRedirectData;

/**
 * Builder for model ThreeDSRedirectData
 *
 * @see ThreeDSRedirectData
 */
class ThreeDSRedirectDataBuilder
{
    /**
     * @var ThreeDSRedirectData
     */
    private $instance;

    private function __construct(ThreeDSRedirectData $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Three DS Redirect Data Builder object.
     */
    public static function init(): self
    {
        return new self(new ThreeDSRedirectData());
    }

    /**
     * Sets Url field.
     *
     * @param string|null $value
     */
    public function url(?string $value): self
    {
        $this->instance->setUrl($value);
        return $this;
    }

    /**
     * Sets Verb field.
     *
     * @param string|null $value
     */
    public function verb(?string $value): self
    {
        $this->instance->setVerb($value);
        return $this;
    }

    /**
     * Sets Params field.
     *
     * @param array<string,string>|null $value
     */
    public function params(?array $value): self
    {
        $this->instance->setParams($value);
        return $this;
    }

    /**
     * Sets Client Redirect Url field.
     *
     * @param string|null $value
     */
    public function clientRedirectUrl(?string $value): self
    {
        $this->instance->setClientRedirectUrl($value);
        return $this;
    }

    /**
     * Initializes a new Three DS Redirect Data object.
     */
    public function build(): ThreeDSRedirectData
    {
        return CoreHelper::clone($this->instance);
    }
}
