<?php

declare(strict_types=1);

/*
 * SplititWebApiV4Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SplititWebApiV4Lib\Models\Builders;

use Core\Utils\CoreHelper;
use SplititWebApiV4Lib\Models\RedirectUrls;
use SplititWebApiV4Lib\Models\ThreeDSAuthenticationData;
use SplititWebApiV4Lib\Models\ThreeDSRequestData;

/**
 * Builder for model ThreeDSRequestData
 *
 * @see ThreeDSRequestData
 */
class ThreeDSRequestDataBuilder
{
    /**
     * @var ThreeDSRequestData
     */
    private $instance;

    private function __construct(ThreeDSRequestData $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Three DS Request Data Builder object.
     */
    public static function init(): self
    {
        return new self(new ThreeDSRequestData());
    }

    /**
     * Sets Execute field.
     *
     * @param bool|null $value
     */
    public function execute(?bool $value): self
    {
        $this->instance->setExecute($value);
        return $this;
    }

    /**
     * Sets Three DSUR Ls field.
     *
     * @param RedirectUrls|null $value
     */
    public function threeDSURLs(?RedirectUrls $value): self
    {
        $this->instance->setThreeDSURLs($value);
        return $this;
    }

    /**
     * Sets Authentication Data field.
     *
     * @param ThreeDSAuthenticationData|null $value
     */
    public function authenticationData(?ThreeDSAuthenticationData $value): self
    {
        $this->instance->setAuthenticationData($value);
        return $this;
    }

    /**
     * Initializes a new Three DS Request Data object.
     */
    public function build(): ThreeDSRequestData
    {
        return CoreHelper::clone($this->instance);
    }
}
