<?php

declare(strict_types=1);

/*
 * SplititWebApiV4Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SplititWebApiV4Lib\Models\Builders;

use Core\Utils\CoreHelper;
use SplititWebApiV4Lib\Models\CardDetails;
use SplititWebApiV4Lib\Models\UpdateOffersPaymentMethod;

/**
 * Builder for model UpdateOffersPaymentMethod
 *
 * @see UpdateOffersPaymentMethod
 */
class UpdateOffersPaymentMethodBuilder
{
    /**
     * @var UpdateOffersPaymentMethod
     */
    private $instance;

    private function __construct(UpdateOffersPaymentMethod $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Update Offers Payment Method Builder object.
     *
     * @param CardDetails $cardDetails
     */
    public static function init(CardDetails $cardDetails): self
    {
        return new self(new UpdateOffersPaymentMethod($cardDetails));
    }

    /**
     * Initializes a new Update Offers Payment Method object.
     */
    public function build(): UpdateOffersPaymentMethod
    {
        return CoreHelper::clone($this->instance);
    }
}
