<?php

declare(strict_types=1);

/*
 * SplititWebApiV4Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SplititWebApiV4Lib\Models\Builders;

use Core\Utils\CoreHelper;
use SplititWebApiV4Lib\Models\MetadataItem;
use SplititWebApiV4Lib\Models\UpdateOrderResponse;

/**
 * Builder for model UpdateOrderResponse
 *
 * @see UpdateOrderResponse
 */
class UpdateOrderResponseBuilder
{
    /**
     * @var UpdateOrderResponse
     */
    private $instance;

    private function __construct(UpdateOrderResponse $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Update Order Response Builder object.
     *
     * @param string $status
     */
    public static function init(string $status): self
    {
        return new self(new UpdateOrderResponse($status));
    }

    /**
     * Sets Merchant Order Reference field.
     *
     * @param string|null $value
     */
    public function merchantOrderReference(?string $value): self
    {
        $this->instance->setMerchantOrderReference($value);
        return $this;
    }

    /**
     * Sets Tracking Number field.
     *
     * @param string|null $value
     */
    public function trackingNumber(?string $value): self
    {
        $this->instance->setTrackingNumber($value);
        return $this;
    }

    /**
     * Sets Shipping Status field.
     *
     * @param string|null $value
     */
    public function shippingStatus(?string $value): self
    {
        $this->instance->setShippingStatus($value);
        return $this;
    }

    /**
     * Sets Metadata field.
     *
     * @param MetadataItem[]|null $value
     */
    public function metadata(?array $value): self
    {
        $this->instance->setMetadata($value);
        return $this;
    }

    /**
     * Sets Installment Plan Number field.
     *
     * @param string|null $value
     */
    public function installmentPlanNumber(?string $value): self
    {
        $this->instance->setInstallmentPlanNumber($value);
        return $this;
    }

    /**
     * Initializes a new Update Order Response object.
     */
    public function build(): UpdateOrderResponse
    {
        return CoreHelper::clone($this->instance);
    }
}
