<?php

declare(strict_types=1);

/*
 * SplititWebApiV4Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SplititWebApiV4Lib\Models\Builders;

use Core\Utils\CoreHelper;
use SplititWebApiV4Lib\Models\MetadataItem;
use SplititWebApiV4Lib\Models\OffersShopperDetails;
use SplititWebApiV4Lib\Models\UpdateOffersPaymentMethod;
use SplititWebApiV4Lib\Models\UpdateOffersRequest;

/**
 * Builder for model UpdateOffersRequest
 *
 * @see UpdateOffersRequest
 */
class UpdateOffersRequestBuilder
{
    /**
     * @var UpdateOffersRequest
     */
    private $instance;

    private function __construct(UpdateOffersRequest $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Update Offers Request Builder object.
     */
    public static function init(): self
    {
        return new self(new UpdateOffersRequest());
    }

    /**
     * Sets Merchant Order Reference field.
     *
     * @param string|null $value
     */
    public function merchantOrderReference(?string $value): self
    {
        $this->instance->setMerchantOrderReference($value);
        return $this;
    }

    /**
     * Sets Shopper Details field.
     *
     * @param OffersShopperDetails|null $value
     */
    public function shopperDetails(?OffersShopperDetails $value): self
    {
        $this->instance->setShopperDetails($value);
        return $this;
    }

    /**
     * Sets Payment Method field.
     *
     * @param UpdateOffersPaymentMethod|null $value
     */
    public function paymentMethod(?UpdateOffersPaymentMethod $value): self
    {
        $this->instance->setPaymentMethod($value);
        return $this;
    }

    /**
     * Sets Metadata field.
     *
     * @param MetadataItem[]|null $value
     */
    public function metadata(?array $value): self
    {
        $this->instance->setMetadata($value);
        return $this;
    }

    /**
     * Initializes a new Update Offers Request object.
     */
    public function build(): UpdateOffersRequest
    {
        return CoreHelper::clone($this->instance);
    }
}
