<?php

declare(strict_types=1);

/*
 * SplititWebApiV4Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SplititWebApiV4Lib\Models\Builders;

use Core\Utils\CoreHelper;
use SplititWebApiV4Lib\Models\MetadataItem;
use SplititWebApiV4Lib\Models\UpdateOrderRequest;

/**
 * Builder for model UpdateOrderRequest
 *
 * @see UpdateOrderRequest
 */
class UpdateOrderRequestBuilder
{
    /**
     * @var UpdateOrderRequest
     */
    private $instance;

    private function __construct(UpdateOrderRequest $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Update Order Request Builder object.
     *
     * @param string $shippingStatus
     */
    public static function init(string $shippingStatus): self
    {
        return new self(new UpdateOrderRequest($shippingStatus));
    }

    /**
     * Sets Tracking Number field.
     *
     * @param string|null $value
     */
    public function trackingNumber(?string $value): self
    {
        $this->instance->setTrackingNumber($value);
        return $this;
    }

    /**
     * Sets Metadata field.
     *
     * @param MetadataItem[]|null $value
     */
    public function metadata(?array $value): self
    {
        $this->instance->setMetadata($value);
        return $this;
    }

    /**
     * Sets Merchant Order Reference field.
     *
     * @param string|null $value
     */
    public function merchantOrderReference(?string $value): self
    {
        $this->instance->setMerchantOrderReference($value);
        return $this;
    }

    /**
     * Initializes a new Update Order Request object.
     */
    public function build(): UpdateOrderRequest
    {
        return CoreHelper::clone($this->instance);
    }
}
