<?php

declare(strict_types=1);

/*
 * SplititWebApiV4Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SplititWebApiV4Lib\Models\Builders;

use Core\Utils\CoreHelper;
use SplititWebApiV4Lib\Models\ValidationError;

/**
 * Builder for model ValidationError
 *
 * @see ValidationError
 */
class ValidationErrorBuilder
{
    /**
     * @var ValidationError
     */
    private $instance;

    private function __construct(ValidationError $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Validation Error Builder object.
     */
    public static function init(): self
    {
        return new self(new ValidationError());
    }

    /**
     * Sets Code field.
     *
     * @param string|null $value
     */
    public function code(?string $value): self
    {
        $this->instance->setCode($value);
        return $this;
    }

    /**
     * Sets Message field.
     *
     * @param string|null $value
     */
    public function message(?string $value): self
    {
        $this->instance->setMessage($value);
        return $this;
    }

    /**
     * Initializes a new Validation Error object.
     */
    public function build(): ValidationError
    {
        return CoreHelper::clone($this->instance);
    }
}
