<?php

declare(strict_types=1);

/*
 * SplititWebApiV4Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SplititWebApiV4Lib\Exceptions;

use SplititWebApiV4Lib\ApiHelper;

class ApiErrorResponseException extends ApiException
{
    /**
     * @var string|null
     */
    private $traceId;

    /**
     * @var \SplititWebApiV4Lib\Models\ApiErrorModel|null
     */
    private $error;

    /**
     * Returns Trace Id.
     */
    public function getTraceId(): ?string
    {
        return $this->traceId;
    }

    /**
     * Sets Trace Id.
     *
     * @maps TraceId
     */
    public function setTraceId(?string $traceId): void
    {
        $this->traceId = $traceId;
    }

    /**
     * Returns Error.
     */
    public function getError(): ?\SplititWebApiV4Lib\Models\ApiErrorModel
    {
        return $this->error;
    }

    /**
     * Sets Error.
     *
     * @maps Error
     */
    public function setError(?\SplititWebApiV4Lib\Models\ApiErrorModel $error): void
    {
        $this->error = $error;
    }

    /**
     * Converts the ApiErrorResponseException object to a human-readable string representation.
     *
     * @return string The string representation of the ApiErrorResponseException object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'ApiErrorResponseException',
            ['traceId' => $this->traceId, 'error' => $this->error],
            parent::__toString()
        );
    }
}
