<?php

declare(strict_types=1);

/*
 * SplititWebApiV4Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SplititWebApiV4Lib\Models;

use SplititWebApiV4Lib\ApiHelper;
use stdClass;

class AmountData implements \JsonSerializable
{
    /**
     * @var float
     */
    private $value;

    /**
     * @var string|null
     */
    private $symbol;

    /**
     * @param float $value
     */
    public function __construct(float $value)
    {
        $this->value = $value;
    }

    /**
     * Returns Value.
     */
    public function getValue(): float
    {
        return $this->value;
    }

    /**
     * Sets Value.
     *
     * @required
     * @maps Value
     */
    public function setValue(float $value): void
    {
        $this->value = $value;
    }

    /**
     * Returns Symbol.
     */
    public function getSymbol(): ?string
    {
        return $this->symbol;
    }

    /**
     * Sets Symbol.
     *
     * @maps Symbol
     */
    public function setSymbol(?string $symbol): void
    {
        $this->symbol = $symbol;
    }

    /**
     * Converts the AmountData object to a human-readable string representation.
     *
     * @return string The string representation of the AmountData object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify('AmountData', ['value' => $this->value, 'symbol' => $this->symbol]);
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        $json['Value']      = $this->value;
        if (isset($this->symbol)) {
            $json['Symbol'] = $this->symbol;
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
