<?php

declare(strict_types=1);

/*
 * SplititWebApiV4Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SplititWebApiV4Lib\Models;

use Core\Utils\CoreHelper;
use Exception;
use stdClass;

class AuthorizationStatusEnum
{
    /**
     * Authorization succeeded
     */
    public const SUCCEEDED = 'Succeeded';

    /**
     * Waiting for 3DS authentication
     */
    public const PENDING3DS = 'Pending3DS';

    /**
     * Authorization Failed
     */
    public const FAILED = 'Failed';

    private const _ALL_VALUES = [self::SUCCEEDED, self::PENDING3DS, self::FAILED];

    /**
     * Ensures that all the given values are present in this Enum.
     *
     * @param array|stdClass|null|string $value Value or a list/map of values to be checked
     *
     * @return array|null|string Input value(s), if all are a part of this Enum
     *
     * @throws Exception Throws exception if any given value is not in this Enum
     */
    public static function checkValue($value)
    {
        $value = json_decode(json_encode($value), true); // converts stdClass into array
        if (CoreHelper::checkValueOrValuesInList($value, self::_ALL_VALUES)) {
            return $value;
        }
        throw new Exception("$value is invalid for AuthorizationStatusEnum.");
    }
}
