<?php

declare(strict_types=1);

/*
 * SplititWebApiV4Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SplititWebApiV4Lib\Models;

use SplititWebApiV4Lib\ApiHelper;
use stdClass;

class AuthorizeRequest implements \JsonSerializable
{
    /**
     * @var string
     */
    private $offerId;

    /**
     * @var bool
     */
    private $autoCapture;

    /**
     * @var bool
     */
    private $shopperAcceptedTerms;

    /**
     * @var string|null
     */
    private $merchantOrderReference;

    /**
     * @var ThreeDSRequestData|null
     */
    private $threeDS;

    /**
     * @var ProcessingData|null
     */
    private $processingData;

    /**
     * @param string $offerId
     * @param bool $autoCapture
     * @param bool $shopperAcceptedTerms
     */
    public function __construct(string $offerId, bool $autoCapture, bool $shopperAcceptedTerms)
    {
        $this->offerId = $offerId;
        $this->autoCapture = $autoCapture;
        $this->shopperAcceptedTerms = $shopperAcceptedTerms;
    }

    /**
     * Returns Offer Id.
     */
    public function getOfferId(): string
    {
        return $this->offerId;
    }

    /**
     * Sets Offer Id.
     *
     * @required
     * @maps OfferId
     */
    public function setOfferId(string $offerId): void
    {
        $this->offerId = $offerId;
    }

    /**
     * Returns Auto Capture.
     */
    public function getAutoCapture(): bool
    {
        return $this->autoCapture;
    }

    /**
     * Sets Auto Capture.
     *
     * @required
     * @maps AutoCapture
     */
    public function setAutoCapture(bool $autoCapture): void
    {
        $this->autoCapture = $autoCapture;
    }

    /**
     * Returns Shopper Accepted Terms.
     */
    public function getShopperAcceptedTerms(): bool
    {
        return $this->shopperAcceptedTerms;
    }

    /**
     * Sets Shopper Accepted Terms.
     *
     * @required
     * @maps ShopperAcceptedTerms
     */
    public function setShopperAcceptedTerms(bool $shopperAcceptedTerms): void
    {
        $this->shopperAcceptedTerms = $shopperAcceptedTerms;
    }

    /**
     * Returns Merchant Order Reference.
     */
    public function getMerchantOrderReference(): ?string
    {
        return $this->merchantOrderReference;
    }

    /**
     * Sets Merchant Order Reference.
     *
     * @maps MerchantOrderReference
     */
    public function setMerchantOrderReference(?string $merchantOrderReference): void
    {
        $this->merchantOrderReference = $merchantOrderReference;
    }

    /**
     * Returns Three DS.
     */
    public function getThreeDS(): ?ThreeDSRequestData
    {
        return $this->threeDS;
    }

    /**
     * Sets Three DS.
     *
     * @maps ThreeDS
     */
    public function setThreeDS(?ThreeDSRequestData $threeDS): void
    {
        $this->threeDS = $threeDS;
    }

    /**
     * Returns Processing Data.
     */
    public function getProcessingData(): ?ProcessingData
    {
        return $this->processingData;
    }

    /**
     * Sets Processing Data.
     *
     * @maps ProcessingData
     */
    public function setProcessingData(?ProcessingData $processingData): void
    {
        $this->processingData = $processingData;
    }

    /**
     * Converts the AuthorizeRequest object to a human-readable string representation.
     *
     * @return string The string representation of the AuthorizeRequest object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'AuthorizeRequest',
            [
                'offerId' => $this->offerId,
                'autoCapture' => $this->autoCapture,
                'shopperAcceptedTerms' => $this->shopperAcceptedTerms,
                'merchantOrderReference' => $this->merchantOrderReference,
                'threeDS' => $this->threeDS,
                'processingData' => $this->processingData
            ]
        );
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        $json['OfferId']                    = $this->offerId;
        $json['AutoCapture']                = $this->autoCapture;
        $json['ShopperAcceptedTerms']       = $this->shopperAcceptedTerms;
        if (isset($this->merchantOrderReference)) {
            $json['MerchantOrderReference'] = $this->merchantOrderReference;
        }
        if (isset($this->threeDS)) {
            $json['ThreeDS']                = $this->threeDS;
        }
        if (isset($this->processingData)) {
            $json['ProcessingData']         = $this->processingData;
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
