<?php

declare(strict_types=1);

/*
 * SplititWebApiV4Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SplititWebApiV4Lib\Models;

use SplititWebApiV4Lib\ApiHelper;
use SplititWebApiV4Lib\Utils\DateTimeHelper;
use stdClass;

class AuthorizeResponse implements \JsonSerializable
{
    /**
     * @var \DateTime
     */
    private $dateCreated;

    /**
     * @var string
     */
    private $planStatus;

    /**
     * @var string|null
     */
    private $installmentPlanNumber;

    /**
     * @var string|null
     */
    private $merchantOrderReference;

    /**
     * @var string
     */
    private $purchaseMethod;

    /**
     * @var string|null
     */
    private $currency;

    /**
     * @var float
     */
    private $purchaseAmount;

    /**
     * @var float
     */
    private $totalFees;

    /**
     * @var float
     */
    private $totalAmount;

    /**
     * @var AprData|null
     */
    private $apr;

    /**
     * @var AuthorizeAuthorizationData|null
     */
    private $authorization;

    /**
     * @var PaymentMethodData|null
     */
    private $paymentMethod;

    /**
     * @var InstallmentItem[]|null
     */
    private $installments;

    /**
     * @var MetadataItem[]|null
     */
    private $metadata;

    /**
     * @param \DateTime $dateCreated
     * @param string $planStatus
     * @param string $purchaseMethod
     * @param float $purchaseAmount
     * @param float $totalFees
     * @param float $totalAmount
     */
    public function __construct(
        \DateTime $dateCreated,
        string $planStatus,
        string $purchaseMethod,
        float $purchaseAmount,
        float $totalFees,
        float $totalAmount
    ) {
        $this->dateCreated = $dateCreated;
        $this->planStatus = $planStatus;
        $this->purchaseMethod = $purchaseMethod;
        $this->purchaseAmount = $purchaseAmount;
        $this->totalFees = $totalFees;
        $this->totalAmount = $totalAmount;
    }

    /**
     * Returns Date Created.
     */
    public function getDateCreated(): \DateTime
    {
        return $this->dateCreated;
    }

    /**
     * Sets Date Created.
     *
     * @required
     * @maps DateCreated
     * @factory \SplititWebApiV4Lib\Utils\DateTimeHelper::fromRfc3339DateTime
     */
    public function setDateCreated(\DateTime $dateCreated): void
    {
        $this->dateCreated = $dateCreated;
    }

    /**
     * Returns Plan Status.
     */
    public function getPlanStatus(): string
    {
        return $this->planStatus;
    }

    /**
     * Sets Plan Status.
     *
     * @required
     * @maps PlanStatus
     * @factory \SplititWebApiV4Lib\Models\InstallmentPlanStatusEnum::checkValue
     */
    public function setPlanStatus(string $planStatus): void
    {
        $this->planStatus = $planStatus;
    }

    /**
     * Returns Installment Plan Number.
     */
    public function getInstallmentPlanNumber(): ?string
    {
        return $this->installmentPlanNumber;
    }

    /**
     * Sets Installment Plan Number.
     *
     * @maps InstallmentPlanNumber
     */
    public function setInstallmentPlanNumber(?string $installmentPlanNumber): void
    {
        $this->installmentPlanNumber = $installmentPlanNumber;
    }

    /**
     * Returns Merchant Order Reference.
     */
    public function getMerchantOrderReference(): ?string
    {
        return $this->merchantOrderReference;
    }

    /**
     * Sets Merchant Order Reference.
     *
     * @maps MerchantOrderReference
     */
    public function setMerchantOrderReference(?string $merchantOrderReference): void
    {
        $this->merchantOrderReference = $merchantOrderReference;
    }

    /**
     * Returns Purchase Method.
     */
    public function getPurchaseMethod(): string
    {
        return $this->purchaseMethod;
    }

    /**
     * Sets Purchase Method.
     *
     * @required
     * @maps PurchaseMethod
     * @factory \SplititWebApiV4Lib\Models\PurchaseMethodEnum::checkValue
     */
    public function setPurchaseMethod(string $purchaseMethod): void
    {
        $this->purchaseMethod = $purchaseMethod;
    }

    /**
     * Returns Currency.
     */
    public function getCurrency(): ?string
    {
        return $this->currency;
    }

    /**
     * Sets Currency.
     *
     * @maps Currency
     */
    public function setCurrency(?string $currency): void
    {
        $this->currency = $currency;
    }

    /**
     * Returns Purchase Amount.
     */
    public function getPurchaseAmount(): float
    {
        return $this->purchaseAmount;
    }

    /**
     * Sets Purchase Amount.
     *
     * @required
     * @maps PurchaseAmount
     */
    public function setPurchaseAmount(float $purchaseAmount): void
    {
        $this->purchaseAmount = $purchaseAmount;
    }

    /**
     * Returns Total Fees.
     */
    public function getTotalFees(): float
    {
        return $this->totalFees;
    }

    /**
     * Sets Total Fees.
     *
     * @required
     * @maps TotalFees
     */
    public function setTotalFees(float $totalFees): void
    {
        $this->totalFees = $totalFees;
    }

    /**
     * Returns Total Amount.
     */
    public function getTotalAmount(): float
    {
        return $this->totalAmount;
    }

    /**
     * Sets Total Amount.
     *
     * @required
     * @maps TotalAmount
     */
    public function setTotalAmount(float $totalAmount): void
    {
        $this->totalAmount = $totalAmount;
    }

    /**
     * Returns Apr.
     */
    public function getApr(): ?AprData
    {
        return $this->apr;
    }

    /**
     * Sets Apr.
     *
     * @maps Apr
     */
    public function setApr(?AprData $apr): void
    {
        $this->apr = $apr;
    }

    /**
     * Returns Authorization.
     */
    public function getAuthorization(): ?AuthorizeAuthorizationData
    {
        return $this->authorization;
    }

    /**
     * Sets Authorization.
     *
     * @maps Authorization
     */
    public function setAuthorization(?AuthorizeAuthorizationData $authorization): void
    {
        $this->authorization = $authorization;
    }

    /**
     * Returns Payment Method.
     */
    public function getPaymentMethod(): ?PaymentMethodData
    {
        return $this->paymentMethod;
    }

    /**
     * Sets Payment Method.
     *
     * @maps PaymentMethod
     */
    public function setPaymentMethod(?PaymentMethodData $paymentMethod): void
    {
        $this->paymentMethod = $paymentMethod;
    }

    /**
     * Returns Installments.
     *
     * @return InstallmentItem[]|null
     */
    public function getInstallments(): ?array
    {
        return $this->installments;
    }

    /**
     * Sets Installments.
     *
     * @maps Installments
     *
     * @param InstallmentItem[]|null $installments
     */
    public function setInstallments(?array $installments): void
    {
        $this->installments = $installments;
    }

    /**
     * Returns Metadata.
     *
     * @return MetadataItem[]|null
     */
    public function getMetadata(): ?array
    {
        return $this->metadata;
    }

    /**
     * Sets Metadata.
     *
     * @maps Metadata
     *
     * @param MetadataItem[]|null $metadata
     */
    public function setMetadata(?array $metadata): void
    {
        $this->metadata = $metadata;
    }

    /**
     * Converts the AuthorizeResponse object to a human-readable string representation.
     *
     * @return string The string representation of the AuthorizeResponse object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'AuthorizeResponse',
            [
                'dateCreated' => $this->dateCreated,
                'planStatus' => $this->planStatus,
                'installmentPlanNumber' => $this->installmentPlanNumber,
                'merchantOrderReference' => $this->merchantOrderReference,
                'purchaseMethod' => $this->purchaseMethod,
                'currency' => $this->currency,
                'purchaseAmount' => $this->purchaseAmount,
                'totalFees' => $this->totalFees,
                'totalAmount' => $this->totalAmount,
                'apr' => $this->apr,
                'authorization' => $this->authorization,
                'paymentMethod' => $this->paymentMethod,
                'installments' => $this->installments,
                'metadata' => $this->metadata
            ]
        );
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        $json['DateCreated']                = DateTimeHelper::toRfc3339DateTime($this->dateCreated);
        $json['PlanStatus']                 = InstallmentPlanStatusEnum::checkValue($this->planStatus);
        if (isset($this->installmentPlanNumber)) {
            $json['InstallmentPlanNumber']  = $this->installmentPlanNumber;
        }
        if (isset($this->merchantOrderReference)) {
            $json['MerchantOrderReference'] = $this->merchantOrderReference;
        }
        $json['PurchaseMethod']             = PurchaseMethodEnum::checkValue($this->purchaseMethod);
        if (isset($this->currency)) {
            $json['Currency']               = $this->currency;
        }
        $json['PurchaseAmount']             = $this->purchaseAmount;
        $json['TotalFees']                  = $this->totalFees;
        $json['TotalAmount']                = $this->totalAmount;
        if (isset($this->apr)) {
            $json['Apr']                    = $this->apr;
        }
        if (isset($this->authorization)) {
            $json['Authorization']          = $this->authorization;
        }
        if (isset($this->paymentMethod)) {
            $json['PaymentMethod']          = $this->paymentMethod;
        }
        if (isset($this->installments)) {
            $json['Installments']           = $this->installments;
        }
        if (isset($this->metadata)) {
            $json['Metadata']               = $this->metadata;
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
