<?php

declare(strict_types=1);

/*
 * SplititWebApiV4Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SplititWebApiV4Lib\Models;

use SplititWebApiV4Lib\ApiHelper;
use stdClass;

class CardDetails implements \JsonSerializable
{
    /**
     * @var string|null
     */
    private $firstName;

    /**
     * @var string|null
     */
    private $lastName;

    /**
     * @var string
     */
    private $cardNumber;

    /**
     * @var string
     */
    private $expYear;

    /**
     * @var string
     */
    private $expMonth;

    /**
     * @var string|null
     */
    private $cvv;

    /**
     * @param string $cardNumber
     * @param string $expYear
     * @param string $expMonth
     */
    public function __construct(string $cardNumber, string $expYear, string $expMonth)
    {
        $this->cardNumber = $cardNumber;
        $this->expYear = $expYear;
        $this->expMonth = $expMonth;
    }

    /**
     * Returns First Name.
     */
    public function getFirstName(): ?string
    {
        return $this->firstName;
    }

    /**
     * Sets First Name.
     *
     * @maps FirstName
     */
    public function setFirstName(?string $firstName): void
    {
        $this->firstName = $firstName;
    }

    /**
     * Returns Last Name.
     */
    public function getLastName(): ?string
    {
        return $this->lastName;
    }

    /**
     * Sets Last Name.
     *
     * @maps LastName
     */
    public function setLastName(?string $lastName): void
    {
        $this->lastName = $lastName;
    }

    /**
     * Returns Card Number.
     */
    public function getCardNumber(): string
    {
        return $this->cardNumber;
    }

    /**
     * Sets Card Number.
     *
     * @required
     * @maps CardNumber
     */
    public function setCardNumber(string $cardNumber): void
    {
        $this->cardNumber = $cardNumber;
    }

    /**
     * Returns Exp Year.
     */
    public function getExpYear(): string
    {
        return $this->expYear;
    }

    /**
     * Sets Exp Year.
     *
     * @required
     * @maps ExpYear
     */
    public function setExpYear(string $expYear): void
    {
        $this->expYear = $expYear;
    }

    /**
     * Returns Exp Month.
     */
    public function getExpMonth(): string
    {
        return $this->expMonth;
    }

    /**
     * Sets Exp Month.
     *
     * @required
     * @maps ExpMonth
     */
    public function setExpMonth(string $expMonth): void
    {
        $this->expMonth = $expMonth;
    }

    /**
     * Returns Cvv.
     */
    public function getCvv(): ?string
    {
        return $this->cvv;
    }

    /**
     * Sets Cvv.
     *
     * @maps Cvv
     */
    public function setCvv(?string $cvv): void
    {
        $this->cvv = $cvv;
    }

    /**
     * Converts the CardDetails object to a human-readable string representation.
     *
     * @return string The string representation of the CardDetails object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'CardDetails',
            [
                'firstName' => $this->firstName,
                'lastName' => $this->lastName,
                'cardNumber' => $this->cardNumber,
                'expYear' => $this->expYear,
                'expMonth' => $this->expMonth,
                'cvv' => $this->cvv
            ]
        );
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->firstName)) {
            $json['FirstName'] = $this->firstName;
        }
        if (isset($this->lastName)) {
            $json['LastName']  = $this->lastName;
        }
        $json['CardNumber']    = $this->cardNumber;
        $json['ExpYear']       = $this->expYear;
        $json['ExpMonth']      = $this->expMonth;
        if (isset($this->cvv)) {
            $json['Cvv']       = $this->cvv;
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
