<?php

declare(strict_types=1);

/*
 * SplititWebApiV4Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SplititWebApiV4Lib\Models;

use SplititWebApiV4Lib\ApiHelper;
use stdClass;

class CardValidityResponse implements \JsonSerializable
{
    /**
     * @var bool
     */
    private $result;

    /**
     * @var ValidationError[]|null
     */
    private $validationErrors;

    /**
     * @param bool $result
     */
    public function __construct(bool $result)
    {
        $this->result = $result;
    }

    /**
     * Returns Result.
     */
    public function getResult(): bool
    {
        return $this->result;
    }

    /**
     * Sets Result.
     *
     * @required
     * @maps Result
     */
    public function setResult(bool $result): void
    {
        $this->result = $result;
    }

    /**
     * Returns Validation Errors.
     *
     * @return ValidationError[]|null
     */
    public function getValidationErrors(): ?array
    {
        return $this->validationErrors;
    }

    /**
     * Sets Validation Errors.
     *
     * @maps ValidationErrors
     *
     * @param ValidationError[]|null $validationErrors
     */
    public function setValidationErrors(?array $validationErrors): void
    {
        $this->validationErrors = $validationErrors;
    }

    /**
     * Converts the CardValidityResponse object to a human-readable string representation.
     *
     * @return string The string representation of the CardValidityResponse object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'CardValidityResponse',
            ['result' => $this->result, 'validationErrors' => $this->validationErrors]
        );
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        $json['Result']               = $this->result;
        if (isset($this->validationErrors)) {
            $json['ValidationErrors'] = $this->validationErrors;
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
