<?php

declare(strict_types=1);

/*
 * SplititWebApiV4Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SplititWebApiV4Lib\Models;

use SplititWebApiV4Lib\ApiHelper;
use stdClass;

class InstallmentPlanSearchRequest implements \JsonSerializable
{
    /**
     * @var string[]|null
     */
    private $installmentPlanNumbers;

    /**
     * @var string[]|null
     */
    private $merchantOrderReferenceIds;

    /**
     * Returns Installment Plan Numbers.
     *
     * @return string[]|null
     */
    public function getInstallmentPlanNumbers(): ?array
    {
        return $this->installmentPlanNumbers;
    }

    /**
     * Sets Installment Plan Numbers.
     *
     * @maps InstallmentPlanNumbers
     *
     * @param string[]|null $installmentPlanNumbers
     */
    public function setInstallmentPlanNumbers(?array $installmentPlanNumbers): void
    {
        $this->installmentPlanNumbers = $installmentPlanNumbers;
    }

    /**
     * Returns Merchant Order Reference Ids.
     *
     * @return string[]|null
     */
    public function getMerchantOrderReferenceIds(): ?array
    {
        return $this->merchantOrderReferenceIds;
    }

    /**
     * Sets Merchant Order Reference Ids.
     *
     * @maps MerchantOrderReferenceIds
     *
     * @param string[]|null $merchantOrderReferenceIds
     */
    public function setMerchantOrderReferenceIds(?array $merchantOrderReferenceIds): void
    {
        $this->merchantOrderReferenceIds = $merchantOrderReferenceIds;
    }

    /**
     * Converts the InstallmentPlanSearchRequest object to a human-readable string representation.
     *
     * @return string The string representation of the InstallmentPlanSearchRequest object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'InstallmentPlanSearchRequest',
            [
                'installmentPlanNumbers' => $this->installmentPlanNumbers,
                'merchantOrderReferenceIds' => $this->merchantOrderReferenceIds
            ]
        );
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->installmentPlanNumbers)) {
            $json['InstallmentPlanNumbers']    = $this->installmentPlanNumbers;
        }
        if (isset($this->merchantOrderReferenceIds)) {
            $json['MerchantOrderReferenceIds'] = $this->merchantOrderReferenceIds;
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
