<?php

declare(strict_types=1);

/*
 * SplititWebApiV4Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SplititWebApiV4Lib\Models;

use SplititWebApiV4Lib\ApiHelper;
use SplititWebApiV4Lib\Utils\DateTimeHelper;
use stdClass;

class InstallmentItem implements \JsonSerializable
{
    /**
     * @var int
     */
    private $installmentNumber;

    /**
     * @var AmountData|null
     */
    private $amount;

    /**
     * @var string
     */
    private $status;

    /**
     * @var \DateTime|null
     */
    private $processDateTime;

    /**
     * @param int $installmentNumber
     * @param string $status
     */
    public function __construct(int $installmentNumber, string $status)
    {
        $this->installmentNumber = $installmentNumber;
        $this->status = $status;
    }

    /**
     * Returns Installment Number.
     */
    public function getInstallmentNumber(): int
    {
        return $this->installmentNumber;
    }

    /**
     * Sets Installment Number.
     *
     * @required
     * @maps InstallmentNumber
     */
    public function setInstallmentNumber(int $installmentNumber): void
    {
        $this->installmentNumber = $installmentNumber;
    }

    /**
     * Returns Amount.
     */
    public function getAmount(): ?AmountData
    {
        return $this->amount;
    }

    /**
     * Sets Amount.
     *
     * @maps Amount
     */
    public function setAmount(?AmountData $amount): void
    {
        $this->amount = $amount;
    }

    /**
     * Returns Status.
     */
    public function getStatus(): string
    {
        return $this->status;
    }

    /**
     * Sets Status.
     *
     * @required
     * @maps Status
     * @factory \SplititWebApiV4Lib\Models\InstallmentStatusEnum::checkValue
     */
    public function setStatus(string $status): void
    {
        $this->status = $status;
    }

    /**
     * Returns Process Date Time.
     */
    public function getProcessDateTime(): ?\DateTime
    {
        return $this->processDateTime;
    }

    /**
     * Sets Process Date Time.
     *
     * @maps ProcessDateTime
     * @factory \SplititWebApiV4Lib\Utils\DateTimeHelper::fromRfc3339DateTime
     */
    public function setProcessDateTime(?\DateTime $processDateTime): void
    {
        $this->processDateTime = $processDateTime;
    }

    /**
     * Converts the InstallmentItem object to a human-readable string representation.
     *
     * @return string The string representation of the InstallmentItem object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'InstallmentItem',
            [
                'installmentNumber' => $this->installmentNumber,
                'amount' => $this->amount,
                'status' => $this->status,
                'processDateTime' => $this->processDateTime
            ]
        );
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        $json['InstallmentNumber']   = $this->installmentNumber;
        if (isset($this->amount)) {
            $json['Amount']          = $this->amount;
        }
        $json['Status']              = InstallmentStatusEnum::checkValue($this->status);
        if (isset($this->processDateTime)) {
            $json['ProcessDateTime'] = DateTimeHelper::toRfc3339DateTime($this->processDateTime);
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
