<?php

declare(strict_types=1);

/*
 * SplititWebApiV4Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SplititWebApiV4Lib\Models;

use SplititWebApiV4Lib\ApiHelper;
use SplititWebApiV4Lib\Utils\DateTimeHelper;
use stdClass;

class InstallmentPlanDetailsResponse implements \JsonSerializable
{
    /**
     * @var \DateTime
     */
    private $dateCreated;

    /**
     * @var string
     */
    private $status;

    /**
     * @var string|null
     */
    private $installmentPlanNumber;

    /**
     * @var string|null
     */
    private $merchantOrderReference;

    /**
     * @var string
     */
    private $installmentProvider;

    /**
     * @var string
     */
    private $purchaseMethod;

    /**
     * @var string|null
     */
    private $currency;

    /**
     * @var float
     */
    private $purchaseAmount;

    /**
     * @var float
     */
    private $totalAmount;

    /**
     * @var float
     */
    private $totalFees;

    /**
     * @var AprData|null
     */
    private $apr;

    /**
     * @var PlanAuthorizationData|null
     */
    private $authorization;

    /**
     * @var ShopperDetailsData|null
     */
    private $shopperDetails;

    /**
     * @var PaymentMethodData|null
     */
    private $paymentMethod;

    /**
     * @var InstallmentItem[]|null
     */
    private $installments;

    /**
     * @var RefundItem[]|null
     */
    private $refunds;

    /**
     * @var PlanLinksData[]|null
     */
    private $links;

    /**
     * @var MetadataItem[]|null
     */
    private $metadata;

    /**
     * @param \DateTime $dateCreated
     * @param string $status
     * @param string $installmentProvider
     * @param string $purchaseMethod
     * @param float $purchaseAmount
     * @param float $totalAmount
     * @param float $totalFees
     */
    public function __construct(
        \DateTime $dateCreated,
        string $status,
        string $installmentProvider,
        string $purchaseMethod,
        float $purchaseAmount,
        float $totalAmount,
        float $totalFees
    ) {
        $this->dateCreated = $dateCreated;
        $this->status = $status;
        $this->installmentProvider = $installmentProvider;
        $this->purchaseMethod = $purchaseMethod;
        $this->purchaseAmount = $purchaseAmount;
        $this->totalAmount = $totalAmount;
        $this->totalFees = $totalFees;
    }

    /**
     * Returns Date Created.
     */
    public function getDateCreated(): \DateTime
    {
        return $this->dateCreated;
    }

    /**
     * Sets Date Created.
     *
     * @required
     * @maps DateCreated
     * @factory \SplititWebApiV4Lib\Utils\DateTimeHelper::fromRfc3339DateTime
     */
    public function setDateCreated(\DateTime $dateCreated): void
    {
        $this->dateCreated = $dateCreated;
    }

    /**
     * Returns Status.
     */
    public function getStatus(): string
    {
        return $this->status;
    }

    /**
     * Sets Status.
     *
     * @required
     * @maps Status
     * @factory \SplititWebApiV4Lib\Models\InstallmentPlanStatusEnum::checkValue
     */
    public function setStatus(string $status): void
    {
        $this->status = $status;
    }

    /**
     * Returns Installment Plan Number.
     */
    public function getInstallmentPlanNumber(): ?string
    {
        return $this->installmentPlanNumber;
    }

    /**
     * Sets Installment Plan Number.
     *
     * @maps InstallmentPlanNumber
     */
    public function setInstallmentPlanNumber(?string $installmentPlanNumber): void
    {
        $this->installmentPlanNumber = $installmentPlanNumber;
    }

    /**
     * Returns Merchant Order Reference.
     */
    public function getMerchantOrderReference(): ?string
    {
        return $this->merchantOrderReference;
    }

    /**
     * Sets Merchant Order Reference.
     *
     * @maps MerchantOrderReference
     */
    public function setMerchantOrderReference(?string $merchantOrderReference): void
    {
        $this->merchantOrderReference = $merchantOrderReference;
    }

    /**
     * Returns Installment Provider.
     */
    public function getInstallmentProvider(): string
    {
        return $this->installmentProvider;
    }

    /**
     * Sets Installment Provider.
     *
     * @required
     * @maps InstallmentProvider
     * @factory \SplititWebApiV4Lib\Models\ExternalProviderTypesEnum::checkValue
     */
    public function setInstallmentProvider(string $installmentProvider): void
    {
        $this->installmentProvider = $installmentProvider;
    }

    /**
     * Returns Purchase Method.
     */
    public function getPurchaseMethod(): string
    {
        return $this->purchaseMethod;
    }

    /**
     * Sets Purchase Method.
     *
     * @required
     * @maps PurchaseMethod
     * @factory \SplititWebApiV4Lib\Models\PurchaseMethodEnum::checkValue
     */
    public function setPurchaseMethod(string $purchaseMethod): void
    {
        $this->purchaseMethod = $purchaseMethod;
    }

    /**
     * Returns Currency.
     */
    public function getCurrency(): ?string
    {
        return $this->currency;
    }

    /**
     * Sets Currency.
     *
     * @maps Currency
     */
    public function setCurrency(?string $currency): void
    {
        $this->currency = $currency;
    }

    /**
     * Returns Purchase Amount.
     */
    public function getPurchaseAmount(): float
    {
        return $this->purchaseAmount;
    }

    /**
     * Sets Purchase Amount.
     *
     * @required
     * @maps PurchaseAmount
     */
    public function setPurchaseAmount(float $purchaseAmount): void
    {
        $this->purchaseAmount = $purchaseAmount;
    }

    /**
     * Returns Total Amount.
     */
    public function getTotalAmount(): float
    {
        return $this->totalAmount;
    }

    /**
     * Sets Total Amount.
     *
     * @required
     * @maps TotalAmount
     */
    public function setTotalAmount(float $totalAmount): void
    {
        $this->totalAmount = $totalAmount;
    }

    /**
     * Returns Total Fees.
     */
    public function getTotalFees(): float
    {
        return $this->totalFees;
    }

    /**
     * Sets Total Fees.
     *
     * @required
     * @maps TotalFees
     */
    public function setTotalFees(float $totalFees): void
    {
        $this->totalFees = $totalFees;
    }

    /**
     * Returns Apr.
     */
    public function getApr(): ?AprData
    {
        return $this->apr;
    }

    /**
     * Sets Apr.
     *
     * @maps Apr
     */
    public function setApr(?AprData $apr): void
    {
        $this->apr = $apr;
    }

    /**
     * Returns Authorization.
     */
    public function getAuthorization(): ?PlanAuthorizationData
    {
        return $this->authorization;
    }

    /**
     * Sets Authorization.
     *
     * @maps Authorization
     */
    public function setAuthorization(?PlanAuthorizationData $authorization): void
    {
        $this->authorization = $authorization;
    }

    /**
     * Returns Shopper Details.
     */
    public function getShopperDetails(): ?ShopperDetailsData
    {
        return $this->shopperDetails;
    }

    /**
     * Sets Shopper Details.
     *
     * @maps ShopperDetails
     */
    public function setShopperDetails(?ShopperDetailsData $shopperDetails): void
    {
        $this->shopperDetails = $shopperDetails;
    }

    /**
     * Returns Payment Method.
     */
    public function getPaymentMethod(): ?PaymentMethodData
    {
        return $this->paymentMethod;
    }

    /**
     * Sets Payment Method.
     *
     * @maps PaymentMethod
     */
    public function setPaymentMethod(?PaymentMethodData $paymentMethod): void
    {
        $this->paymentMethod = $paymentMethod;
    }

    /**
     * Returns Installments.
     *
     * @return InstallmentItem[]|null
     */
    public function getInstallments(): ?array
    {
        return $this->installments;
    }

    /**
     * Sets Installments.
     *
     * @maps Installments
     *
     * @param InstallmentItem[]|null $installments
     */
    public function setInstallments(?array $installments): void
    {
        $this->installments = $installments;
    }

    /**
     * Returns Refunds.
     *
     * @return RefundItem[]|null
     */
    public function getRefunds(): ?array
    {
        return $this->refunds;
    }

    /**
     * Sets Refunds.
     *
     * @maps Refunds
     *
     * @param RefundItem[]|null $refunds
     */
    public function setRefunds(?array $refunds): void
    {
        $this->refunds = $refunds;
    }

    /**
     * Returns Links.
     *
     * @return PlanLinksData[]|null
     */
    public function getLinks(): ?array
    {
        return $this->links;
    }

    /**
     * Sets Links.
     *
     * @maps Links
     *
     * @param PlanLinksData[]|null $links
     */
    public function setLinks(?array $links): void
    {
        $this->links = $links;
    }

    /**
     * Returns Metadata.
     *
     * @return MetadataItem[]|null
     */
    public function getMetadata(): ?array
    {
        return $this->metadata;
    }

    /**
     * Sets Metadata.
     *
     * @maps Metadata
     *
     * @param MetadataItem[]|null $metadata
     */
    public function setMetadata(?array $metadata): void
    {
        $this->metadata = $metadata;
    }

    /**
     * Converts the InstallmentPlanDetailsResponse object to a human-readable string representation.
     *
     * @return string The string representation of the InstallmentPlanDetailsResponse object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'InstallmentPlanDetailsResponse',
            [
                'dateCreated' => $this->dateCreated,
                'status' => $this->status,
                'installmentPlanNumber' => $this->installmentPlanNumber,
                'merchantOrderReference' => $this->merchantOrderReference,
                'installmentProvider' => $this->installmentProvider,
                'purchaseMethod' => $this->purchaseMethod,
                'currency' => $this->currency,
                'purchaseAmount' => $this->purchaseAmount,
                'totalAmount' => $this->totalAmount,
                'totalFees' => $this->totalFees,
                'apr' => $this->apr,
                'authorization' => $this->authorization,
                'shopperDetails' => $this->shopperDetails,
                'paymentMethod' => $this->paymentMethod,
                'installments' => $this->installments,
                'refunds' => $this->refunds,
                'links' => $this->links,
                'metadata' => $this->metadata
            ]
        );
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        $json['DateCreated']                = DateTimeHelper::toRfc3339DateTime($this->dateCreated);
        $json['Status']                     = InstallmentPlanStatusEnum::checkValue($this->status);
        if (isset($this->installmentPlanNumber)) {
            $json['InstallmentPlanNumber']  = $this->installmentPlanNumber;
        }
        if (isset($this->merchantOrderReference)) {
            $json['MerchantOrderReference'] = $this->merchantOrderReference;
        }
        $json['InstallmentProvider']        = ExternalProviderTypesEnum::checkValue($this->installmentProvider);
        $json['PurchaseMethod']             = PurchaseMethodEnum::checkValue($this->purchaseMethod);
        if (isset($this->currency)) {
            $json['Currency']               = $this->currency;
        }
        $json['PurchaseAmount']             = $this->purchaseAmount;
        $json['TotalAmount']                = $this->totalAmount;
        $json['TotalFees']                  = $this->totalFees;
        if (isset($this->apr)) {
            $json['Apr']                    = $this->apr;
        }
        if (isset($this->authorization)) {
            $json['Authorization']          = $this->authorization;
        }
        if (isset($this->shopperDetails)) {
            $json['ShopperDetails']         = $this->shopperDetails;
        }
        if (isset($this->paymentMethod)) {
            $json['PaymentMethod']          = $this->paymentMethod;
        }
        if (isset($this->installments)) {
            $json['Installments']           = $this->installments;
        }
        if (isset($this->refunds)) {
            $json['Refunds']                = $this->refunds;
        }
        if (isset($this->links)) {
            $json['Links']                  = $this->links;
        }
        if (isset($this->metadata)) {
            $json['Metadata']               = $this->metadata;
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
