<?php

declare(strict_types=1);

/*
 * SplititWebApiV4Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SplititWebApiV4Lib\Models;

use SplititWebApiV4Lib\ApiHelper;
use stdClass;

class MaskedCardDetails implements \JsonSerializable
{
    /**
     * @var string|null
     */
    private $last4Digits;

    /**
     * @var string|null
     */
    private $bIN;

    /**
     * @var string|null
     */
    private $issuerName;

    /**
     * Returns Last 4 Digits.
     */
    public function getLast4Digits(): ?string
    {
        return $this->last4Digits;
    }

    /**
     * Sets Last 4 Digits.
     *
     * @maps Last4Digits
     */
    public function setLast4Digits(?string $last4Digits): void
    {
        $this->last4Digits = $last4Digits;
    }

    /**
     * Returns B IN.
     */
    public function getBIN(): ?string
    {
        return $this->bIN;
    }

    /**
     * Sets B IN.
     *
     * @maps BIN
     */
    public function setBIN(?string $bIN): void
    {
        $this->bIN = $bIN;
    }

    /**
     * Returns Issuer Name.
     */
    public function getIssuerName(): ?string
    {
        return $this->issuerName;
    }

    /**
     * Sets Issuer Name.
     *
     * @maps IssuerName
     */
    public function setIssuerName(?string $issuerName): void
    {
        $this->issuerName = $issuerName;
    }

    /**
     * Converts the MaskedCardDetails object to a human-readable string representation.
     *
     * @return string The string representation of the MaskedCardDetails object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'MaskedCardDetails',
            ['last4Digits' => $this->last4Digits, 'bIN' => $this->bIN, 'issuerName' => $this->issuerName]
        );
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->last4Digits)) {
            $json['Last4Digits'] = $this->last4Digits;
        }
        if (isset($this->bIN)) {
            $json['BIN']         = $this->bIN;
        }
        if (isset($this->issuerName)) {
            $json['IssuerName']  = $this->issuerName;
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
