<?php

declare(strict_types=1);

/*
 * SplititWebApiV4Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SplititWebApiV4Lib\Models;

use SplititWebApiV4Lib\ApiHelper;
use SplititWebApiV4Lib\Utils\DateTimeHelper;
use stdClass;

class OffersResponse implements \JsonSerializable
{
    /**
     * @var string|null
     */
    private $installmentPlanNumber;

    /**
     * @var string|null
     */
    private $merchantOrderReference;

    /**
     * @var string
     */
    private $purchaseMethod;

    /**
     * @var float
     */
    private $purchaseAmount;

    /**
     * @var string|null
     */
    private $currency;

    /**
     * @var OffersPaymentMethodResponse|null
     */
    private $paymentMethod;

    /**
     * @var OfferItem[]|null
     */
    private $offers;

    /**
     * @var \DateTime|null
     */
    private $validUntil;

    /**
     * @param string $purchaseMethod
     * @param float $purchaseAmount
     */
    public function __construct(string $purchaseMethod, float $purchaseAmount)
    {
        $this->purchaseMethod = $purchaseMethod;
        $this->purchaseAmount = $purchaseAmount;
    }

    /**
     * Returns Installment Plan Number.
     */
    public function getInstallmentPlanNumber(): ?string
    {
        return $this->installmentPlanNumber;
    }

    /**
     * Sets Installment Plan Number.
     *
     * @maps InstallmentPlanNumber
     */
    public function setInstallmentPlanNumber(?string $installmentPlanNumber): void
    {
        $this->installmentPlanNumber = $installmentPlanNumber;
    }

    /**
     * Returns Merchant Order Reference.
     */
    public function getMerchantOrderReference(): ?string
    {
        return $this->merchantOrderReference;
    }

    /**
     * Sets Merchant Order Reference.
     *
     * @maps MerchantOrderReference
     */
    public function setMerchantOrderReference(?string $merchantOrderReference): void
    {
        $this->merchantOrderReference = $merchantOrderReference;
    }

    /**
     * Returns Purchase Method.
     */
    public function getPurchaseMethod(): string
    {
        return $this->purchaseMethod;
    }

    /**
     * Sets Purchase Method.
     *
     * @required
     * @maps PurchaseMethod
     * @factory \SplititWebApiV4Lib\Models\PurchaseMethodEnum::checkValue
     */
    public function setPurchaseMethod(string $purchaseMethod): void
    {
        $this->purchaseMethod = $purchaseMethod;
    }

    /**
     * Returns Purchase Amount.
     */
    public function getPurchaseAmount(): float
    {
        return $this->purchaseAmount;
    }

    /**
     * Sets Purchase Amount.
     *
     * @required
     * @maps PurchaseAmount
     */
    public function setPurchaseAmount(float $purchaseAmount): void
    {
        $this->purchaseAmount = $purchaseAmount;
    }

    /**
     * Returns Currency.
     */
    public function getCurrency(): ?string
    {
        return $this->currency;
    }

    /**
     * Sets Currency.
     *
     * @maps Currency
     */
    public function setCurrency(?string $currency): void
    {
        $this->currency = $currency;
    }

    /**
     * Returns Payment Method.
     */
    public function getPaymentMethod(): ?OffersPaymentMethodResponse
    {
        return $this->paymentMethod;
    }

    /**
     * Sets Payment Method.
     *
     * @maps PaymentMethod
     */
    public function setPaymentMethod(?OffersPaymentMethodResponse $paymentMethod): void
    {
        $this->paymentMethod = $paymentMethod;
    }

    /**
     * Returns Offers.
     *
     * @return OfferItem[]|null
     */
    public function getOffers(): ?array
    {
        return $this->offers;
    }

    /**
     * Sets Offers.
     *
     * @maps Offers
     *
     * @param OfferItem[]|null $offers
     */
    public function setOffers(?array $offers): void
    {
        $this->offers = $offers;
    }

    /**
     * Returns Valid Until.
     */
    public function getValidUntil(): ?\DateTime
    {
        return $this->validUntil;
    }

    /**
     * Sets Valid Until.
     *
     * @maps ValidUntil
     * @factory \SplititWebApiV4Lib\Utils\DateTimeHelper::fromRfc3339DateTime
     */
    public function setValidUntil(?\DateTime $validUntil): void
    {
        $this->validUntil = $validUntil;
    }

    /**
     * Converts the OffersResponse object to a human-readable string representation.
     *
     * @return string The string representation of the OffersResponse object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'OffersResponse',
            [
                'installmentPlanNumber' => $this->installmentPlanNumber,
                'merchantOrderReference' => $this->merchantOrderReference,
                'purchaseMethod' => $this->purchaseMethod,
                'purchaseAmount' => $this->purchaseAmount,
                'currency' => $this->currency,
                'paymentMethod' => $this->paymentMethod,
                'offers' => $this->offers,
                'validUntil' => $this->validUntil
            ]
        );
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->installmentPlanNumber)) {
            $json['InstallmentPlanNumber']  = $this->installmentPlanNumber;
        }
        if (isset($this->merchantOrderReference)) {
            $json['MerchantOrderReference'] = $this->merchantOrderReference;
        }
        $json['PurchaseMethod']             = PurchaseMethodEnum::checkValue($this->purchaseMethod);
        $json['PurchaseAmount']             = $this->purchaseAmount;
        if (isset($this->currency)) {
            $json['Currency']               = $this->currency;
        }
        if (isset($this->paymentMethod)) {
            $json['PaymentMethod']          = $this->paymentMethod;
        }
        if (isset($this->offers)) {
            $json['Offers']                 = $this->offers;
        }
        if (isset($this->validUntil)) {
            $json['ValidUntil']             = DateTimeHelper::toRfc3339DateTime($this->validUntil);
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
