<?php

declare(strict_types=1);

/*
 * SplititWebApiV4Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SplititWebApiV4Lib\Models;

use SplititWebApiV4Lib\ApiHelper;
use stdClass;

class OffersMerchantDetails implements \JsonSerializable
{
    /**
     * @var string|null
     */
    private $storeName;

    /**
     * @var string|null
     */
    private $storeId;

    /**
     * @var OffersStoreLocation
     */
    private $storeLocation;

    /**
     * @param OffersStoreLocation $storeLocation
     */
    public function __construct(OffersStoreLocation $storeLocation)
    {
        $this->storeLocation = $storeLocation;
    }

    /**
     * Returns Store Name.
     */
    public function getStoreName(): ?string
    {
        return $this->storeName;
    }

    /**
     * Sets Store Name.
     *
     * @maps StoreName
     */
    public function setStoreName(?string $storeName): void
    {
        $this->storeName = $storeName;
    }

    /**
     * Returns Store Id.
     */
    public function getStoreId(): ?string
    {
        return $this->storeId;
    }

    /**
     * Sets Store Id.
     *
     * @maps StoreId
     */
    public function setStoreId(?string $storeId): void
    {
        $this->storeId = $storeId;
    }

    /**
     * Returns Store Location.
     */
    public function getStoreLocation(): OffersStoreLocation
    {
        return $this->storeLocation;
    }

    /**
     * Sets Store Location.
     *
     * @required
     * @maps StoreLocation
     */
    public function setStoreLocation(OffersStoreLocation $storeLocation): void
    {
        $this->storeLocation = $storeLocation;
    }

    /**
     * Converts the OffersMerchantDetails object to a human-readable string representation.
     *
     * @return string The string representation of the OffersMerchantDetails object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'OffersMerchantDetails',
            ['storeName' => $this->storeName, 'storeId' => $this->storeId, 'storeLocation' => $this->storeLocation]
        );
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->storeName)) {
            $json['StoreName'] = $this->storeName;
        }
        if (isset($this->storeId)) {
            $json['StoreId']   = $this->storeId;
        }
        $json['StoreLocation'] = $this->storeLocation;

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
