<?php

declare(strict_types=1);

/*
 * SplititWebApiV4Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SplititWebApiV4Lib\Models;

use SplititWebApiV4Lib\ApiHelper;
use stdClass;

class OffersPaymentMethod implements \JsonSerializable
{
    /**
     * @var string
     */
    private $type;

    /**
     * @var OffersCardDetails
     */
    private $cardDetails;

    /**
     * @param OffersCardDetails $cardDetails
     */
    public function __construct(OffersCardDetails $cardDetails)
    {
        $this->cardDetails = $cardDetails;
    }

    /**
     * Returns Type.
     */
    public function getType(): string
    {
        return $this->type;
    }

    /**
     * Sets Type.
     *
     * @maps Type
     */
    public function setType(string $type): void
    {
        $this->type = $type;
    }

    /**
     * Returns Card Details.
     */
    public function getCardDetails(): OffersCardDetails
    {
        return $this->cardDetails;
    }

    /**
     * Sets Card Details.
     *
     * @required
     * @maps CardDetails
     */
    public function setCardDetails(OffersCardDetails $cardDetails): void
    {
        $this->cardDetails = $cardDetails;
    }

    /**
     * Converts the OffersPaymentMethod object to a human-readable string representation.
     *
     * @return string The string representation of the OffersPaymentMethod object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'OffersPaymentMethod',
            ['type' => $this->type, 'cardDetails' => $this->cardDetails]
        );
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        $json['Type']        = $this->type;
        $json['CardDetails'] = $this->cardDetails;

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
