<?php

declare(strict_types=1);

/*
 * SplititWebApiV4Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SplititWebApiV4Lib\Models;

use SplititWebApiV4Lib\ApiHelper;
use stdClass;

class OffersShopperDetails implements \JsonSerializable
{
    /**
     * @var string|null
     */
    private $firstName;

    /**
     * @var string
     */
    private $lastName;

    /**
     * @var string
     */
    private $email;

    /**
     * @var string|null
     */
    private $phoneNumber;

    /**
     * @var string|null
     */
    private $shopperLocale;

    /**
     * @var OffersBillingAddress|null
     */
    private $billingAddress;

    /**
     * @param string $lastName
     * @param string $email
     */
    public function __construct(string $lastName, string $email)
    {
        $this->lastName = $lastName;
        $this->email = $email;
    }

    /**
     * Returns First Name.
     */
    public function getFirstName(): ?string
    {
        return $this->firstName;
    }

    /**
     * Sets First Name.
     *
     * @maps FirstName
     */
    public function setFirstName(?string $firstName): void
    {
        $this->firstName = $firstName;
    }

    /**
     * Returns Last Name.
     */
    public function getLastName(): string
    {
        return $this->lastName;
    }

    /**
     * Sets Last Name.
     *
     * @required
     * @maps LastName
     */
    public function setLastName(string $lastName): void
    {
        $this->lastName = $lastName;
    }

    /**
     * Returns Email.
     */
    public function getEmail(): string
    {
        return $this->email;
    }

    /**
     * Sets Email.
     *
     * @required
     * @maps Email
     */
    public function setEmail(string $email): void
    {
        $this->email = $email;
    }

    /**
     * Returns Phone Number.
     */
    public function getPhoneNumber(): ?string
    {
        return $this->phoneNumber;
    }

    /**
     * Sets Phone Number.
     *
     * @maps PhoneNumber
     */
    public function setPhoneNumber(?string $phoneNumber): void
    {
        $this->phoneNumber = $phoneNumber;
    }

    /**
     * Returns Shopper Locale.
     */
    public function getShopperLocale(): ?string
    {
        return $this->shopperLocale;
    }

    /**
     * Sets Shopper Locale.
     *
     * @maps ShopperLocale
     */
    public function setShopperLocale(?string $shopperLocale): void
    {
        $this->shopperLocale = $shopperLocale;
    }

    /**
     * Returns Billing Address.
     */
    public function getBillingAddress(): ?OffersBillingAddress
    {
        return $this->billingAddress;
    }

    /**
     * Sets Billing Address.
     *
     * @maps BillingAddress
     */
    public function setBillingAddress(?OffersBillingAddress $billingAddress): void
    {
        $this->billingAddress = $billingAddress;
    }

    /**
     * Converts the OffersShopperDetails object to a human-readable string representation.
     *
     * @return string The string representation of the OffersShopperDetails object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'OffersShopperDetails',
            [
                'firstName' => $this->firstName,
                'lastName' => $this->lastName,
                'email' => $this->email,
                'phoneNumber' => $this->phoneNumber,
                'shopperLocale' => $this->shopperLocale,
                'billingAddress' => $this->billingAddress
            ]
        );
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->firstName)) {
            $json['FirstName']      = $this->firstName;
        }
        $json['LastName']           = $this->lastName;
        $json['Email']              = $this->email;
        if (isset($this->phoneNumber)) {
            $json['PhoneNumber']    = $this->phoneNumber;
        }
        if (isset($this->shopperLocale)) {
            $json['ShopperLocale']  = $this->shopperLocale;
        }
        if (isset($this->billingAddress)) {
            $json['BillingAddress'] = $this->billingAddress;
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
