<?php

declare(strict_types=1);

/*
 * SplititWebApiV4Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SplititWebApiV4Lib\Models;

use SplititWebApiV4Lib\ApiHelper;
use stdClass;

class OffersRequest implements \JsonSerializable
{
    /**
     * @var string|null
     */
    private $merchantOrderReference;

    /**
     * @var string
     */
    private $purchaseMethod;

    /**
     * @var string
     */
    private $purchaseAmount;

    /**
     * @var string
     */
    private $currency;

    /**
     * @var OffersShopperDetails
     */
    private $shopperDetails;

    /**
     * @var OffersPaymentMethod
     */
    private $paymentMethod;

    /**
     * @var OffersMerchantDetails|null
     */
    private $merchantDetails;

    /**
     * @var MetadataItem[]|null
     */
    private $metadata;

    /**
     * @param string $purchaseMethod
     * @param string $purchaseAmount
     * @param string $currency
     * @param OffersShopperDetails $shopperDetails
     * @param OffersPaymentMethod $paymentMethod
     */
    public function __construct(
        string $purchaseMethod,
        string $purchaseAmount,
        string $currency,
        OffersShopperDetails $shopperDetails,
        OffersPaymentMethod $paymentMethod
    ) {
        $this->purchaseMethod = $purchaseMethod;
        $this->purchaseAmount = $purchaseAmount;
        $this->currency = $currency;
        $this->shopperDetails = $shopperDetails;
        $this->paymentMethod = $paymentMethod;
    }

    /**
     * Returns Merchant Order Reference.
     */
    public function getMerchantOrderReference(): ?string
    {
        return $this->merchantOrderReference;
    }

    /**
     * Sets Merchant Order Reference.
     *
     * @maps MerchantOrderReference
     */
    public function setMerchantOrderReference(?string $merchantOrderReference): void
    {
        $this->merchantOrderReference = $merchantOrderReference;
    }

    /**
     * Returns Purchase Method.
     */
    public function getPurchaseMethod(): string
    {
        return $this->purchaseMethod;
    }

    /**
     * Sets Purchase Method.
     *
     * @required
     * @maps PurchaseMethod
     * @factory \SplititWebApiV4Lib\Models\PurchaseMethodEnum::checkValue
     */
    public function setPurchaseMethod(string $purchaseMethod): void
    {
        $this->purchaseMethod = $purchaseMethod;
    }

    /**
     * Returns Purchase Amount.
     */
    public function getPurchaseAmount(): string
    {
        return $this->purchaseAmount;
    }

    /**
     * Sets Purchase Amount.
     *
     * @required
     * @maps PurchaseAmount
     */
    public function setPurchaseAmount(string $purchaseAmount): void
    {
        $this->purchaseAmount = $purchaseAmount;
    }

    /**
     * Returns Currency.
     */
    public function getCurrency(): string
    {
        return $this->currency;
    }

    /**
     * Sets Currency.
     *
     * @required
     * @maps Currency
     */
    public function setCurrency(string $currency): void
    {
        $this->currency = $currency;
    }

    /**
     * Returns Shopper Details.
     */
    public function getShopperDetails(): OffersShopperDetails
    {
        return $this->shopperDetails;
    }

    /**
     * Sets Shopper Details.
     *
     * @required
     * @maps ShopperDetails
     */
    public function setShopperDetails(OffersShopperDetails $shopperDetails): void
    {
        $this->shopperDetails = $shopperDetails;
    }

    /**
     * Returns Payment Method.
     */
    public function getPaymentMethod(): OffersPaymentMethod
    {
        return $this->paymentMethod;
    }

    /**
     * Sets Payment Method.
     *
     * @required
     * @maps PaymentMethod
     */
    public function setPaymentMethod(OffersPaymentMethod $paymentMethod): void
    {
        $this->paymentMethod = $paymentMethod;
    }

    /**
     * Returns Merchant Details.
     */
    public function getMerchantDetails(): ?OffersMerchantDetails
    {
        return $this->merchantDetails;
    }

    /**
     * Sets Merchant Details.
     *
     * @maps MerchantDetails
     */
    public function setMerchantDetails(?OffersMerchantDetails $merchantDetails): void
    {
        $this->merchantDetails = $merchantDetails;
    }

    /**
     * Returns Metadata.
     *
     * @return MetadataItem[]|null
     */
    public function getMetadata(): ?array
    {
        return $this->metadata;
    }

    /**
     * Sets Metadata.
     *
     * @maps Metadata
     *
     * @param MetadataItem[]|null $metadata
     */
    public function setMetadata(?array $metadata): void
    {
        $this->metadata = $metadata;
    }

    /**
     * Converts the OffersRequest object to a human-readable string representation.
     *
     * @return string The string representation of the OffersRequest object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'OffersRequest',
            [
                'merchantOrderReference' => $this->merchantOrderReference,
                'purchaseMethod' => $this->purchaseMethod,
                'purchaseAmount' => $this->purchaseAmount,
                'currency' => $this->currency,
                'shopperDetails' => $this->shopperDetails,
                'paymentMethod' => $this->paymentMethod,
                'merchantDetails' => $this->merchantDetails,
                'metadata' => $this->metadata
            ]
        );
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->merchantOrderReference)) {
            $json['MerchantOrderReference'] = $this->merchantOrderReference;
        }
        $json['PurchaseMethod']             = PurchaseMethodEnum::checkValue($this->purchaseMethod);
        $json['PurchaseAmount']             = $this->purchaseAmount;
        $json['Currency']                   = $this->currency;
        $json['ShopperDetails']             = $this->shopperDetails;
        $json['PaymentMethod']              = $this->paymentMethod;
        if (isset($this->merchantDetails)) {
            $json['MerchantDetails']        = $this->merchantDetails;
        }
        if (isset($this->metadata)) {
            $json['Metadata']               = $this->metadata;
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
