<?php

declare(strict_types=1);

/*
 * SplititWebApiV4Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SplititWebApiV4Lib\Models;

use SplititWebApiV4Lib\ApiHelper;
use stdClass;

class OfferItem implements \JsonSerializable
{
    /**
     * @var string|null
     */
    private $offerId;

    /**
     * @var AprData|null
     */
    private $apr;

    /**
     * @var string|null
     */
    private $currency;

    /**
     * @var float
     */
    private $totalAmount;

    /**
     * @var float
     */
    private $totalFees;

    /**
     * @var int
     */
    private $numberOfInstallments;

    /**
     * @var string|null
     */
    private $frequency;

    /**
     * @var float
     */
    private $installmentAmount;

    /**
     * @var float
     */
    private $firstInstallmentAmount;

    /**
     * @var AmountData|null
     */
    private $lastInstallmentAmount;

    /**
     * @var InlineContent|null
     */
    private $inlineContent;

    /**
     * @param float $totalAmount
     * @param float $totalFees
     * @param int $numberOfInstallments
     * @param float $installmentAmount
     * @param float $firstInstallmentAmount
     */
    public function __construct(
        float $totalAmount,
        float $totalFees,
        int $numberOfInstallments,
        float $installmentAmount,
        float $firstInstallmentAmount
    ) {
        $this->totalAmount = $totalAmount;
        $this->totalFees = $totalFees;
        $this->numberOfInstallments = $numberOfInstallments;
        $this->installmentAmount = $installmentAmount;
        $this->firstInstallmentAmount = $firstInstallmentAmount;
    }

    /**
     * Returns Offer Id.
     */
    public function getOfferId(): ?string
    {
        return $this->offerId;
    }

    /**
     * Sets Offer Id.
     *
     * @maps OfferId
     */
    public function setOfferId(?string $offerId): void
    {
        $this->offerId = $offerId;
    }

    /**
     * Returns Apr.
     */
    public function getApr(): ?AprData
    {
        return $this->apr;
    }

    /**
     * Sets Apr.
     *
     * @maps Apr
     */
    public function setApr(?AprData $apr): void
    {
        $this->apr = $apr;
    }

    /**
     * Returns Currency.
     */
    public function getCurrency(): ?string
    {
        return $this->currency;
    }

    /**
     * Sets Currency.
     *
     * @maps Currency
     */
    public function setCurrency(?string $currency): void
    {
        $this->currency = $currency;
    }

    /**
     * Returns Total Amount.
     */
    public function getTotalAmount(): float
    {
        return $this->totalAmount;
    }

    /**
     * Sets Total Amount.
     *
     * @required
     * @maps TotalAmount
     */
    public function setTotalAmount(float $totalAmount): void
    {
        $this->totalAmount = $totalAmount;
    }

    /**
     * Returns Total Fees.
     */
    public function getTotalFees(): float
    {
        return $this->totalFees;
    }

    /**
     * Sets Total Fees.
     *
     * @required
     * @maps TotalFees
     */
    public function setTotalFees(float $totalFees): void
    {
        $this->totalFees = $totalFees;
    }

    /**
     * Returns Number of Installments.
     */
    public function getNumberOfInstallments(): int
    {
        return $this->numberOfInstallments;
    }

    /**
     * Sets Number of Installments.
     *
     * @required
     * @maps NumberOfInstallments
     */
    public function setNumberOfInstallments(int $numberOfInstallments): void
    {
        $this->numberOfInstallments = $numberOfInstallments;
    }

    /**
     * Returns Frequency.
     */
    public function getFrequency(): ?string
    {
        return $this->frequency;
    }

    /**
     * Sets Frequency.
     *
     * @maps Frequency
     */
    public function setFrequency(?string $frequency): void
    {
        $this->frequency = $frequency;
    }

    /**
     * Returns Installment Amount.
     */
    public function getInstallmentAmount(): float
    {
        return $this->installmentAmount;
    }

    /**
     * Sets Installment Amount.
     *
     * @required
     * @maps InstallmentAmount
     */
    public function setInstallmentAmount(float $installmentAmount): void
    {
        $this->installmentAmount = $installmentAmount;
    }

    /**
     * Returns First Installment Amount.
     */
    public function getFirstInstallmentAmount(): float
    {
        return $this->firstInstallmentAmount;
    }

    /**
     * Sets First Installment Amount.
     *
     * @required
     * @maps FirstInstallmentAmount
     */
    public function setFirstInstallmentAmount(float $firstInstallmentAmount): void
    {
        $this->firstInstallmentAmount = $firstInstallmentAmount;
    }

    /**
     * Returns Last Installment Amount.
     */
    public function getLastInstallmentAmount(): ?AmountData
    {
        return $this->lastInstallmentAmount;
    }

    /**
     * Sets Last Installment Amount.
     *
     * @maps LastInstallmentAmount
     */
    public function setLastInstallmentAmount(?AmountData $lastInstallmentAmount): void
    {
        $this->lastInstallmentAmount = $lastInstallmentAmount;
    }

    /**
     * Returns Inline Content.
     */
    public function getInlineContent(): ?InlineContent
    {
        return $this->inlineContent;
    }

    /**
     * Sets Inline Content.
     *
     * @maps InlineContent
     */
    public function setInlineContent(?InlineContent $inlineContent): void
    {
        $this->inlineContent = $inlineContent;
    }

    /**
     * Converts the OfferItem object to a human-readable string representation.
     *
     * @return string The string representation of the OfferItem object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'OfferItem',
            [
                'offerId' => $this->offerId,
                'apr' => $this->apr,
                'currency' => $this->currency,
                'totalAmount' => $this->totalAmount,
                'totalFees' => $this->totalFees,
                'numberOfInstallments' => $this->numberOfInstallments,
                'frequency' => $this->frequency,
                'installmentAmount' => $this->installmentAmount,
                'firstInstallmentAmount' => $this->firstInstallmentAmount,
                'lastInstallmentAmount' => $this->lastInstallmentAmount,
                'inlineContent' => $this->inlineContent
            ]
        );
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->offerId)) {
            $json['OfferId']               = $this->offerId;
        }
        if (isset($this->apr)) {
            $json['Apr']                   = $this->apr;
        }
        if (isset($this->currency)) {
            $json['Currency']              = $this->currency;
        }
        $json['TotalAmount']               = $this->totalAmount;
        $json['TotalFees']                 = $this->totalFees;
        $json['NumberOfInstallments']      = $this->numberOfInstallments;
        if (isset($this->frequency)) {
            $json['Frequency']             = $this->frequency;
        }
        $json['InstallmentAmount']         = $this->installmentAmount;
        $json['FirstInstallmentAmount']    = $this->firstInstallmentAmount;
        if (isset($this->lastInstallmentAmount)) {
            $json['LastInstallmentAmount'] = $this->lastInstallmentAmount;
        }
        if (isset($this->inlineContent)) {
            $json['InlineContent']         = $this->inlineContent;
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
