<?php

declare(strict_types=1);

/*
 * SplititWebApiV4Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SplititWebApiV4Lib\Models;

use SplititWebApiV4Lib\ApiHelper;
use stdClass;

class PaymentLinkResponse implements \JsonSerializable
{
    /**
     * @var CheckoutUrlData|null
     */
    private $checkoutUrl;

    /**
     * @var string|null
     */
    private $installmentPlanNumber;

    /**
     * @var string|null
     */
    private $merchantOrderReference;

    /**
     * @var float
     */
    private $purchaseAmount;

    /**
     * @var string|null
     */
    private $currency;

    /**
     * @param float $purchaseAmount
     */
    public function __construct(float $purchaseAmount)
    {
        $this->purchaseAmount = $purchaseAmount;
    }

    /**
     * Returns Checkout Url.
     */
    public function getCheckoutUrl(): ?CheckoutUrlData
    {
        return $this->checkoutUrl;
    }

    /**
     * Sets Checkout Url.
     *
     * @maps CheckoutUrl
     */
    public function setCheckoutUrl(?CheckoutUrlData $checkoutUrl): void
    {
        $this->checkoutUrl = $checkoutUrl;
    }

    /**
     * Returns Installment Plan Number.
     */
    public function getInstallmentPlanNumber(): ?string
    {
        return $this->installmentPlanNumber;
    }

    /**
     * Sets Installment Plan Number.
     *
     * @maps InstallmentPlanNumber
     */
    public function setInstallmentPlanNumber(?string $installmentPlanNumber): void
    {
        $this->installmentPlanNumber = $installmentPlanNumber;
    }

    /**
     * Returns Merchant Order Reference.
     */
    public function getMerchantOrderReference(): ?string
    {
        return $this->merchantOrderReference;
    }

    /**
     * Sets Merchant Order Reference.
     *
     * @maps MerchantOrderReference
     */
    public function setMerchantOrderReference(?string $merchantOrderReference): void
    {
        $this->merchantOrderReference = $merchantOrderReference;
    }

    /**
     * Returns Purchase Amount.
     */
    public function getPurchaseAmount(): float
    {
        return $this->purchaseAmount;
    }

    /**
     * Sets Purchase Amount.
     *
     * @required
     * @maps PurchaseAmount
     */
    public function setPurchaseAmount(float $purchaseAmount): void
    {
        $this->purchaseAmount = $purchaseAmount;
    }

    /**
     * Returns Currency.
     */
    public function getCurrency(): ?string
    {
        return $this->currency;
    }

    /**
     * Sets Currency.
     *
     * @maps Currency
     */
    public function setCurrency(?string $currency): void
    {
        $this->currency = $currency;
    }

    /**
     * Converts the PaymentLinkResponse object to a human-readable string representation.
     *
     * @return string The string representation of the PaymentLinkResponse object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'PaymentLinkResponse',
            [
                'checkoutUrl' => $this->checkoutUrl,
                'installmentPlanNumber' => $this->installmentPlanNumber,
                'merchantOrderReference' => $this->merchantOrderReference,
                'purchaseAmount' => $this->purchaseAmount,
                'currency' => $this->currency
            ]
        );
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->checkoutUrl)) {
            $json['CheckoutUrl']            = $this->checkoutUrl;
        }
        if (isset($this->installmentPlanNumber)) {
            $json['InstallmentPlanNumber']  = $this->installmentPlanNumber;
        }
        if (isset($this->merchantOrderReference)) {
            $json['MerchantOrderReference'] = $this->merchantOrderReference;
        }
        $json['PurchaseAmount']             = $this->purchaseAmount;
        if (isset($this->currency)) {
            $json['Currency']               = $this->currency;
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
