<?php

declare(strict_types=1);

/*
 * SplititWebApiV4Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SplititWebApiV4Lib\Models;

use SplititWebApiV4Lib\ApiHelper;
use SplititWebApiV4Lib\Utils\DateTimeHelper;
use stdClass;

class PaymentLinkRequest implements \JsonSerializable
{
    /**
     * @var string
     */
    private $amount;

    /**
     * @var string
     */
    private $currency;

    /**
     * @var bool|null
     */
    private $autoCapture;

    /**
     * @var string|null
     */
    private $merchantOrderReference;

    /**
     * @var string
     */
    private $purchaseMethod;

    /**
     * @var OffersShopperDetails
     */
    private $shopperDetails;

    /**
     * @var OffersMerchantDetails|null
     */
    private $merchantDetails;

    /**
     * @var \DateTime|null
     */
    private $checkoutUrlValidity;

    /**
     * @var MetadataItem[]|null
     */
    private $metadata;

    /**
     * @var RedirectUrls|null
     */
    private $redirectUrls;

    /**
     * @var ProcessingData|null
     */
    private $processingData;

    /**
     * @var ThreeDSExecute|null
     */
    private $threeDS;

    /**
     * @param string $amount
     * @param string $currency
     * @param string $purchaseMethod
     * @param OffersShopperDetails $shopperDetails
     */
    public function __construct(
        string $amount,
        string $currency,
        string $purchaseMethod,
        OffersShopperDetails $shopperDetails
    ) {
        $this->amount = $amount;
        $this->currency = $currency;
        $this->purchaseMethod = $purchaseMethod;
        $this->shopperDetails = $shopperDetails;
    }

    /**
     * Returns Amount.
     */
    public function getAmount(): string
    {
        return $this->amount;
    }

    /**
     * Sets Amount.
     *
     * @required
     * @maps Amount
     */
    public function setAmount(string $amount): void
    {
        $this->amount = $amount;
    }

    /**
     * Returns Currency.
     */
    public function getCurrency(): string
    {
        return $this->currency;
    }

    /**
     * Sets Currency.
     *
     * @required
     * @maps Currency
     */
    public function setCurrency(string $currency): void
    {
        $this->currency = $currency;
    }

    /**
     * Returns Auto Capture.
     */
    public function getAutoCapture(): ?bool
    {
        return $this->autoCapture;
    }

    /**
     * Sets Auto Capture.
     *
     * @maps AutoCapture
     */
    public function setAutoCapture(?bool $autoCapture): void
    {
        $this->autoCapture = $autoCapture;
    }

    /**
     * Returns Merchant Order Reference.
     */
    public function getMerchantOrderReference(): ?string
    {
        return $this->merchantOrderReference;
    }

    /**
     * Sets Merchant Order Reference.
     *
     * @maps MerchantOrderReference
     */
    public function setMerchantOrderReference(?string $merchantOrderReference): void
    {
        $this->merchantOrderReference = $merchantOrderReference;
    }

    /**
     * Returns Purchase Method.
     */
    public function getPurchaseMethod(): string
    {
        return $this->purchaseMethod;
    }

    /**
     * Sets Purchase Method.
     *
     * @required
     * @maps PurchaseMethod
     * @factory \SplititWebApiV4Lib\Models\PurchaseMethodEnum::checkValue
     */
    public function setPurchaseMethod(string $purchaseMethod): void
    {
        $this->purchaseMethod = $purchaseMethod;
    }

    /**
     * Returns Shopper Details.
     */
    public function getShopperDetails(): OffersShopperDetails
    {
        return $this->shopperDetails;
    }

    /**
     * Sets Shopper Details.
     *
     * @required
     * @maps ShopperDetails
     */
    public function setShopperDetails(OffersShopperDetails $shopperDetails): void
    {
        $this->shopperDetails = $shopperDetails;
    }

    /**
     * Returns Merchant Details.
     */
    public function getMerchantDetails(): ?OffersMerchantDetails
    {
        return $this->merchantDetails;
    }

    /**
     * Sets Merchant Details.
     *
     * @maps MerchantDetails
     */
    public function setMerchantDetails(?OffersMerchantDetails $merchantDetails): void
    {
        $this->merchantDetails = $merchantDetails;
    }

    /**
     * Returns Checkout Url Validity.
     */
    public function getCheckoutUrlValidity(): ?\DateTime
    {
        return $this->checkoutUrlValidity;
    }

    /**
     * Sets Checkout Url Validity.
     *
     * @maps CheckoutUrlValidity
     * @factory \SplititWebApiV4Lib\Utils\DateTimeHelper::fromRfc3339DateTime
     */
    public function setCheckoutUrlValidity(?\DateTime $checkoutUrlValidity): void
    {
        $this->checkoutUrlValidity = $checkoutUrlValidity;
    }

    /**
     * Returns Metadata.
     *
     * @return MetadataItem[]|null
     */
    public function getMetadata(): ?array
    {
        return $this->metadata;
    }

    /**
     * Sets Metadata.
     *
     * @maps Metadata
     *
     * @param MetadataItem[]|null $metadata
     */
    public function setMetadata(?array $metadata): void
    {
        $this->metadata = $metadata;
    }

    /**
     * Returns Redirect Urls.
     */
    public function getRedirectUrls(): ?RedirectUrls
    {
        return $this->redirectUrls;
    }

    /**
     * Sets Redirect Urls.
     *
     * @maps RedirectUrls
     */
    public function setRedirectUrls(?RedirectUrls $redirectUrls): void
    {
        $this->redirectUrls = $redirectUrls;
    }

    /**
     * Returns Processing Data.
     */
    public function getProcessingData(): ?ProcessingData
    {
        return $this->processingData;
    }

    /**
     * Sets Processing Data.
     *
     * @maps ProcessingData
     */
    public function setProcessingData(?ProcessingData $processingData): void
    {
        $this->processingData = $processingData;
    }

    /**
     * Returns Three DS.
     */
    public function getThreeDS(): ?ThreeDSExecute
    {
        return $this->threeDS;
    }

    /**
     * Sets Three DS.
     *
     * @maps ThreeDS
     */
    public function setThreeDS(?ThreeDSExecute $threeDS): void
    {
        $this->threeDS = $threeDS;
    }

    /**
     * Converts the PaymentLinkRequest object to a human-readable string representation.
     *
     * @return string The string representation of the PaymentLinkRequest object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'PaymentLinkRequest',
            [
                'amount' => $this->amount,
                'currency' => $this->currency,
                'autoCapture' => $this->autoCapture,
                'merchantOrderReference' => $this->merchantOrderReference,
                'purchaseMethod' => $this->purchaseMethod,
                'shopperDetails' => $this->shopperDetails,
                'merchantDetails' => $this->merchantDetails,
                'checkoutUrlValidity' => $this->checkoutUrlValidity,
                'metadata' => $this->metadata,
                'redirectUrls' => $this->redirectUrls,
                'processingData' => $this->processingData,
                'threeDS' => $this->threeDS
            ]
        );
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        $json['Amount']                     = $this->amount;
        $json['Currency']                   = $this->currency;
        if (isset($this->autoCapture)) {
            $json['AutoCapture']            = $this->autoCapture;
        }
        if (isset($this->merchantOrderReference)) {
            $json['MerchantOrderReference'] = $this->merchantOrderReference;
        }
        $json['PurchaseMethod']             = PurchaseMethodEnum::checkValue($this->purchaseMethod);
        $json['ShopperDetails']             = $this->shopperDetails;
        if (isset($this->merchantDetails)) {
            $json['MerchantDetails']        = $this->merchantDetails;
        }
        if (isset($this->checkoutUrlValidity)) {
            $json['CheckoutUrlValidity']    = DateTimeHelper::toRfc3339DateTime($this->checkoutUrlValidity);
        }
        if (isset($this->metadata)) {
            $json['Metadata']               = $this->metadata;
        }
        if (isset($this->redirectUrls)) {
            $json['RedirectUrls']           = $this->redirectUrls;
        }
        if (isset($this->processingData)) {
            $json['ProcessingData']         = $this->processingData;
        }
        if (isset($this->threeDS)) {
            $json['ThreeDS']                = $this->threeDS;
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
