<?php

declare(strict_types=1);

/*
 * SplititWebApiV4Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SplititWebApiV4Lib\Models;

use SplititWebApiV4Lib\ApiHelper;
use stdClass;

class PaymentMethodData implements \JsonSerializable
{
    /**
     * @var string
     */
    private $type;

    /**
     * @var MaskedCardDetails|null
     */
    private $cardDetails;

    /**
     * @var string|null
     */
    private $par;

    /**
     * Returns Type.
     */
    public function getType(): string
    {
        return $this->type;
    }

    /**
     * Sets Type.
     *
     * @maps Type
     */
    public function setType(string $type): void
    {
        $this->type = $type;
    }

    /**
     * Returns Card Details.
     */
    public function getCardDetails(): ?MaskedCardDetails
    {
        return $this->cardDetails;
    }

    /**
     * Sets Card Details.
     *
     * @maps CardDetails
     */
    public function setCardDetails(?MaskedCardDetails $cardDetails): void
    {
        $this->cardDetails = $cardDetails;
    }

    /**
     * Returns Par.
     */
    public function getPar(): ?string
    {
        return $this->par;
    }

    /**
     * Sets Par.
     *
     * @maps Par
     */
    public function setPar(?string $par): void
    {
        $this->par = $par;
    }

    /**
     * Converts the PaymentMethodData object to a human-readable string representation.
     *
     * @return string The string representation of the PaymentMethodData object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'PaymentMethodData',
            ['type' => $this->type, 'cardDetails' => $this->cardDetails, 'par' => $this->par]
        );
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        $json['Type']            = $this->type;
        if (isset($this->cardDetails)) {
            $json['CardDetails'] = $this->cardDetails;
        }
        if (isset($this->par)) {
            $json['Par']         = $this->par;
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
