<?php

declare(strict_types=1);

/*
 * SplititWebApiV4Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SplititWebApiV4Lib\Models;

use Core\Utils\CoreHelper;
use Exception;
use stdClass;

class PisErrorCodesEnum
{
    public const CONFIGURATIONKEYNOTFOUND = 'ConfigurationKeyNotFound';

    public const IDNOTFOUND = 'IdNotFound';

    public const INVALIDINPUT = 'InvalidInput';

    public const EXTERNALSYSTEMCALLFAILED = 'ExternalSystemCallFailed';

    public const IDEMPOTENCYERROR = 'IdempotencyError';

    public const IDEMPOTENCYORIGINALREQUESTERROR = 'IdempotencyOriginalRequestError';

    public const RULEDATAALREADYEXISTS = 'RuleDataAlreadyExists';

    public const PGPENCRYPTIONKEYNOTFOUND = 'PGPEncryptionKeyNotFound';

    public const INVALIDPGPKEY = 'InvalidPGPKey';

    public const MERCHANTMUSTBEPROVIDED = 'MerchantMustBeProvided';

    public const INVALIDMERCHANTCONFIGURATION = 'InvalidMerchantConfiguration';

    public const INVALIDINSTALLMENTPLANNUMBER = 'InvalidInstallmentPlanNumber';

    public const INVALIDINSTALLMENTPLANSTATUS = 'InvalidInstallmentPlanStatus';

    public const INVALIDCCCARDTYPENOTSUPPORTED = 'InvalidCCCardTypeNotSupported';

    public const INVALIDNUMBEROFINSTALLMENTS = 'InvalidNumberOfInstallments';

    public const INVALIDAMOUNTFORMAT = 'InvalidAmountFormat';

    public const CARDUPDATEISNOTALLOWED = 'CardUpdateIsNotAllowed';

    public const INVALIDCOUNTRYCODE = 'InvalidCountryCode';

    public const INVALIDRESPONSEURL = 'InvalidResponseURL';

    public const INVALIDCARDHOLDERNAME = 'InvalidCardholderName';

    public const INVALIDAMOUNT = 'InvalidAmount';

    public const INVALIDCVV = 'InvalidCVV';

    public const INVALIDCARDNUMBER = 'InvalidCardNumber';

    public const INVALIDEXPIRATIONDATE = 'InvalidExpirationDate';

    public const INVALIDCONSUMERFULLNAME = 'InvalidConsumerFullName';

    public const INVALIDEMAILFORMAT = 'InvalidEmailFormat';

    public const INVALIDADDRESS = 'InvalidAddress';

    public const INVALIDZIPCODE = 'InvalidZIPCode';

    public const INVALIDCCISSUECOUNTRYNOTSUPPORTEDBYTERMINAL = 'InvalidCCIssueCountryNotSupportedByTerminal';

    public const INVALIDCURRENCY = 'InvalidCurrency';

    public const INVALIDMASKEDCCNUMNOTFOUNDINPLAN = 'InvalidMaskedCcNumNotFoundInPlan';

    public const INSTALLMENTPLANISABOUTTOEXPIRE = 'InstallmentPlanIsAboutToExpire';

    public const COUNTRYSUBDIVISIONNOTSUPPORTED = 'CountrySubdivisionNotSupported';

    public const UPDATEINSTALLMENT_WITHHIGHERAMOUNTTHANPERSISTEDISNOTALLOW =
        'UpdateInstallment_WithHigherAmountThanPersistedIsNotAllow';

    public const UPDATEINSTALLMENT_FIRSTINSTALLMENTWITHHIGHERAMOUNTTHANPERSISTEDISNOTALLOW =
        'UpdateInstallment_FirstInstallmentWithHigherAmountThanPersistedIsNotAllow';

    public const UPDATEINSTALLMENT_INTHEMIDDLEOFPLANASZEROISNOTALLOW =
        'UpdateInstallment_InTheMiddleOfPlanAsZeroIsNotAllow';

    public const REFUNDINSTALLMENTWITHHIGHERAMOUNTTHANORIGINALISNOTALLOWED =
        'RefundInstallmentWithHigherAmountThanOriginalIsNotAllowed';

    public const REFUNDINSTALLMENTTHATHASBEENCAPTUREDYETISNOTALLOWED =
        'RefundInstallmentThatHasBeenCapturedYetIsNotAllowed';

    public const UPDATEINSTALLMENT_ALREADYPROCESSED = 'UpdateInstallment_AlreadyProcessed';

    public const APPROVEPLAN_PLANALREADYAPPROVED = 'ApprovePlan_PlanAlreadyApproved';

    public const INVALIDEXPIRATIONDATEFORMAT = 'InvalidExpirationDateFormat';

    public const INVALIDCCBINNOTFOUND = 'InvalidCCBinNotFound';

    public const INVALIDCCCARDBRANDNOTSUPPORTED = 'InvalidCCCardBrandNotSupported';

    public const APPROVEPLAN_NOAPPROVALEVIDENCE = 'ApprovePlan_NoApprovalEvidence';

    public const PLANWITHTHESAMEPAYMENTDATAALREADYBEENCREATEDLATELY =
        'PlanWithTheSamePaymentDataAlreadyBeenCreatedLately';

    public const INVALIDFUTURECHARGEDATE = 'InvalidFutureChargeDate';

    public const INVALIDFIRSTINSTALLMENTAMOUNT = 'InvalidFirstInstallmentAmount';

    public const CULTURENAMENOTVALID = 'CultureNameNotValid';

    public const CULTURENOTSUPPORTED = 'CultureNotSupported';

    public const SYSTEMTEXTKEYNOTFOUND = 'SystemTextKeyNotFound';

    public const TERMINALNOTFOUNDBYSUPPLIEDAPIKEY = 'TerminalNotFoundBySuppliedApiKey';

    public const UNKNOWNZIPCODE = 'UnknownZipCode';

    public const CCREJECTIONPROCESSCANNOTBEINITIATEDDUETOAUTHEXPIRATION =
        'CCRejectionProcessCannotBeInitiatedDueToAuthExpiration';

    public const CANTCHARGEINSTALLMENTWHILEPLANCHARGESAREONHOLD = 'CantChargeInstallmentWhilePlanChargesAreOnHold';

    public const CANTRELEASEHOLDONCHARGESSINCECHARGESARENOTHOLDED = 'CantReleaseHoldOnChargesSinceChargesAreNotHolded';

    public const REFUNDNOTALLOWEDONEORMOREINSTALLMENTSPASSEDREFUNDALLOWEDTIME =
        'RefundNotAllowedOneOrMoreInstallmentsPassedRefundAllowedTime';

    public const REFUNDPARTIALYFAILEDONEORMOREINSTALLMENTFAILEDREFUND =
        'RefundPartialyFailedOneOrMoreInstallmentFailedRefund';

    public const REFUNDFAILED = 'RefundFailed';

    public const UPDATEPLANPARAMETERSARENOTSUPPORTED = 'UpdatePlanParametersAreNotSupported';

    public const REFUNDREQUESTEDAMOUNTEXCEEDEDPLANREFUNDABLEAMOUNT =
        'RefundRequestedAmountExceededPlanRefundableAmount';

    public const INVALIDCURRENCY_NOTSUPPORTEDBYTERMINAL = 'InvalidCurrency_NotSupportedByTerminal';

    public const CREDITCARDISMISSING = 'CreditCardIsMissing';

    public const PISMEMBERISMISSING = 'PisMemberIsMissing';

    public const ADDRESSDATAISMISSINGORPARTIALLYINITIATED = 'AddressDataIsMissingOrPartiallyInitiated';

    public const CARDHOLDERNAMEISMISSING = 'CardHolderNameIsMissing';

    public const CARDNUMBERISMISSING = 'CardNumberIsMissing';

    public const CARDEXPIRATIONMONTHISMISSING = 'CardExpirationMonthIsMissing';

    public const CARDEXPIRATIONYEARISMISSING = 'CardExpirationYearIsMissing';

    public const NUMBEROFINSTALLMENTNOTDEFINED = 'NumberOfInstallmentNotDefined';

    public const INVALIDSTATECODE = 'InvalidStateCode';

    public const EMAILISMISSING = 'EmailIsMissing';

    public const CONSUMERFULLNAMEISMISSING = 'ConsumerFullNameIsMissing';

    public const CURRENCYMUSTBEDEFINEDONTRANSACTION = 'CurrencyMustBeDefinedOnTransaction';

    public const COULDNOTFUNDINSTALLMENTPLAN = 'CouldNotFundInstallmentPlan';

    public const COULDNOTREVERTFUND = 'CouldNotRevertFund';

    public const INVALIDPLANSTRATEGY = 'InvalidPlanStrategy';

    public const FULLCAPTURENOTSUPPORTED = 'FullCaptureNotSupported';

    public const INVALIDCCPREPAIDCARDNOTSUPPORTED = 'InvalidCcPrepaidCardNotSupported';

    public const CARDEXPIREBEFOREPLANENDS = 'CardExpireBeforePlanEnds';

    public const PARTIALPLANAMOUNTAUTHORIZED = 'PartialPlanAmountAuthorized';

    public const SECUREDAUTHORIZATIONREQUIREDFORPARTIALPAYMENT = 'SecuredAuthorizationRequiredForPartialPayment';

    public const THREEDSECUREDATANOTFOUND = 'ThreeDSecureDataNotFound';

    public const THREEDSECURENOTSUPPORTEDBYPLANSTRATEGY = 'ThreeDSecureNotSupportedByPlanStrategy';

    public const THREEDSECUREREQUIREDDATAMISSING = 'ThreeDSecureRequiredDataMissing';

    public const STRATEGYNOTALLOWED = 'StrategyNotAllowed';

    public const PAYMENTTOKENNOTVALID = 'PaymentTokenNotValid';

    public const ACTIVITYNOTSUPPORTEDFORPLANSTRATEGY = 'ActivityNotSupportedForPlanStrategy';

    public const PAYMENTWIZARDVIEWNOTEXIST = 'PaymentWizardViewNotExist';

    public const INVALIDURL = 'InvalidUrl';

    public const ISSUERBINNOTSUPPORTINGINSTALLMENTEXCEPTION = 'IssuerBinNotSupportingInstallmentException';

    public const COULDNOTCHANGELENDER = 'CouldNotChangeLender';

    public const FRAUDDETECED = 'FraudDeteced';

    public const PHONEISMISSING = 'PhoneIsMissing';

    public const INVALIDPHONEFORMAT = 'InvalidPhoneFormat';

    public const INSTALLMENTMISSINGOPENAUTHORIZATION = 'InstallmentMissingOpenAuthorization';

    public const GENERALERROR = 'GeneralError';

    public const GTWYRESULTGENERALERROR = 'GtwyResultGeneralError';

    public const GTWYRESULTCCDATAAVSZIP = 'GtwyResultCCDataAVSZip';

    public const GTWYRESULTCCDATAAVSADDRESS = 'GtwyResultCCDataAVSAddress';

    public const GTWYRESULTCCDATACVV = 'GtwyResultCCDataCVV';

    public const GTWYRESULTCCDATACCEXPIRATION = 'GtwyResultCCDataCCExpiration';

    public const GTWYRESULTCCDATAAVS = 'GtwyResultCCDataAVS';

    public const GTWYRESULTCCDATANUMBER = 'GtwyResultCCDataNumber';

    public const GTWYRESULTCCDATAGENERALPROBLEM = 'GtwyResultCCDataGeneralProblem';

    public const GTWYRESULTCCDATAINSUFFICIENTFUNDS = 'GtwyResultCCDataInsufficientFunds';

    public const GTWYRESULTCCWASDECLINED = 'GtwyResultCCWasDeclined';

    public const GTWYUNAUTHORIZEDCREDENTIALS = 'GtwyUnAuthorizedCredentials';

    public const GTWYCONNECTIVITYPROBLEM = 'GtwyConnectivityProblem';

    public const GTWYMERCHANTDATAPROBLEM = 'GtwyMerchantDataProblem';

    public const GTWYREQUIRE3DAUTHENTICATION = 'GtwyRequire3DAuthentication';

    public const ACTIVEINSTALLMENTPLANSGTWERROR = 'ActiveInstallmentPlansGtwError';

    public const GTWY3DAUTHENTICATIONFAILED = 'Gtwy3DAuthenticationFailed';

    public const GTWYFRAUDDETECTED = 'GtwyFraudDetected';

    public const GTWYRESULTPICKUPCARD = 'GtwyResultPickupCard';

    public const GTWYRESULTPINTRYEXCEEDED = 'GtwyResultPinTryExceeded';

    public const GTWYRESULTLOSTCARD = 'GtwyResultLostCard';

    public const GTWYRESULTSTOLENCARD = 'GtwyResultStolenCard';

    public const GTWYRESULTCLOSEDSHOPPERACCOUNT = 'GtwyResultClosedShopperAccount';

    public const GTWYRESULTRESTRICTEDCARD = 'GtwyResultRestrictedCard';

    public const GTWIRESULTCCWRONGPIN = 'GtwiResultCCWrongPin';

    public const GTWRESULTCCDECLINEDCARDNOTSUPPORTED = 'GtwResultCCDEclinedCardNotSupported';

    public const GTWRESULTCCDECLINEDCURRENCYNOTSUPPORTED = 'GtwResultCCDeclinedCurrencyNotSupported';

    public const GTWRESULTCCDECLINEDDUEAMOUNT = 'GtwResultCCDeclinedDueAmount';

    public const GTWRESULTCCDECLINEDDUESECURITYVIOLATION = 'GtwResultCCDeclinedDueSecurityViolation';

    public const AMOUNTEXCEEDSUSURYLIMIT = 'AmountExceedsUsuryLimit';

    public const INVALIDCREDENTIALS = 'InvalidCredentials';

    public const USERISLOCKED = 'UserIsLocked';

    public const USERISLOCKEDDUEINACTIVITY = 'UserIsLockedDueInactivity';

    public const SESSIONNOTVALID = 'SessionNotValid';

    public const SESSIONEXPIRED = 'SessionExpired';

    public const ACTIVITYNOTALLOWEDFORUSER = 'ActivityNotAllowedForUser';

    public const ACTIVITYONMERCHANTNOTALLOWEDFORUSER = 'ActivityOnMerchantNotAllowedForUser';

    public const ACTIVITYONTERMINALNOTALLOWEDFORUSER = 'ActivityOnTerminalNotAllowedForUser';

    public const ACTIVITYONINSTALLMENTPLANNOTALLOWEDFORUSER = 'ActivityOnInstallmentPlanNotAllowedForUser';

    public const TOKENNOTFOUNDOREXPIRED = 'TokenNotFoundOrExpired';

    public const TOKENALREADYUSED = 'TokenAlreadyUsed';

    public const USEROLDPASSRODISINCORRECT = 'UserOldPassrodIsIncorrect';

    public const USERNEWPASSWORDALREADYUSED = 'UserNewPasswordAlreadyUsed';

    public const USEREMAILNOTFOUND = 'UserEmailNotFound';

    public const PASSWORDEXPIRED = 'PasswordExpired';

    public const TOUCHPOINTNOTFOUND = 'TouchPointNotFound';

    public const ACTIVITYNOTALLOWEDFORPUBLICSESSION = 'ActivityNotAllowedForPublicSession';

    public const USERRELATESTOMORETHANSINGLEBUSINESSUNIT = 'UserRelatesToMoreThanSingleBusinessUnit';

    public const INVALIDPASSWORDSTRENGTH = 'InvalidPasswordStrength';

    public const INVALIDREQUESTEDSTRATEGY = 'InvalidRequestedStrategy';

    public const ROLENOTALLOWEDFORUSER = 'RoleNotAllowedForUser';

    public const USERNAMEALREADYEXISTS = 'UserNameAlreadyExists';

    public const ACTIVITYNOTALLOWEDFORAUTHENTICATIONTYPE = 'ActivityNotAllowedForAuthenticationType';

    public const ACTIVITYNOTALLOWEDDUETOPRIVACYPROTECTION = 'ActivityNotAllowedDueToPrivacyProtection';

    public const BUSINESSUNITNOTALLOWEDFORUSER = 'BusinessUnitNotAllowedForUser';

    public const UPDATETODIFFERENTBUSINESSPARTYROLENOTALLOWED = 'UpdateToDifferentBusinessPartyRoleNotAllowed';

    public const EXTERNALAUTHAMOUNTNOTVALID = 'ExternalAuthAmountNotValid';

    public const CAPTCHANOTSUCCESSFUL = 'CaptchaNotSuccessful';

    public const REPORTNOTALLOWEDFORUSER = 'ReportNotAllowedForUser';

    public const PHONETOKENINVALIDOREXPIRED = 'PhoneTokenInvalidOrExpired';

    public const USEREMAILHIDDENBYEXTERNALPROVIDER = 'UserEmailHiddenByExternalProvider';

    public const INVALIDPERIODRANGEVALUES = 'InvalidPeriodRangeValues';

    public const REMOVEDTRANSACTIONCURRENCYISINUSEBYTERMINAL = 'RemovedTransactionCurrencyIsInUseByTerminal';

    public const REMOVEDTRANSACTIONCURRENCYISINUSEBYACCOUNTINGCURRENCY =
        'RemovedTransactionCurrencyIsInUseByAccountingCurrency';

    public const INVALIDAMOUNTRANGEVALUES = 'InvalidAmountRangeValues';

    public const EMAILCANNOTBEEMPTY = 'EmailCannotBeEmpty';

    public const COUNTRYNOTSUPPORTED = 'CountryNotSupported';

    public const TERMINALAPIKEYMISSING = 'TerminalApiKeyMissing';

    public const FULLNAMECANNOTBEEMPTY = 'FullnameCannotBeEmpty';

    public const COMPANYNAMECANNOTBEEMPTY = 'CompanyNameCannotBeEmpty';

    public const INVALIDCOMPANYFORMAT = 'InvalidCompanyFormat';

    public const INVALIDFULLNAMEFORMAT = 'InvalidFullnameFormat';

    public const INVALIDSTOREURL = 'InvalidStoreUrl';

    public const INVALIDCOMPANYWEBSITE = 'InvalidCompanyWebsite';

    public const TERMINALPROCESSORISMISSING = 'TerminalProcessorIsMissing';

    public const NONTRANSACTIONALLOWEDTOCREATETERMINAL = 'NonTransactionAllowedToCreateTerminal';

    public const TOTALWEIGHTEDVALUESNOTEQUAL100 = 'TotalWeightedValuesNotEqual100';

    public const AMOUNTEXCEEDEDMAXALLOWEDFORFUNDINGOPERATION = 'AmountExceededMaxAllowedForFundingOperation';

    public const FUNDEDPLANSCANNOTBECANCELEDWITHOUTREFUND = 'FundedPlansCannotBeCanceledWithoutRefund';

    public const INSTALLMENTSCANNOTBEUPDATEDONFUNDEDPLANWITHLOWERPLANAMOUNT =
        'InstallmentsCannotBeUpdatedOnFundedPlanWithLowerPlanAmount';

    public const NOFUNDINGPLANINFOFORINSTALLMENTPLAN = 'NoFundingPlanInfoForInstallmentPlan';

    public const NOFUNDINGSETUPFORBUSINESSUNIT = 'NoFundingSetupForBusinessUnit';

    public const MERCHANTISNOTFINANCEDYET = 'MerchantIsNotFinancedYet';

    public const CANNOTCHANGEFUNDINGCOLLECTIONMETHOD = 'CannotChangeFundingCollectionMethod';

    public const SALESFORCEOPERATIONERROR = 'SalesforceOperationError';

    public const MAXRETRIESEXCEEDED = 'MaxRetriesExceeded';

    public const IDEMPOTENCYHASHMISMATCHERROR = 'IdempotencyHashMismatchError';

    public const TERMINALNOTSUPPORTPAYMENTTOKEN = 'TerminalNotSupportPaymentToken';

    public const ADDITIONTOKENPARAMNOTEXIST = 'AdditionTokenParamNotExist';

    public const UNABLETORETRIEVECARDFROMTOKEN = 'UnableToRetrieveCardFromToken';

    public const PROCESSORSETTINGSNOTENABLED = 'ProcessorSettingsNotEnabled';

    public const UNABLETOUPDATEDISPUTE = 'UnableToUpdateDispute';

    public const ENCRYPTIONERROR = 'EncryptionError';

    public const DECRYPTIONERROR = 'DecryptionError';

    public const MULTIPLEMESSAGINGMEANSPROVIDED = 'MultipleMessagingMeansProvided';

    public const NOMESSAGINGMEANSWASPROVIDED = 'NoMessagingMeansWasProvided';

    public const LOGOCANNOTBEREMOVED = 'LogoCannotBeRemoved';

    public const PLANISLOCKEDFORCHANGES = 'PlanIsLockedForChanges';

    public const CANNOTPERFROMACTIONDUETOACTIVEDELAYDCHARGE = 'CannotPerfromActionDueToActiveDelaydCharge';

    public const EXTERNALINSTALLMENTPROVIDERERROR = 'ExternalInstallmentProviderError';

    public const CANNOTCHANGEAMOUNTWHENSTATUSISNTINITIALIZE = 'CannotChangeAmountWhenStatusIsntInitialize';

    public const CANNOTCHARGEBEFORESTARTINSTALLMENTS = 'CannotChargeBeforeStartInstallments';

    public const EXECUTIONCANCELLED = 'ExecutionCancelled';

    public const INVALIDPLANSTATUS = 'InvalidPlanStatus';

    public const TRANSACTIONROUTENOTFOUND = 'TransactionRouteNotFound';

    public const PLANHASMOREOPENAUTHORIZATIONS = 'PlanHasMoreOpenAuthorizations';

    public const INVALIDREFORDERNUMBER = 'InvalidRefOrderNumber';

    public const STARTINSTALLMENTSRETRYEXCEEDED = 'StartInstallmentsRetryExceeded';

    public const STARTINSTALLMENTSRETRYLOOPALREADYEXIST = 'StartInstallmentsRetryLoopAlreadyExist';

    public const INVALIDINSTALLMENTPLANAUTHORIZATIONSTATUS = 'InvalidInstallmentPlanAuthorizationStatus';

    public const INVALIDCCCARDTYPENOTSUPPORTEDMORETHANXINSTALLMENTS =
        'InvalidCCCardTypeNotSupportedMoreThanXInstallments';

    public const INVALIDCCCARDTYPENOTSUPPORTEDMORETHANXAMOUNT = 'InvalidCCCardTypeNotSupportedMoreThanXAmount';

    public const INVALIDNUMBEROFREQUESTEDINSTALLMENTS = 'InvalidNumberOfRequestedInstallments';

    public const CARDUPDATELIMITBREACHED = 'CardUpdateLimitBreached';

    public const CARDUPDATEDENIEDOPENDISPUTES = 'CardUpdateDeniedOpenDisputes';

    public const PLANAMOUNTEXCEEDSALLOWEDDECIMALPLACES = 'PlanAmountExceedsAllowedDecimalPlaces';

    public const SHOPPERBALANCEEXCEEDED = 'ShopperBalanceExceeded';

    public const INVALIDCARDNUMBERLENGTH = 'InvalidCardNumberLength';

    public const BILLINGCOUNTRYISNOTALLOWEDFORMERCHANT = 'BillingCountryIsNotAllowedForMerchant';

    public const INVALIDCCCARDBRANDNOTSUPPORTEDMORETHANXINSTALLMENTS =
        'InvalidCCCardBrandNotSupportedMoreThanXInstallments';

    public const INVALIDCCCARDBRANDNOTSUPPORTEDMORETHANXAMOUNT = 'InvalidCCCardBrandNotSupportedMoreThanXAmount';

    public const REFUNDNOTALLOWEDFORCHARGEBACKPLANS = 'RefundNotAllowedForChargebackPlans';

    public const REFUNDFAILEDPLANALREADYREFUNDED = 'RefundFailedPlanAlreadyRefunded';

    public const EMAILNOTVERIFIED = 'EmailNotVerified';

    public const INVALIDCCPREPAIDCARDNOTSUPPORTEDMORETHANXINSTALLMENTS =
        'InvalidCcPrepaidCardNotSupportedMoreThanXInstallments';

    public const INVALIDCCPREPAIDCARDNOTSUPPORTEDMORETHANXAMOUNT = 'InvalidCcPrepaidCardNotSupportedMoreThanXAmount';

    public const PLANVERIFICATIONFAILED = 'PlanVerificationFailed';

    public const PAYMENTTOKENIZATIONNOTENABLED = 'PaymentTokenizationNotEnabled';

    public const INVALIDINTERNALURLSENTTOOMS = 'InvalidInternalUrlSentToOms';

    public const ISSUERBINBLACKLISTED = 'IssuerBinBlacklisted';

    public const MERCHANTDORMANTACCOUNT = 'MerchantDormantAccount';

    public const SHOPPERDETAILSBLACKLISTED = 'ShopperDetailsBlacklisted';

    public const PLANCONTEXTNOTVALIDFORNUMBEROFINSTALLMENTS = 'PlanContextNotValidForNumberOfInstallments';

    public const PLANCONTEXTNOTVALIDFORAMOUNT = 'PlanContextNotValidForAmount';

    public const GENERALTIMEOUTERROR = 'GeneralTimeoutError';

    public const CANNOTCANCELCFPLAN = 'CanNotCancelCFPlan';

    public const ISSUERREFUNDEXPIRED = 'IssuerRefundExpired';

    public const UPDATECARDNOTALLOWEDPLANISNOTACTIVE = 'UpdateCardNotAllowedPlanIsNotActive';

    public const USEREMAILALREADYEXISTS = 'UserEmailAlreadyExists';

    public const USERNOTFOUND = 'UserNotFound';

    public const USERHASNOROLESASSIGNED = 'UserHasNoRolesAssigned';

    public const NONE = 'None';

    private const _ALL_VALUES = [
        self::CONFIGURATIONKEYNOTFOUND,
        self::IDNOTFOUND,
        self::INVALIDINPUT,
        self::EXTERNALSYSTEMCALLFAILED,
        self::IDEMPOTENCYERROR,
        self::IDEMPOTENCYORIGINALREQUESTERROR,
        self::RULEDATAALREADYEXISTS,
        self::PGPENCRYPTIONKEYNOTFOUND,
        self::INVALIDPGPKEY,
        self::MERCHANTMUSTBEPROVIDED,
        self::INVALIDMERCHANTCONFIGURATION,
        self::INVALIDINSTALLMENTPLANNUMBER,
        self::INVALIDINSTALLMENTPLANSTATUS,
        self::INVALIDCCCARDTYPENOTSUPPORTED,
        self::INVALIDNUMBEROFINSTALLMENTS,
        self::INVALIDAMOUNTFORMAT,
        self::CARDUPDATEISNOTALLOWED,
        self::INVALIDCOUNTRYCODE,
        self::INVALIDRESPONSEURL,
        self::INVALIDCARDHOLDERNAME,
        self::INVALIDAMOUNT,
        self::INVALIDCVV,
        self::INVALIDCARDNUMBER,
        self::INVALIDEXPIRATIONDATE,
        self::INVALIDCONSUMERFULLNAME,
        self::INVALIDEMAILFORMAT,
        self::INVALIDADDRESS,
        self::INVALIDZIPCODE,
        self::INVALIDCCISSUECOUNTRYNOTSUPPORTEDBYTERMINAL,
        self::INVALIDCURRENCY,
        self::INVALIDMASKEDCCNUMNOTFOUNDINPLAN,
        self::INSTALLMENTPLANISABOUTTOEXPIRE,
        self::COUNTRYSUBDIVISIONNOTSUPPORTED,
        self::UPDATEINSTALLMENT_WITHHIGHERAMOUNTTHANPERSISTEDISNOTALLOW,
        self::UPDATEINSTALLMENT_FIRSTINSTALLMENTWITHHIGHERAMOUNTTHANPERSISTEDISNOTALLOW,
        self::UPDATEINSTALLMENT_INTHEMIDDLEOFPLANASZEROISNOTALLOW,
        self::REFUNDINSTALLMENTWITHHIGHERAMOUNTTHANORIGINALISNOTALLOWED,
        self::REFUNDINSTALLMENTTHATHASBEENCAPTUREDYETISNOTALLOWED,
        self::UPDATEINSTALLMENT_ALREADYPROCESSED,
        self::APPROVEPLAN_PLANALREADYAPPROVED,
        self::INVALIDEXPIRATIONDATEFORMAT,
        self::INVALIDCCBINNOTFOUND,
        self::INVALIDCCCARDBRANDNOTSUPPORTED,
        self::APPROVEPLAN_NOAPPROVALEVIDENCE,
        self::PLANWITHTHESAMEPAYMENTDATAALREADYBEENCREATEDLATELY,
        self::INVALIDFUTURECHARGEDATE,
        self::INVALIDFIRSTINSTALLMENTAMOUNT,
        self::CULTURENAMENOTVALID,
        self::CULTURENOTSUPPORTED,
        self::SYSTEMTEXTKEYNOTFOUND,
        self::TERMINALNOTFOUNDBYSUPPLIEDAPIKEY,
        self::UNKNOWNZIPCODE,
        self::CCREJECTIONPROCESSCANNOTBEINITIATEDDUETOAUTHEXPIRATION,
        self::CANTCHARGEINSTALLMENTWHILEPLANCHARGESAREONHOLD,
        self::CANTRELEASEHOLDONCHARGESSINCECHARGESARENOTHOLDED,
        self::REFUNDNOTALLOWEDONEORMOREINSTALLMENTSPASSEDREFUNDALLOWEDTIME,
        self::REFUNDPARTIALYFAILEDONEORMOREINSTALLMENTFAILEDREFUND,
        self::REFUNDFAILED,
        self::UPDATEPLANPARAMETERSARENOTSUPPORTED,
        self::REFUNDREQUESTEDAMOUNTEXCEEDEDPLANREFUNDABLEAMOUNT,
        self::INVALIDCURRENCY_NOTSUPPORTEDBYTERMINAL,
        self::CREDITCARDISMISSING,
        self::PISMEMBERISMISSING,
        self::ADDRESSDATAISMISSINGORPARTIALLYINITIATED,
        self::CARDHOLDERNAMEISMISSING,
        self::CARDNUMBERISMISSING,
        self::CARDEXPIRATIONMONTHISMISSING,
        self::CARDEXPIRATIONYEARISMISSING,
        self::NUMBEROFINSTALLMENTNOTDEFINED,
        self::INVALIDSTATECODE,
        self::EMAILISMISSING,
        self::CONSUMERFULLNAMEISMISSING,
        self::CURRENCYMUSTBEDEFINEDONTRANSACTION,
        self::COULDNOTFUNDINSTALLMENTPLAN,
        self::COULDNOTREVERTFUND,
        self::INVALIDPLANSTRATEGY,
        self::FULLCAPTURENOTSUPPORTED,
        self::INVALIDCCPREPAIDCARDNOTSUPPORTED,
        self::CARDEXPIREBEFOREPLANENDS,
        self::PARTIALPLANAMOUNTAUTHORIZED,
        self::SECUREDAUTHORIZATIONREQUIREDFORPARTIALPAYMENT,
        self::THREEDSECUREDATANOTFOUND,
        self::THREEDSECURENOTSUPPORTEDBYPLANSTRATEGY,
        self::THREEDSECUREREQUIREDDATAMISSING,
        self::STRATEGYNOTALLOWED,
        self::PAYMENTTOKENNOTVALID,
        self::ACTIVITYNOTSUPPORTEDFORPLANSTRATEGY,
        self::PAYMENTWIZARDVIEWNOTEXIST,
        self::INVALIDURL,
        self::ISSUERBINNOTSUPPORTINGINSTALLMENTEXCEPTION,
        self::COULDNOTCHANGELENDER,
        self::FRAUDDETECED,
        self::PHONEISMISSING,
        self::INVALIDPHONEFORMAT,
        self::INSTALLMENTMISSINGOPENAUTHORIZATION,
        self::GENERALERROR,
        self::GTWYRESULTGENERALERROR,
        self::GTWYRESULTCCDATAAVSZIP,
        self::GTWYRESULTCCDATAAVSADDRESS,
        self::GTWYRESULTCCDATACVV,
        self::GTWYRESULTCCDATACCEXPIRATION,
        self::GTWYRESULTCCDATAAVS,
        self::GTWYRESULTCCDATANUMBER,
        self::GTWYRESULTCCDATAGENERALPROBLEM,
        self::GTWYRESULTCCDATAINSUFFICIENTFUNDS,
        self::GTWYRESULTCCWASDECLINED,
        self::GTWYUNAUTHORIZEDCREDENTIALS,
        self::GTWYCONNECTIVITYPROBLEM,
        self::GTWYMERCHANTDATAPROBLEM,
        self::GTWYREQUIRE3DAUTHENTICATION,
        self::ACTIVEINSTALLMENTPLANSGTWERROR,
        self::GTWY3DAUTHENTICATIONFAILED,
        self::GTWYFRAUDDETECTED,
        self::GTWYRESULTPICKUPCARD,
        self::GTWYRESULTPINTRYEXCEEDED,
        self::GTWYRESULTLOSTCARD,
        self::GTWYRESULTSTOLENCARD,
        self::GTWYRESULTCLOSEDSHOPPERACCOUNT,
        self::GTWYRESULTRESTRICTEDCARD,
        self::GTWIRESULTCCWRONGPIN,
        self::GTWRESULTCCDECLINEDCARDNOTSUPPORTED,
        self::GTWRESULTCCDECLINEDCURRENCYNOTSUPPORTED,
        self::GTWRESULTCCDECLINEDDUEAMOUNT,
        self::GTWRESULTCCDECLINEDDUESECURITYVIOLATION,
        self::AMOUNTEXCEEDSUSURYLIMIT,
        self::INVALIDCREDENTIALS,
        self::USERISLOCKED,
        self::USERISLOCKEDDUEINACTIVITY,
        self::SESSIONNOTVALID,
        self::SESSIONEXPIRED,
        self::ACTIVITYNOTALLOWEDFORUSER,
        self::ACTIVITYONMERCHANTNOTALLOWEDFORUSER,
        self::ACTIVITYONTERMINALNOTALLOWEDFORUSER,
        self::ACTIVITYONINSTALLMENTPLANNOTALLOWEDFORUSER,
        self::TOKENNOTFOUNDOREXPIRED,
        self::TOKENALREADYUSED,
        self::USEROLDPASSRODISINCORRECT,
        self::USERNEWPASSWORDALREADYUSED,
        self::USEREMAILNOTFOUND,
        self::PASSWORDEXPIRED,
        self::TOUCHPOINTNOTFOUND,
        self::ACTIVITYNOTALLOWEDFORPUBLICSESSION,
        self::USERRELATESTOMORETHANSINGLEBUSINESSUNIT,
        self::INVALIDPASSWORDSTRENGTH,
        self::INVALIDREQUESTEDSTRATEGY,
        self::ROLENOTALLOWEDFORUSER,
        self::USERNAMEALREADYEXISTS,
        self::ACTIVITYNOTALLOWEDFORAUTHENTICATIONTYPE,
        self::ACTIVITYNOTALLOWEDDUETOPRIVACYPROTECTION,
        self::BUSINESSUNITNOTALLOWEDFORUSER,
        self::UPDATETODIFFERENTBUSINESSPARTYROLENOTALLOWED,
        self::EXTERNALAUTHAMOUNTNOTVALID,
        self::CAPTCHANOTSUCCESSFUL,
        self::REPORTNOTALLOWEDFORUSER,
        self::PHONETOKENINVALIDOREXPIRED,
        self::USEREMAILHIDDENBYEXTERNALPROVIDER,
        self::INVALIDPERIODRANGEVALUES,
        self::REMOVEDTRANSACTIONCURRENCYISINUSEBYTERMINAL,
        self::REMOVEDTRANSACTIONCURRENCYISINUSEBYACCOUNTINGCURRENCY,
        self::INVALIDAMOUNTRANGEVALUES,
        self::EMAILCANNOTBEEMPTY,
        self::COUNTRYNOTSUPPORTED,
        self::TERMINALAPIKEYMISSING,
        self::FULLNAMECANNOTBEEMPTY,
        self::COMPANYNAMECANNOTBEEMPTY,
        self::INVALIDCOMPANYFORMAT,
        self::INVALIDFULLNAMEFORMAT,
        self::INVALIDSTOREURL,
        self::INVALIDCOMPANYWEBSITE,
        self::TERMINALPROCESSORISMISSING,
        self::NONTRANSACTIONALLOWEDTOCREATETERMINAL,
        self::TOTALWEIGHTEDVALUESNOTEQUAL100,
        self::AMOUNTEXCEEDEDMAXALLOWEDFORFUNDINGOPERATION,
        self::FUNDEDPLANSCANNOTBECANCELEDWITHOUTREFUND,
        self::INSTALLMENTSCANNOTBEUPDATEDONFUNDEDPLANWITHLOWERPLANAMOUNT,
        self::NOFUNDINGPLANINFOFORINSTALLMENTPLAN,
        self::NOFUNDINGSETUPFORBUSINESSUNIT,
        self::MERCHANTISNOTFINANCEDYET,
        self::CANNOTCHANGEFUNDINGCOLLECTIONMETHOD,
        self::SALESFORCEOPERATIONERROR,
        self::MAXRETRIESEXCEEDED,
        self::IDEMPOTENCYHASHMISMATCHERROR,
        self::TERMINALNOTSUPPORTPAYMENTTOKEN,
        self::ADDITIONTOKENPARAMNOTEXIST,
        self::UNABLETORETRIEVECARDFROMTOKEN,
        self::PROCESSORSETTINGSNOTENABLED,
        self::UNABLETOUPDATEDISPUTE,
        self::ENCRYPTIONERROR,
        self::DECRYPTIONERROR,
        self::MULTIPLEMESSAGINGMEANSPROVIDED,
        self::NOMESSAGINGMEANSWASPROVIDED,
        self::LOGOCANNOTBEREMOVED,
        self::PLANISLOCKEDFORCHANGES,
        self::CANNOTPERFROMACTIONDUETOACTIVEDELAYDCHARGE,
        self::EXTERNALINSTALLMENTPROVIDERERROR,
        self::CANNOTCHANGEAMOUNTWHENSTATUSISNTINITIALIZE,
        self::CANNOTCHARGEBEFORESTARTINSTALLMENTS,
        self::EXECUTIONCANCELLED,
        self::INVALIDPLANSTATUS,
        self::TRANSACTIONROUTENOTFOUND,
        self::PLANHASMOREOPENAUTHORIZATIONS,
        self::INVALIDREFORDERNUMBER,
        self::STARTINSTALLMENTSRETRYEXCEEDED,
        self::STARTINSTALLMENTSRETRYLOOPALREADYEXIST,
        self::INVALIDINSTALLMENTPLANAUTHORIZATIONSTATUS,
        self::INVALIDCCCARDTYPENOTSUPPORTEDMORETHANXINSTALLMENTS,
        self::INVALIDCCCARDTYPENOTSUPPORTEDMORETHANXAMOUNT,
        self::INVALIDNUMBEROFREQUESTEDINSTALLMENTS,
        self::CARDUPDATELIMITBREACHED,
        self::CARDUPDATEDENIEDOPENDISPUTES,
        self::PLANAMOUNTEXCEEDSALLOWEDDECIMALPLACES,
        self::SHOPPERBALANCEEXCEEDED,
        self::INVALIDCARDNUMBERLENGTH,
        self::BILLINGCOUNTRYISNOTALLOWEDFORMERCHANT,
        self::INVALIDCCCARDBRANDNOTSUPPORTEDMORETHANXINSTALLMENTS,
        self::INVALIDCCCARDBRANDNOTSUPPORTEDMORETHANXAMOUNT,
        self::REFUNDNOTALLOWEDFORCHARGEBACKPLANS,
        self::REFUNDFAILEDPLANALREADYREFUNDED,
        self::EMAILNOTVERIFIED,
        self::INVALIDCCPREPAIDCARDNOTSUPPORTEDMORETHANXINSTALLMENTS,
        self::INVALIDCCPREPAIDCARDNOTSUPPORTEDMORETHANXAMOUNT,
        self::PLANVERIFICATIONFAILED,
        self::PAYMENTTOKENIZATIONNOTENABLED,
        self::INVALIDINTERNALURLSENTTOOMS,
        self::ISSUERBINBLACKLISTED,
        self::MERCHANTDORMANTACCOUNT,
        self::SHOPPERDETAILSBLACKLISTED,
        self::PLANCONTEXTNOTVALIDFORNUMBEROFINSTALLMENTS,
        self::PLANCONTEXTNOTVALIDFORAMOUNT,
        self::GENERALTIMEOUTERROR,
        self::CANNOTCANCELCFPLAN,
        self::ISSUERREFUNDEXPIRED,
        self::UPDATECARDNOTALLOWEDPLANISNOTACTIVE,
        self::USEREMAILALREADYEXISTS,
        self::USERNOTFOUND,
        self::USERHASNOROLESASSIGNED,
        self::NONE
    ];

    /**
     * Ensures that all the given values are present in this Enum.
     *
     * @param array|stdClass|null|string $value Value or a list/map of values to be checked
     *
     * @return array|null|string Input value(s), if all are a part of this Enum
     *
     * @throws Exception Throws exception if any given value is not in this Enum
     */
    public static function checkValue($value)
    {
        $value = json_decode(json_encode($value), true); // converts stdClass into array
        if (CoreHelper::checkValueOrValuesInList($value, self::_ALL_VALUES)) {
            return $value;
        }
        throw new Exception("$value is invalid for PisErrorCodesEnum.");
    }
}
