<?php

declare(strict_types=1);

/*
 * SplititWebApiV4Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SplititWebApiV4Lib\Models;

use SplititWebApiV4Lib\ApiHelper;
use stdClass;

class RedirectUrls implements \JsonSerializable
{
    /**
     * @var string
     */
    private $successUrl;

    /**
     * @var string|null
     */
    private $failureUrl;

    /**
     * @var string|null
     */
    private $cancelUrl;

    /**
     * @param string $successUrl
     */
    public function __construct(string $successUrl)
    {
        $this->successUrl = $successUrl;
    }

    /**
     * Returns Success Url.
     */
    public function getSuccessUrl(): string
    {
        return $this->successUrl;
    }

    /**
     * Sets Success Url.
     *
     * @required
     * @maps SuccessUrl
     */
    public function setSuccessUrl(string $successUrl): void
    {
        $this->successUrl = $successUrl;
    }

    /**
     * Returns Failure Url.
     */
    public function getFailureUrl(): ?string
    {
        return $this->failureUrl;
    }

    /**
     * Sets Failure Url.
     *
     * @maps FailureUrl
     */
    public function setFailureUrl(?string $failureUrl): void
    {
        $this->failureUrl = $failureUrl;
    }

    /**
     * Returns Cancel Url.
     */
    public function getCancelUrl(): ?string
    {
        return $this->cancelUrl;
    }

    /**
     * Sets Cancel Url.
     *
     * @maps CancelUrl
     */
    public function setCancelUrl(?string $cancelUrl): void
    {
        $this->cancelUrl = $cancelUrl;
    }

    /**
     * Converts the RedirectUrls object to a human-readable string representation.
     *
     * @return string The string representation of the RedirectUrls object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'RedirectUrls',
            ['successUrl' => $this->successUrl, 'failureUrl' => $this->failureUrl, 'cancelUrl' => $this->cancelUrl]
        );
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        $json['SuccessUrl']     = $this->successUrl;
        if (isset($this->failureUrl)) {
            $json['FailureUrl'] = $this->failureUrl;
        }
        if (isset($this->cancelUrl)) {
            $json['CancelUrl']  = $this->cancelUrl;
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
