<?php

declare(strict_types=1);

/*
 * SplititWebApiV4Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SplititWebApiV4Lib\Models;

use SplititWebApiV4Lib\ApiHelper;
use SplititWebApiV4Lib\Utils\DateTimeHelper;
use stdClass;

class RefundItem implements \JsonSerializable
{
    /**
     * @var \DateTime|null
     */
    private $submitDate;

    /**
     * @var float
     */
    private $requestedAmount;

    /**
     * @var string|null
     */
    private $status;

    /**
     * @var float|null
     */
    private $nonCreditRefundAmount;

    /**
     * @var float|null
     */
    private $creditRefundAmount;

    /**
     * @var string|null
     */
    private $refundId;

    /**
     * @var string|null
     */
    private $referenceId;

    /**
     * @param float $requestedAmount
     */
    public function __construct(float $requestedAmount)
    {
        $this->requestedAmount = $requestedAmount;
    }

    /**
     * Returns Submit Date.
     */
    public function getSubmitDate(): ?\DateTime
    {
        return $this->submitDate;
    }

    /**
     * Sets Submit Date.
     *
     * @maps SubmitDate
     * @factory \SplititWebApiV4Lib\Utils\DateTimeHelper::fromRfc3339DateTime
     */
    public function setSubmitDate(?\DateTime $submitDate): void
    {
        $this->submitDate = $submitDate;
    }

    /**
     * Returns Requested Amount.
     */
    public function getRequestedAmount(): float
    {
        return $this->requestedAmount;
    }

    /**
     * Sets Requested Amount.
     *
     * @required
     * @maps RequestedAmount
     */
    public function setRequestedAmount(float $requestedAmount): void
    {
        $this->requestedAmount = $requestedAmount;
    }

    /**
     * Returns Status.
     */
    public function getStatus(): ?string
    {
        return $this->status;
    }

    /**
     * Sets Status.
     *
     * @maps Status
     */
    public function setStatus(?string $status): void
    {
        $this->status = $status;
    }

    /**
     * Returns Non Credit Refund Amount.
     */
    public function getNonCreditRefundAmount(): ?float
    {
        return $this->nonCreditRefundAmount;
    }

    /**
     * Sets Non Credit Refund Amount.
     *
     * @maps NonCreditRefundAmount
     */
    public function setNonCreditRefundAmount(?float $nonCreditRefundAmount): void
    {
        $this->nonCreditRefundAmount = $nonCreditRefundAmount;
    }

    /**
     * Returns Credit Refund Amount.
     */
    public function getCreditRefundAmount(): ?float
    {
        return $this->creditRefundAmount;
    }

    /**
     * Sets Credit Refund Amount.
     *
     * @maps CreditRefundAmount
     */
    public function setCreditRefundAmount(?float $creditRefundAmount): void
    {
        $this->creditRefundAmount = $creditRefundAmount;
    }

    /**
     * Returns Refund Id.
     */
    public function getRefundId(): ?string
    {
        return $this->refundId;
    }

    /**
     * Sets Refund Id.
     *
     * @maps RefundId
     */
    public function setRefundId(?string $refundId): void
    {
        $this->refundId = $refundId;
    }

    /**
     * Returns Reference Id.
     */
    public function getReferenceId(): ?string
    {
        return $this->referenceId;
    }

    /**
     * Sets Reference Id.
     *
     * @maps ReferenceId
     */
    public function setReferenceId(?string $referenceId): void
    {
        $this->referenceId = $referenceId;
    }

    /**
     * Converts the RefundItem object to a human-readable string representation.
     *
     * @return string The string representation of the RefundItem object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'RefundItem',
            [
                'submitDate' => $this->submitDate,
                'requestedAmount' => $this->requestedAmount,
                'status' => $this->status,
                'nonCreditRefundAmount' => $this->nonCreditRefundAmount,
                'creditRefundAmount' => $this->creditRefundAmount,
                'refundId' => $this->refundId,
                'referenceId' => $this->referenceId
            ]
        );
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->submitDate)) {
            $json['SubmitDate']            = DateTimeHelper::toRfc3339DateTime($this->submitDate);
        }
        $json['RequestedAmount']           = $this->requestedAmount;
        if (isset($this->status)) {
            $json['Status']                = $this->status;
        }
        if (isset($this->nonCreditRefundAmount)) {
            $json['NonCreditRefundAmount'] = $this->nonCreditRefundAmount;
        }
        if (isset($this->creditRefundAmount)) {
            $json['CreditRefundAmount']    = $this->creditRefundAmount;
        }
        if (isset($this->refundId)) {
            $json['RefundId']              = $this->refundId;
        }
        if (isset($this->referenceId)) {
            $json['ReferenceId']           = $this->referenceId;
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
