<?php

declare(strict_types=1);

/*
 * SplititWebApiV4Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SplititWebApiV4Lib\Models;

use SplititWebApiV4Lib\ApiHelper;
use stdClass;

class RefundResponse implements \JsonSerializable
{
    /**
     * @var string|null
     */
    private $refundId;

    /**
     * @var string|null
     */
    private $installmentPlanNumber;

    /**
     * @var string|null
     */
    private $currency;

    /**
     * @var float
     */
    private $requestedAmount;

    /**
     * @var string|null
     */
    private $referenceId;

    /**
     * @param float $requestedAmount
     */
    public function __construct(float $requestedAmount)
    {
        $this->requestedAmount = $requestedAmount;
    }

    /**
     * Returns Refund Id.
     */
    public function getRefundId(): ?string
    {
        return $this->refundId;
    }

    /**
     * Sets Refund Id.
     *
     * @maps RefundId
     */
    public function setRefundId(?string $refundId): void
    {
        $this->refundId = $refundId;
    }

    /**
     * Returns Installment Plan Number.
     */
    public function getInstallmentPlanNumber(): ?string
    {
        return $this->installmentPlanNumber;
    }

    /**
     * Sets Installment Plan Number.
     *
     * @maps InstallmentPlanNumber
     */
    public function setInstallmentPlanNumber(?string $installmentPlanNumber): void
    {
        $this->installmentPlanNumber = $installmentPlanNumber;
    }

    /**
     * Returns Currency.
     */
    public function getCurrency(): ?string
    {
        return $this->currency;
    }

    /**
     * Sets Currency.
     *
     * @maps Currency
     */
    public function setCurrency(?string $currency): void
    {
        $this->currency = $currency;
    }

    /**
     * Returns Requested Amount.
     */
    public function getRequestedAmount(): float
    {
        return $this->requestedAmount;
    }

    /**
     * Sets Requested Amount.
     *
     * @required
     * @maps RequestedAmount
     */
    public function setRequestedAmount(float $requestedAmount): void
    {
        $this->requestedAmount = $requestedAmount;
    }

    /**
     * Returns Reference Id.
     */
    public function getReferenceId(): ?string
    {
        return $this->referenceId;
    }

    /**
     * Sets Reference Id.
     *
     * @maps ReferenceId
     */
    public function setReferenceId(?string $referenceId): void
    {
        $this->referenceId = $referenceId;
    }

    /**
     * Converts the RefundResponse object to a human-readable string representation.
     *
     * @return string The string representation of the RefundResponse object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'RefundResponse',
            [
                'refundId' => $this->refundId,
                'installmentPlanNumber' => $this->installmentPlanNumber,
                'currency' => $this->currency,
                'requestedAmount' => $this->requestedAmount,
                'referenceId' => $this->referenceId
            ]
        );
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->refundId)) {
            $json['RefundId']              = $this->refundId;
        }
        if (isset($this->installmentPlanNumber)) {
            $json['InstallmentPlanNumber'] = $this->installmentPlanNumber;
        }
        if (isset($this->currency)) {
            $json['Currency']              = $this->currency;
        }
        $json['RequestedAmount']           = $this->requestedAmount;
        if (isset($this->referenceId)) {
            $json['ReferenceId']           = $this->referenceId;
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
