<?php

declare(strict_types=1);

/*
 * SplititWebApiV4Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SplititWebApiV4Lib\Models;

use SplititWebApiV4Lib\ApiHelper;
use stdClass;

class ShopperDetailsData implements \JsonSerializable
{
    /**
     * @var string|null
     */
    private $firstName;

    /**
     * @var string|null
     */
    private $lastName;

    /**
     * @var string|null
     */
    private $email;

    /**
     * @var string|null
     */
    private $phoneNumber;

    /**
     * @var string|null
     */
    private $culture;

    /**
     * @var BillingAddressData|null
     */
    private $billingAddress;

    /**
     * Returns First Name.
     */
    public function getFirstName(): ?string
    {
        return $this->firstName;
    }

    /**
     * Sets First Name.
     *
     * @maps FirstName
     */
    public function setFirstName(?string $firstName): void
    {
        $this->firstName = $firstName;
    }

    /**
     * Returns Last Name.
     */
    public function getLastName(): ?string
    {
        return $this->lastName;
    }

    /**
     * Sets Last Name.
     *
     * @maps LastName
     */
    public function setLastName(?string $lastName): void
    {
        $this->lastName = $lastName;
    }

    /**
     * Returns Email.
     */
    public function getEmail(): ?string
    {
        return $this->email;
    }

    /**
     * Sets Email.
     *
     * @maps Email
     */
    public function setEmail(?string $email): void
    {
        $this->email = $email;
    }

    /**
     * Returns Phone Number.
     */
    public function getPhoneNumber(): ?string
    {
        return $this->phoneNumber;
    }

    /**
     * Sets Phone Number.
     *
     * @maps PhoneNumber
     */
    public function setPhoneNumber(?string $phoneNumber): void
    {
        $this->phoneNumber = $phoneNumber;
    }

    /**
     * Returns Culture.
     */
    public function getCulture(): ?string
    {
        return $this->culture;
    }

    /**
     * Sets Culture.
     *
     * @maps Culture
     */
    public function setCulture(?string $culture): void
    {
        $this->culture = $culture;
    }

    /**
     * Returns Billing Address.
     */
    public function getBillingAddress(): ?BillingAddressData
    {
        return $this->billingAddress;
    }

    /**
     * Sets Billing Address.
     *
     * @maps BillingAddress
     */
    public function setBillingAddress(?BillingAddressData $billingAddress): void
    {
        $this->billingAddress = $billingAddress;
    }

    /**
     * Converts the ShopperDetailsData object to a human-readable string representation.
     *
     * @return string The string representation of the ShopperDetailsData object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'ShopperDetailsData',
            [
                'firstName' => $this->firstName,
                'lastName' => $this->lastName,
                'email' => $this->email,
                'phoneNumber' => $this->phoneNumber,
                'culture' => $this->culture,
                'billingAddress' => $this->billingAddress
            ]
        );
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->firstName)) {
            $json['FirstName']      = $this->firstName;
        }
        if (isset($this->lastName)) {
            $json['LastName']       = $this->lastName;
        }
        if (isset($this->email)) {
            $json['Email']          = $this->email;
        }
        if (isset($this->phoneNumber)) {
            $json['PhoneNumber']    = $this->phoneNumber;
        }
        if (isset($this->culture)) {
            $json['Culture']        = $this->culture;
        }
        if (isset($this->billingAddress)) {
            $json['BillingAddress'] = $this->billingAddress;
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
