<?php

declare(strict_types=1);

/*
 * SplititWebApiV4Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SplititWebApiV4Lib\Models;

use SplititWebApiV4Lib\ApiHelper;
use stdClass;

class ThreeDSRequestData implements \JsonSerializable
{
    /**
     * @var bool|null
     */
    private $execute;

    /**
     * @var RedirectUrls|null
     */
    private $threeDSURLs;

    /**
     * @var ThreeDSAuthenticationData|null
     */
    private $authenticationData;

    /**
     * Returns Execute.
     */
    public function getExecute(): ?bool
    {
        return $this->execute;
    }

    /**
     * Sets Execute.
     *
     * @maps Execute
     */
    public function setExecute(?bool $execute): void
    {
        $this->execute = $execute;
    }

    /**
     * Returns Three DSUR Ls.
     */
    public function getThreeDSURLs(): ?RedirectUrls
    {
        return $this->threeDSURLs;
    }

    /**
     * Sets Three DSUR Ls.
     *
     * @maps ThreeDSURLs
     */
    public function setThreeDSURLs(?RedirectUrls $threeDSURLs): void
    {
        $this->threeDSURLs = $threeDSURLs;
    }

    /**
     * Returns Authentication Data.
     */
    public function getAuthenticationData(): ?ThreeDSAuthenticationData
    {
        return $this->authenticationData;
    }

    /**
     * Sets Authentication Data.
     *
     * @maps AuthenticationData
     */
    public function setAuthenticationData(?ThreeDSAuthenticationData $authenticationData): void
    {
        $this->authenticationData = $authenticationData;
    }

    /**
     * Converts the ThreeDSRequestData object to a human-readable string representation.
     *
     * @return string The string representation of the ThreeDSRequestData object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'ThreeDSRequestData',
            [
                'execute' => $this->execute,
                'threeDSURLs' => $this->threeDSURLs,
                'authenticationData' => $this->authenticationData
            ]
        );
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->execute)) {
            $json['Execute']            = $this->execute;
        }
        if (isset($this->threeDSURLs)) {
            $json['ThreeDSURLs']        = $this->threeDSURLs;
        }
        if (isset($this->authenticationData)) {
            $json['AuthenticationData'] = $this->authenticationData;
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
