<?php

declare(strict_types=1);

/*
 * SplititWebApiV4Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SplititWebApiV4Lib\Models;

use SplititWebApiV4Lib\ApiHelper;
use stdClass;

class ThreeDSAuthenticationData implements \JsonSerializable
{
    /**
     * @var string
     */
    private $eCI;

    /**
     * @var string
     */
    private $cAVV;

    /**
     * @var string
     */
    private $directoryServerTransactionId;

    /**
     * @var string
     */
    private $version;

    /**
     * @param string $eCI
     * @param string $cAVV
     * @param string $directoryServerTransactionId
     * @param string $version
     */
    public function __construct(string $eCI, string $cAVV, string $directoryServerTransactionId, string $version)
    {
        $this->eCI = $eCI;
        $this->cAVV = $cAVV;
        $this->directoryServerTransactionId = $directoryServerTransactionId;
        $this->version = $version;
    }

    /**
     * Returns E CI.
     */
    public function getECI(): string
    {
        return $this->eCI;
    }

    /**
     * Sets E CI.
     *
     * @required
     * @maps ECI
     */
    public function setECI(string $eCI): void
    {
        $this->eCI = $eCI;
    }

    /**
     * Returns C AVV.
     */
    public function getCAVV(): string
    {
        return $this->cAVV;
    }

    /**
     * Sets C AVV.
     *
     * @required
     * @maps CAVV
     */
    public function setCAVV(string $cAVV): void
    {
        $this->cAVV = $cAVV;
    }

    /**
     * Returns Directory Server Transaction Id.
     */
    public function getDirectoryServerTransactionId(): string
    {
        return $this->directoryServerTransactionId;
    }

    /**
     * Sets Directory Server Transaction Id.
     *
     * @required
     * @maps DirectoryServerTransactionId
     */
    public function setDirectoryServerTransactionId(string $directoryServerTransactionId): void
    {
        $this->directoryServerTransactionId = $directoryServerTransactionId;
    }

    /**
     * Returns Version.
     */
    public function getVersion(): string
    {
        return $this->version;
    }

    /**
     * Sets Version.
     *
     * @required
     * @maps Version
     */
    public function setVersion(string $version): void
    {
        $this->version = $version;
    }

    /**
     * Converts the ThreeDSAuthenticationData object to a human-readable string representation.
     *
     * @return string The string representation of the ThreeDSAuthenticationData object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'ThreeDSAuthenticationData',
            [
                'eCI' => $this->eCI,
                'cAVV' => $this->cAVV,
                'directoryServerTransactionId' => $this->directoryServerTransactionId,
                'version' => $this->version
            ]
        );
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        $json['ECI']                          = $this->eCI;
        $json['CAVV']                         = $this->cAVV;
        $json['DirectoryServerTransactionId'] = $this->directoryServerTransactionId;
        $json['Version']                      = $this->version;

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
