<?php

declare(strict_types=1);

/*
 * SplititWebApiV4Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SplititWebApiV4Lib\Models;

use SplititWebApiV4Lib\ApiHelper;
use stdClass;

class ThreeDSExecute implements \JsonSerializable
{
    /**
     * @var bool|null
     */
    private $execute;

    /**
     * Returns Execute.
     */
    public function getExecute(): ?bool
    {
        return $this->execute;
    }

    /**
     * Sets Execute.
     *
     * @maps Execute
     */
    public function setExecute(?bool $execute): void
    {
        $this->execute = $execute;
    }

    /**
     * Converts the ThreeDSExecute object to a human-readable string representation.
     *
     * @return string The string representation of the ThreeDSExecute object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify('ThreeDSExecute', ['execute' => $this->execute]);
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->execute)) {
            $json['Execute'] = $this->execute;
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
