<?php

declare(strict_types=1);

/*
 * SplititWebApiV4Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SplititWebApiV4Lib\Models;

use SplititWebApiV4Lib\ApiHelper;
use stdClass;

class UpdateOffersRequest implements \JsonSerializable
{
    /**
     * @var string|null
     */
    private $merchantOrderReference;

    /**
     * @var OffersShopperDetails|null
     */
    private $shopperDetails;

    /**
     * @var UpdateOffersPaymentMethod|null
     */
    private $paymentMethod;

    /**
     * @var MetadataItem[]|null
     */
    private $metadata;

    /**
     * Returns Merchant Order Reference.
     */
    public function getMerchantOrderReference(): ?string
    {
        return $this->merchantOrderReference;
    }

    /**
     * Sets Merchant Order Reference.
     *
     * @maps MerchantOrderReference
     */
    public function setMerchantOrderReference(?string $merchantOrderReference): void
    {
        $this->merchantOrderReference = $merchantOrderReference;
    }

    /**
     * Returns Shopper Details.
     */
    public function getShopperDetails(): ?OffersShopperDetails
    {
        return $this->shopperDetails;
    }

    /**
     * Sets Shopper Details.
     *
     * @maps ShopperDetails
     */
    public function setShopperDetails(?OffersShopperDetails $shopperDetails): void
    {
        $this->shopperDetails = $shopperDetails;
    }

    /**
     * Returns Payment Method.
     */
    public function getPaymentMethod(): ?UpdateOffersPaymentMethod
    {
        return $this->paymentMethod;
    }

    /**
     * Sets Payment Method.
     *
     * @maps PaymentMethod
     */
    public function setPaymentMethod(?UpdateOffersPaymentMethod $paymentMethod): void
    {
        $this->paymentMethod = $paymentMethod;
    }

    /**
     * Returns Metadata.
     *
     * @return MetadataItem[]|null
     */
    public function getMetadata(): ?array
    {
        return $this->metadata;
    }

    /**
     * Sets Metadata.
     *
     * @maps Metadata
     *
     * @param MetadataItem[]|null $metadata
     */
    public function setMetadata(?array $metadata): void
    {
        $this->metadata = $metadata;
    }

    /**
     * Converts the UpdateOffersRequest object to a human-readable string representation.
     *
     * @return string The string representation of the UpdateOffersRequest object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'UpdateOffersRequest',
            [
                'merchantOrderReference' => $this->merchantOrderReference,
                'shopperDetails' => $this->shopperDetails,
                'paymentMethod' => $this->paymentMethod,
                'metadata' => $this->metadata
            ]
        );
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->merchantOrderReference)) {
            $json['MerchantOrderReference'] = $this->merchantOrderReference;
        }
        if (isset($this->shopperDetails)) {
            $json['ShopperDetails']         = $this->shopperDetails;
        }
        if (isset($this->paymentMethod)) {
            $json['PaymentMethod']          = $this->paymentMethod;
        }
        if (isset($this->metadata)) {
            $json['Metadata']               = $this->metadata;
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
