<?php

declare(strict_types=1);

/*
 * SplititWebApiV4Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SplititWebApiV4Lib\Models;

use SplititWebApiV4Lib\ApiHelper;
use stdClass;

class UpdateOrderResponse implements \JsonSerializable
{
    /**
     * @var string
     */
    private $status;

    /**
     * @var string|null
     */
    private $merchantOrderReference;

    /**
     * @var string|null
     */
    private $trackingNumber;

    /**
     * @var string|null
     */
    private $shippingStatus;

    /**
     * @var MetadataItem[]|null
     */
    private $metadata;

    /**
     * @var string|null
     */
    private $installmentPlanNumber;

    /**
     * @param string $status
     */
    public function __construct(string $status)
    {
        $this->status = $status;
    }

    /**
     * Returns Status.
     */
    public function getStatus(): string
    {
        return $this->status;
    }

    /**
     * Sets Status.
     *
     * @required
     * @maps Status
     * @factory \SplititWebApiV4Lib\Models\PlanStatusEnum::checkValue
     */
    public function setStatus(string $status): void
    {
        $this->status = $status;
    }

    /**
     * Returns Merchant Order Reference.
     */
    public function getMerchantOrderReference(): ?string
    {
        return $this->merchantOrderReference;
    }

    /**
     * Sets Merchant Order Reference.
     *
     * @maps MerchantOrderReference
     */
    public function setMerchantOrderReference(?string $merchantOrderReference): void
    {
        $this->merchantOrderReference = $merchantOrderReference;
    }

    /**
     * Returns Tracking Number.
     */
    public function getTrackingNumber(): ?string
    {
        return $this->trackingNumber;
    }

    /**
     * Sets Tracking Number.
     *
     * @maps TrackingNumber
     */
    public function setTrackingNumber(?string $trackingNumber): void
    {
        $this->trackingNumber = $trackingNumber;
    }

    /**
     * Returns Shipping Status.
     */
    public function getShippingStatus(): ?string
    {
        return $this->shippingStatus;
    }

    /**
     * Sets Shipping Status.
     *
     * @maps ShippingStatus
     * @factory \SplititWebApiV4Lib\Models\ShippingStatusEnum::checkValue
     */
    public function setShippingStatus(?string $shippingStatus): void
    {
        $this->shippingStatus = $shippingStatus;
    }

    /**
     * Returns Metadata.
     *
     * @return MetadataItem[]|null
     */
    public function getMetadata(): ?array
    {
        return $this->metadata;
    }

    /**
     * Sets Metadata.
     *
     * @maps Metadata
     *
     * @param MetadataItem[]|null $metadata
     */
    public function setMetadata(?array $metadata): void
    {
        $this->metadata = $metadata;
    }

    /**
     * Returns Installment Plan Number.
     */
    public function getInstallmentPlanNumber(): ?string
    {
        return $this->installmentPlanNumber;
    }

    /**
     * Sets Installment Plan Number.
     *
     * @maps InstallmentPlanNumber
     */
    public function setInstallmentPlanNumber(?string $installmentPlanNumber): void
    {
        $this->installmentPlanNumber = $installmentPlanNumber;
    }

    /**
     * Converts the UpdateOrderResponse object to a human-readable string representation.
     *
     * @return string The string representation of the UpdateOrderResponse object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'UpdateOrderResponse',
            [
                'status' => $this->status,
                'merchantOrderReference' => $this->merchantOrderReference,
                'trackingNumber' => $this->trackingNumber,
                'shippingStatus' => $this->shippingStatus,
                'metadata' => $this->metadata,
                'installmentPlanNumber' => $this->installmentPlanNumber
            ]
        );
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        $json['Status']                     = PlanStatusEnum::checkValue($this->status);
        if (isset($this->merchantOrderReference)) {
            $json['MerchantOrderReference'] = $this->merchantOrderReference;
        }
        if (isset($this->trackingNumber)) {
            $json['TrackingNumber']         = $this->trackingNumber;
        }
        if (isset($this->shippingStatus)) {
            $json['ShippingStatus']         = ShippingStatusEnum::checkValue($this->shippingStatus);
        }
        if (isset($this->metadata)) {
            $json['Metadata']               = $this->metadata;
        }
        if (isset($this->installmentPlanNumber)) {
            $json['InstallmentPlanNumber']  = $this->installmentPlanNumber;
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
