<?php

declare(strict_types=1);

/*
 * SplititWebApiV4Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SplititWebApiV4Lib;

use CoreInterfaces\Http\HttpConfigurations;
use SplititWebApiV4Lib\Authentication\ApiKeyCredentials;
use SplititWebApiV4Lib\Authentication\ApiKeyCredentialsBuilder;
use SplititWebApiV4Lib\Authentication\OAuth2Credentials;
use SplititWebApiV4Lib\Authentication\OAuth2CredentialsBuilder;
use SplititWebApiV4Lib\Proxy\ProxyConfigurationBuilder;

/**
 * An interface for all configuration parameters required by the SDK.
 */
interface ConfigurationInterface extends HttpConfigurations
{
    /**
     * Get current API environment
     */
    public function getEnvironment(): string;

    /**
     * Get the credentials to use with OAuth2
     */
    public function getOAuth2Credentials(): OAuth2Credentials;

    /**
     * Get the credentials builder instance to update credentials for OAuth2
     */
    public function getOAuth2CredentialsBuilder(): ?OAuth2CredentialsBuilder;

    /**
     * Get the credentials to use with ApiKey
     */
    public function getApiKeyCredentials(): ApiKeyCredentials;

    /**
     * Get the credentials builder instance to update credentials for ApiKey
     */
    public function getApiKeyCredentialsBuilder(): ?ApiKeyCredentialsBuilder;

    /**
     * Represents the proxy configurations for API calls.
     */
    public function getProxyConfigurationBuilder(): ProxyConfigurationBuilder;

    /**
     * Get the base uri for a given server in the current environment.
     *
     * @param string $server Server name
     *
     * @return string Base URI
     */
    public function getBaseUri(string $server = Server::DEFAULT_): string;
}
