<?php

declare(strict_types=1);

/*
 * SplititWebApiV4Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SplititWebApiV4Lib;

/**
 * Environments available for API
 */
class Environment
{
    /**
     * Sandbox Environment (Transactional API)
     */
    public const SANDBOX = 'Sandbox';

    /**
     * Production Environment (Transactional API)
     */
    public const PRODUCTION = 'Production';
}
