<?php

declare(strict_types=1);

/*
 * SplititWebApiV4Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SplititWebApiV4Lib;

use Core\ClientBuilder;
use Core\Utils\CoreHelper;
use SplititWebApiV4Lib\Authentication\ApiKeyCredentials;
use SplititWebApiV4Lib\Authentication\ApiKeyCredentialsBuilder;
use SplititWebApiV4Lib\Authentication\ApiKeyManager;
use SplititWebApiV4Lib\Authentication\OAuth2Credentials;
use SplititWebApiV4Lib\Authentication\OAuth2CredentialsBuilder;
use SplititWebApiV4Lib\Authentication\OAuth2Manager;
use SplititWebApiV4Lib\Controllers\InstallmentPlanController;
use SplititWebApiV4Lib\Controllers\OAuthAuthorizationController;
use SplititWebApiV4Lib\Proxy\ProxyConfigurationBuilder;
use SplititWebApiV4Lib\Utils\CompatibilityConverter;
use Unirest\Configuration;
use Unirest\HttpClient;

class SplititWebApiV4Client implements ConfigurationInterface
{
    private $installmentPlan;

    private $oAuthAuthorization;

    private $oAuth2Manager;

    private $apiKeyManager;

    private $proxyConfiguration;

    private $config;

    private $client;

    /**
     * @see SplititWebApiV4ClientBuilder::init()
     * @see SplititWebApiV4ClientBuilder::build()
     *
     * @param array $config
     */
    public function __construct(array $config = [])
    {
        $this->config = array_merge(ConfigurationDefaults::_ALL, CoreHelper::clone($config));
        $this->oAuth2Manager = new OAuth2Manager($this->config);
        $this->apiKeyManager = new ApiKeyManager($this->config);
        $this->validateConfig();
        $this->proxyConfiguration = $this->config['proxyConfiguration'] ?? ConfigurationDefaults::PROXY_CONFIGURATION;
        $this->client = ClientBuilder::init(
            new HttpClient(Configuration::init($this)->proxyConfiguration($this->proxyConfiguration))
        )
            ->converter(new CompatibilityConverter())
            ->jsonHelper(ApiHelper::getJsonHelper())
            ->apiCallback($this->config['httpCallback'] ?? null)
            ->userAgent('APIMATIC 3.0')
            ->serverUrls(self::ENVIRONMENT_MAP[$this->getEnvironment()], Server::DEFAULT_)
            ->authManagers(['OAuth2' => $this->oAuth2Manager, 'ApiKey' => $this->apiKeyManager])
            ->build();
        $this->oAuth2Manager->setClient($this->client);
    }

    /**
     * Create a builder with the current client's configurations.
     *
     * @return SplititWebApiV4ClientBuilder SplititWebApiV4ClientBuilder instance
     */
    public function toBuilder(): SplititWebApiV4ClientBuilder
    {
        $builder = SplititWebApiV4ClientBuilder::init()
            ->timeout($this->getTimeout())
            ->enableRetries($this->shouldEnableRetries())
            ->numberOfRetries($this->getNumberOfRetries())
            ->retryInterval($this->getRetryInterval())
            ->backOffFactor($this->getBackOffFactor())
            ->maximumRetryWaitTime($this->getMaximumRetryWaitTime())
            ->retryOnTimeout($this->shouldRetryOnTimeout())
            ->httpStatusCodesToRetry($this->getHttpStatusCodesToRetry())
            ->httpMethodsToRetry($this->getHttpMethodsToRetry())
            ->environment($this->getEnvironment())
            ->httpCallback($this->config['httpCallback'] ?? null)
            ->proxyConfiguration($this->getProxyConfigurationBuilder());

        $oAuth2 = $this->getOAuth2CredentialsBuilder();
        if ($oAuth2 != null) {
            $builder->oAuth2Credentials($oAuth2);
        }

        $apiKey = $this->getApiKeyCredentialsBuilder();
        if ($apiKey != null) {
            $builder->apiKeyCredentials($apiKey);
        }
        return $builder;
    }

    public function getTimeout(): int
    {
        return $this->config['timeout'] ?? ConfigurationDefaults::TIMEOUT;
    }

    public function shouldEnableRetries(): bool
    {
        return $this->config['enableRetries'] ?? ConfigurationDefaults::ENABLE_RETRIES;
    }

    public function getNumberOfRetries(): int
    {
        return $this->config['numberOfRetries'] ?? ConfigurationDefaults::NUMBER_OF_RETRIES;
    }

    public function getRetryInterval(): float
    {
        return $this->config['retryInterval'] ?? ConfigurationDefaults::RETRY_INTERVAL;
    }

    public function getBackOffFactor(): float
    {
        return $this->config['backOffFactor'] ?? ConfigurationDefaults::BACK_OFF_FACTOR;
    }

    public function getMaximumRetryWaitTime(): int
    {
        return $this->config['maximumRetryWaitTime'] ?? ConfigurationDefaults::MAXIMUM_RETRY_WAIT_TIME;
    }

    public function shouldRetryOnTimeout(): bool
    {
        return $this->config['retryOnTimeout'] ?? ConfigurationDefaults::RETRY_ON_TIMEOUT;
    }

    public function getHttpStatusCodesToRetry(): array
    {
        return $this->config['httpStatusCodesToRetry'] ?? ConfigurationDefaults::HTTP_STATUS_CODES_TO_RETRY;
    }

    public function getHttpMethodsToRetry(): array
    {
        return $this->config['httpMethodsToRetry'] ?? ConfigurationDefaults::HTTP_METHODS_TO_RETRY;
    }

    public function getEnvironment(): string
    {
        return $this->config['environment'] ?? ConfigurationDefaults::ENVIRONMENT;
    }

    public function getOAuth2Credentials(): OAuth2Credentials
    {
        return $this->oAuth2Manager;
    }

    public function getOAuth2CredentialsBuilder(): ?OAuth2CredentialsBuilder
    {
        if (empty($this->oAuth2Manager->getOAuthClientId()) && empty($this->oAuth2Manager->getOAuthClientSecret())) {
            return null;
        }
        return OAuth2CredentialsBuilder::init(
            $this->oAuth2Manager->getOAuthClientId(),
            $this->oAuth2Manager->getOAuthClientSecret()
        )->oAuthToken($this->oAuth2Manager->getOAuthToken())->oAuthScopes($this->oAuth2Manager->getOAuthScopes());
    }

    public function getApiKeyCredentials(): ApiKeyCredentials
    {
        return $this->apiKeyManager;
    }

    public function getApiKeyCredentialsBuilder(): ?ApiKeyCredentialsBuilder
    {
        if (empty($this->apiKeyManager->getXSplititApiKey())) {
            return null;
        }
        return ApiKeyCredentialsBuilder::init($this->apiKeyManager->getXSplititApiKey());
    }

    /**
     * Get the proxy configuration builder
     */
    public function getProxyConfigurationBuilder(): ProxyConfigurationBuilder
    {
        return ProxyConfigurationBuilder::init($this->proxyConfiguration['address'])
            ->port($this->proxyConfiguration['port'])
            ->tunnel($this->proxyConfiguration['tunnel'])
            ->auth($this->proxyConfiguration['auth']['user'], $this->proxyConfiguration['auth']['pass'])
            ->authMethod($this->proxyConfiguration['auth']['method']);
    }

    /**
     * Get the client configuration as an associative array
     *
     * @see SplititWebApiV4ClientBuilder::getConfiguration()
     */
    public function getConfiguration(): array
    {
        return $this->toBuilder()->getConfiguration();
    }

    /**
     * Clone this client and override given configuration options
     *
     * @see SplititWebApiV4ClientBuilder::build()
     */
    public function withConfiguration(array $config): self
    {
        return new self(array_merge($this->config, $config));
    }

    /**
     * Validate required configuration variables
     */
    private function validateConfig(): void
    {
        $builder = SplititWebApiV4ClientBuilder::init();

        $oAuth2 = $this->getOAuth2CredentialsBuilder();
        if ($oAuth2 != null) {
            $builder->oAuth2Credentials($oAuth2);
        }
    }

    /**
     * Get the base uri for a given server in the current environment.
     *
     * @param string $server Server name
     *
     * @return string Base URI
     */
    public function getBaseUri(string $server = Server::DEFAULT_): string
    {
        return $this->client->getGlobalRequest($server)->getQueryUrl();
    }

    /**
     * Returns Installment Plan Controller
     */
    public function getInstallmentPlanController(): InstallmentPlanController
    {
        if ($this->installmentPlan == null) {
            $this->installmentPlan = new InstallmentPlanController($this->client);
        }
        return $this->installmentPlan;
    }

    /**
     * Returns O Auth Authorization Controller
     */
    public function getOAuthAuthorizationController(): OAuthAuthorizationController
    {
        if ($this->oAuthAuthorization == null) {
            $this->oAuthAuthorization = new OAuthAuthorizationController($this->client);
        }
        return $this->oAuthAuthorization;
    }

    /**
     * A map of all base urls used in different environments and servers
     *
     * @var array
     */
    private const ENVIRONMENT_MAP = [
        Environment::SANDBOX => [
            Server::DEFAULT_ => 'https://orch-api.sandbox.splitit.com',
            Server::ACCESS_TOKEN_SERVER => 'https://id.sandbox.splitit.com/connect'
        ],
        Environment::PRODUCTION => [
            Server::DEFAULT_ => 'https://orch-api.splitit.com',
            Server::ACCESS_TOKEN_SERVER => 'https://id.splitit.com/connect'
        ]
    ];
}
