name: Auto PR develop to master

on:
  schedule:
    - cron: "27 3 * * 4" ## 3:27 UTC every Thursday
  workflow_dispatch: ## enables manual triggering

jobs:
  develop-master-pr:
    uses: Splitit/gh-actions-lib/.github/workflows/develop-master-pr.yml@develop
    secrets: inherit 